name: Build PJSKBOT14

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/PJSKBOT14.yml'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Restore embedded project
        shell: bash
        run: |
          cat > /tmp/PJSKBOT14.b64 <<'EOF_B64'
          UEsDBBQAAAAIABgGFF2fB5ftXgAAAG0AAAAbAAAAUEpTS0JPVDE0L2dyYWRsZS5wcm9wZXJ0aWVz
          yy9K10svSkzJSdXLKstNLEovttWNyK0wMjCxyFXQdUnLBEqk5iXnp2TmpduGhrjpWnAl5qUU5Wem
          6JUWpzpCmBG2JUWlqXCJvPy8kKLEvOLMksyy1CDnnMTiYogCAFBLAwQUAAAACAAYBhRdsqJfX0YA
          AABJAAAAFgAAAFBKU0tCT1QxNC9idWlsZC5ncmFkbGUryClNz8wrVqjmUgCCzBQF9eT8XL3EvJSi
          /MwUvcSCgpzM5MSSzPw8dYWy1KJiIENB3ULPXM9YXQEkWamQlphTnMpVywUAUEsDBBQAAAAIABgG
          FF2wK1S/rgAAAEUBAAAZAAAAUEpTS0JPVDE0L3NldHRpbmdzLmdyYWRsZaWPsQqDMBiE9zyFOOni
          AxQ6tGKhttYQ3SWYn5AS84ckFkrx3aulSOnQpTd+xx13Vo9SmYobLmEAE6IHiWY5sOhVQKfAv9Ei
          iSg1JOkKBn4Dk885x/UHlo4LDfTVTdGF1ZzIRARYMAJMf2fgUY9B4e8BFQrIPISEfcPD7nju6ktH
          WV0WeduxgtZN+u+DZaRDDNThFfqQGT5AtI1iWjanfd3GRJlejwKSeMOtjVPyBFBLAwQUAAAACAAY
          BhRdxNf4/N8FAACwCgAAEwAAAFBKU0tCT1QxNC9SRUFETUUubWR9VltPG1cQft9fcSReWlUx4ZK0
          qsQDTUmbhjQoIFV9KsZswAJsZBtVvBlYoo1xEtN48TrZdU1rcIhcdWMcYiT7z/Rxz+x/6MycXWzS
          i4SwvXvm9n0z35wRMffd/P2vHi6MTWoa1FryIh8U90Xw2hBw0IC6I4JyUdZNcDtC7l8G1bIY9z1H
          yAsDDFdIzwZ7JyiWYpo2MiLwO+ztQKUEBhpWLXC7suQIv72naYHhwaUt4Pce1PYF1ErQ7shCWUgM
          c+AIqFtk6nbwNzq7IaDZBDd/3SV0TL/riQf35udViv2GPO+ISf+yCM186AN978v6Cbrwu51r9vIF
          mlRa8teWkG1TzM08ujtzZwGLcGDPxfOy7Em3x7nbBoJByVL+stVFJChZqB/6H/DEOxGVw3X4Hga3
          DHlgoj3i1A0KXQG/7csTWyA48twYhYsy1HcYJYznt1uB5UQQQ78sX2KYtuF/6NKRETEWw+xN2Hsq
          /npyyByc/gGuIRam58DpyWM0atvytKUhHnDcCV1QiosLP87N/HR39t6d+4uyWRRQaEA1j8AGZSM4
          Mhne0LVKdGD0zcPZrxeJgj/zFIEjV8uw2wkOHS6xZsJRh1F0e0g9Z4NJIQdyt+Of1/lERcXQrhrr
          S6ZiKCIigFA6Brztg2tHKFwLhyX3YT+vvBsU0m/nYbc1cPXZ0OEpwfUOxfHKXPtxh2icokQVruOx
          EMwh67AXT3pRqBAXAtntwoErsHhZOImwXtXjy2JpPb3Eyb934EmRTxw7YJCVvDQIrbHYBGHp9jSq
          TL59A0dDBQ7iiKDSIPqxoRFIspQlRNK0/xvNELFr9kSjyoISp9YnlAPbCvYcxkI14I0o43h2U0/k
          EJDJW/hwkBeNJPv9qKkv8vDkmdiIZ9b0DEOz24JXZwrVCUTVIs4MkoqaQYMqj11kgnQDjBoBccbD
          6L9viW+xzyIwFzf0zIq+sL2pf/LpIg08vaTQ5BCnlFL3O3noHssXPQRNwxERuUw8sca9seOGs09m
          nJZTx5+BZVMh2VwysbYtNjPJdCaZ2wY7/y9gfv/w0YPpWTGqegg/yRV+0DRwU5gGAoejXyJOpHeG
          HRHOIM32wRvC1G7Ims1ax7lSIbLZGEJkWU/Et+mkiaNEDrG1QpgEDefzKlOJee/aXIfSsgEVES6y
          ZLPWWQVwiwr+yZjKGXUUaocs1YVTToGFS1PCHWoon6QWJmez0wszLKchYFA7QZ6YtKHeuzHsXhBx
          DWzvLzayOLO/iImb+AXqRoiJPM/77b5K7FaYGNIUjl1Eu55aFo/XkR2RiyP/OQ6ppHmAGUqMPH+P
          BfvvPIRFo99FlqYQuExyaSmdEivxTSGtIlVbKWGjOyj/nBH92m2RpjfN/5+oQT5KnalYsR7P5uZ1
          PYVz9Q4O6rQhrgrh3VS3cMkFNZOb9W4mvqFPJ3LJdCob7hsauzpOEMkWkYwrazW9vqz6V8DpU7X5
          HKxPAXY7JqYTCT2bTS4l17FjxYqezW1ldKTb5GjliIzE6lZqTUyMhyRMIhv4CnVOjE2Ez8Yn+Zlq
          6wFd6qk0TNkimrlREulULpna0udzmfSajqrRRRQZMd8roVqgwc/xXGJ1Ob0ixm8j4Srdz2O4M8tq
          b0XXA7wdgFHXwDYVA9RWlBY9sPoCXpeIawJsWc+hAqUz4jEhN9DrwOogeNrYzcebWfFo5s5HdwDL
          QFcECO0dEhYSvnYfXnk8Hs3ngL3MDONLXq8cmYYT8xhVcIRpLG/pETGUHJcWCorcfYOe2RFdUdzi
          9asEBuVrCPZdKMfcl3z1CCMOjVGhzC5xKx1HF6PAuhJ5lS3dDIyXPLZK1/0PDlxWQ0WjDqp4ftuj
          Oibgsjt6C/8plVTHpwQ0DsGq8jNUKwKU9h5yfYS7pwPNq10qX1Sx867sfG8H/4Q8ywcHnrrYcMPy
          jp+KnFwYQfVZtD2nxPwP9+ZmBht3cE3557trnvieWNmXzzwCvtC9msMJvhLQyA69xeXRoHuW2sAx
          7W9QSwMEFAAAAAgAGAYUXR9gM/72CQAASgoAABkAAABQSlNLQk9UMTQvYXBwL3Bqc2tib3Quamtz
          jZRXVBMIFobTIdQQqor0DkIQ6S0gVUeaBaIQmiAC0hLKKkgMvbcIokAMOHQRwojSpTgsEAQp0ru0
          0NEMVVjm7Jxx92n34Z577vff+3g/FJHFBAQEo4jwLRhcLtosepcdyAR8SYTPQojwyVM8iiJCK/8r
          glIgRGjuKc4+racw1r8iNhYg6DREn0IdlPvfF1B2FAal8XNkQ8lDeAaREp32bWsT37YZ58Ov2hSn
          25hrgEDSCBBQBMUGY/73LggOBaDOw+BO0WZANzAEKAdBNBbbxRai7yX0F4sgKDWqDyFESN8yy1HE
          uwWZ8E6Wbh+ENfkZ/ygiaFz6LKkmzWCvkDeL03jkBWUk1dMeiy3GKfBnNaHHQGQbLvvt1pGpdbLE
          VwcSuRDeWl3WEUfLAS8k2V7w87sMCq6d9VLKqqZlBW31naernwnrl0y5z87TYyBoFaS+cbvG6YiL
          IQzk++Bh6yMgZs6aMcQvCO3b1o/KXC9erWnPFNNESwpPhFp0XP9FjoUaNycFLgC+bRJ7+/RYsjHs
          ejM9XS5yIiqkRefcMPLD7M3Cg0727D/eIJuf+MzHtbx9rw1kCwzOajEsLU+9q5xouW82A0Oo50Yk
          rBx0PqFsqX0pt2dMCRMM0oCSpczRumZmjudGhCef0odk1WirlCcyiohsIH6ANd76M8PdcVxVCK9j
          O1303ZoYsDP4ltLIMTTa+SFKe3CJl8vW+rx2oP4VT7q4DuK2RaSa3TxS6/d1tKfJE1WVNVyg2a8r
          br2LI3FWdvGbD3h0vfmk8jTEasPwTMAf1aChmAuyYwKLOqm2+4ybdqPxqEvTXJOVUtvx4ZkhELoe
          MD3dNVHjIFylGKCng0UwhCxidy9m1Vsjpu58QXNuwbaXcmeM2nDlomRW7Kc863ARcx9x3SD0KHm/
          guRZxDz2RkQ+VEpCU1E4r9WApCNRWvCdiXScpE9dlxS/HhP72bgmSXW6WzPZx0mxHntxNjxsuVrF
          kqeNk/a1igojDYM7o8CdcWtOOyWxaHDArhzsHmwfWtHWi+lcIPDL5JYoJahQAImyuML3BCoec7V2
          ordt88hYot++slgFUK/5vbPLyD2SuJW6R2jHCq1LJb+NpkE6Z7nBfiLR3+3zxPeBcI0XWx8PiZ62
          y+CNbXRFbcASm2TqHbwYvyvfK9p8hZSba+GU97ti7VIobROeqQmPXTln1K33UEmdaulgeydaU8v3
          bM7dXj9z/HiZ794qwGI5IKBMmJwNBfWEknDKD0wxjLsNlh/tSDtT2hAE5Pd+gZWIUdWNr+DExeNU
          +/z97ir04FUw3jm/mO+NHHwitBHQ5EDqGmGeEa84sXASmgKzi2rxFb2/nji469cYuGtaW88oethf
          2LnDQZowGoNZlXiy49sF0wdNGwsuhor4xVCvFmVz6jwff7QqPWt75DcqP1f/jaEl9RHZECDteHE9
          t6lXXlr1syrMm5/urPF1krpGTTmMbncvlQwynXRU5xwXnfO+xZzGYJV20g2wkTDI17g5E998rFt1
          w6dOjn1bTfixpr/AZxZN7j4RLrbPuePyjc1YwiJC298X0IW25l4Z8yGUO2Cw3RUleH+X0vSTP5wD
          axNtV7xMWj0Y9xOWNzpBlUuOfNTS4B0r7vn6zRSBATf8r9l9HRGhgYgBhU8VcPLzeVwEXQw7Qasy
          irvTWhQSKSxhAKtSaEsJkwT4c3S8HsjpaD13h05zdwq7fetRwQoV0nH4/lXEGns3fBXu4oMlnhz0
          QoIcH1OAvjy4GzevHLsGxxZLimcPCotCWuU/luWVBhyKUd6yRYQ/pOgHsag6fjNcCPOyGOfYPcme
          fyAtx8m19ZEIaIs5js8d5J7wZzHJ5o+7tkMawEdOG2xt2qXfx+hftuQqxRkXLTwcovmL5DDvumet
          biRwF+nCsdMdMcZJVj3B3o9GXg6RaYrKhn9K7y9dwnmUEUIcAD+AJwAH8AK4AHwBeJToz5hXmQeC
          vHH/gZuIsrqGurKq6iU1FZSqMooI+bnEBHtJhCBPEQcICDhtTP9h8/8lasYF542is5Jxv/EbBqWJ
          WWsW6Dkj/h9RTwrNT780lPewrdtaMlRJTicQwamYqaZ9mfTxPmB+rEWX4yWhleF054yK6ohGj1R0
          11Ztorrc8cws9mPctE1Htr8TR0NUInJGaMkA/TLj2dLB6livTGr32KW7vmMUh0c+GdygT2kWB98m
          bfTlW+TfYySjZXk1najbF9JxeINvacpu+XvMXQJqK2ekM8z/WagyN0hcVCPHOzyWag9J7S5oNtYe
          XMMTvkyEDXu3FPO71pGV9KJM1ih330HOZxBcXmGipmrmokIyPfjkaerHEIUbCd7Ntx9/TiZC3rQ+
          Nujk3w8YUCm75udodvTgxUKlkj0ak6Zht6GgRqeCY6t9207QtG1C7p6/TWNChmlNvSxjpcE5TGm+
          u2k6F9Q3dRUMdM1UEhu1tGsRXm5Icl3dURRQ6BgZjjoyH3XHDl/BFT0wuqR+mYq9GFTOZNyYy96W
          bbdn44X+hxLiyYAh/I7KaEqs/XMHKfEtaYyiminURYdAiCXvzDnTJQNFDqQf0sv+aDgj2PLCqBw7
          YQz2I9m1zf2wBoqDIycvVwfPPCMR2x6u0h0o2BUqheX5bMptzoLffgRfGWOqrCeQ3Rx318x24VZB
          LS1jhGkP2BZKR6btSbrVke6I03YvYmq6bg0Hb3fV3+PeXIzJkJxUPUo4moqNOewgAXqWC01e8TZU
          i/rkAfMyMJrto+W2C7OrWoE9vN3IaGZD6L3Wk/2AT/FwLkX0rb3fgkTbUrLC+ZDss2+MfnD/Ehj+
          C8CUZSEHKQA3ePZ0MZMkAyWYRxbkwsgLhXl4X1vA7Mu+NoFK4eV3qawBofJ02lBIS/t12R9h378k
          cQwkg2Qla5abeV8vzFop9Ix6eV3BpRxSx0O0uqYu1fHZFXhr6TvMOJxB9nYLF2CjBzor5ZoXrnGC
          71eFqU1K32oooyb5bmJ69h5xWaQGdL1m1+4eawrhzvc0zlMOC+35dOC3r7hX9GPjWok3Z7JH2Y0C
          dgYHAKyPzOMQ5JNNWmn9XS2z5vpm9YeqRh2ci80Xvfh1xXMs75RBJP7J6JKsEI979rWOXSe8XdId
          j1itz/c4ArvKez3oeicQQJ40PMdjuGbQL++r7a/Lzq9ej7kyjHEkoFX8CupMzyeWszxb4980vyPM
          2MKbEpZjV7WRQpgWeWiKsW40eBMEEyzLs3exqbNj2ogrtzyboYcEaYUE0L0K7zlKhIvbJwtaWHo2
          7IrsVtUeCo+g+kuK8y1oX/3UXSpiTM70SWXFoq6hlFHsf78tCAgFQERQUozop4deNEML5b2Ca3Wa
          8hjzgW3OvX3zd8icfhWKCIRHL+XpSOB0B/G1//05UsfzW3IWgOE/lfAvUEsDBBQAAAAIABgGFF35
          0KcCRAEAAC0DAAAaAAAAUEpTS0JPVDE0L2FwcC9idWlsZC5ncmFkbGWlUrFOwzAQ3fMVVpbCErWl
          lBlVRSpDiyjqii7xJbrGsS07KYpQ/h2nMZVJB5C4wcPz87t7vqdFU5C07DNiroizSaaqBCQ3ingC
          WgvKoCYlJ1EXRR73bAkVWg0ZDo8qyIxK9NGWqaonZ4aDNQnc85Ld3UdniGMOjahXSuZUeKG+glYb
          zuIrwfjCrEj2gvPlBanBFFj7Lt/gCY11YivFkc0WY3jrZmfxbJFMB+FumM5SIUkWw3Q2GM9PESBn
          eq0MPjmHLHfHTexZybG08e018wWs/VDG2fPE+XS+jH/wSmwfBYG9UK6ufxHpQjtpQ4K/tRpDKxzT
          phgbCX2PfuF7A6MWfRkUCBZHYm5BlLdrCalAznIQFv/bzPvxedrpPiahJ6sak+HKXbsEpSSobtkz
          nOAwbDs5rF/3m932ffYwCs2fn3Qu/19QSwMEFAAAAAgAGAYUXWnLCxEfAgAAcQYAACoAAABQSlNL
          Qk9UMTQvYXBwL3NyYy9tYWluL0FuZHJvaWRNYW5pZmVzdC54bWytVctymzAU3fsrGO2N2l3HA04x
          Ji2pbTyGNJMVo4iLowYkRhJp/PeVbbBN/YinDTt0zz069ynn5q0srFeQignuos/2J2QBpyJjfOmi
          Wuf9L+hm2HNKwlkOSlsGztWA8EwKlrnoWetqgLGiz1ASZTfnNhUlJtULlqBwc4aGvZ5lPqdWoPoV
          yJKp9aVWYx9wUoKLWoY9wI4f4ySYpt4kWCTpQzgbRw/IwsN/ZLuNFsG3RXQ/G6dxsPgZ+sGHkqXT
          YBx66XwR3QV+Ekaz/2CfR3GSzqIkvA19b80Vb8i2bKSqCkaJNsDNwfprGUlRiN8jQl/qykU5KRSg
          I0xBnqBw0fwu/jGKkmO7NhU1sr4qvSoAJ+s/uwU3GrY6qGavTK92J4ck29DsKWHca3DoJBDeKiE1
          mI7SsobTGEUlAI8kA643cbtIAVdCTgxCUVIBGnYcHca1wfZzVmiQXdtO+9lCbJ3tLcaeeuG+lB0S
          UwNYCrm6TNOi7Il3P/O/B4sjMgefkevgNseHeVcgXxmFS2n3SaVrCfEW+V7i/+qTQ1AuJCylqHnW
          cCWrylxQQsbIXIpfsMnRvjmvFejVWniUgmn3J1aYAC9K3U/GyWkZmc2Qer4fxHE4Cidh8rgb8Ksi
          /8jeIYdBNYmwT0b6bhd0rSVo0s+IJkeCrheCzvqadS1qSddjb/Y87jinjXdKBc/ZsiPcwY2xXU74
          YDuZ1wO3z8ew9wdQSwMEFAAAAAgAGAYUXaYcQsTsAAAApQEAAD8AAABQSlNLQk9UMTQvYXBwL3Ny
          Yy9tYWluL3Jlcy94bWwvYWNjZXNzaWJpbGl0eV9zZXJ2aWNlX2NvbmZpZy54bWx9j8FqwzAMhu99
          iuB7426nEeq2ULZex1bYcbi20ogmcpCUbH37uSWHhcF0ERL/hz6tt99dW4zAgomceShXpgAKKSKd
          nRm0Xj6Z7Wax9iGACJ6wRb0uBXjEAEVmSSpPkRNGZxrVvrJWQgOdl3LalyF11vcXyyB22plFkWsa
          qggSGHu9K+xEOR+3s4ufvyJzdhZ7HoH0eO1BnNHcPpBi+npXr7BvPJ0h/gO/AMSTD5cb70w9TQcg
          YAxzjpJijcHfdI7YQRrUmcfVPBQ8vQLXibsDiA58l+IB/qTeIH8M42S7T6T5i2zgWwFT2M3iB1BL
          AwQUAAAACAAYBhRdqXlRv60AAAAsAQAALAAAAFBKU0tCT1QxNC9hcHAvc3JjL21haW4vcmVzL3Zh
          bHVlcy90aGVtZXMueG1sjZDLCsIwEEX3fkWJ+2ajG4kBnwu1KugPDOmogSQjk9Ti31tbha7EWZ97
          LncUY6SKDUY9yJpTMT0dZgE8TsX5hh7z4+a0nR/OIrsDY0hTAaFksuWkRWUHFZCQLbh8Z6+3lO9p
          ZpKlMAcWnbiV24T+4/5KLhTSGrx1T6EjhKjkG/qdqW0oqe4aCirx8EB20AgSV/iPwJAjnhnTzBF6
          OF6sRstxP6dku00PlOz95wVQSwMEFAAAAAgAGAYUXWo4J4ZtAAAAnAAAAC0AAABQSlNLQk9UMTQv
          YXBwL3NyYy9tYWluL3Jlcy92YWx1ZXMvc3RyaW5ncy54bWyzKUotzi8tSk4ttuNSAAKb4pKizLx0
          hbzE3FRbpcSCgngQS8kuwCvY28k/xEYfIo9VcTLQlOLMpMyczJLK+JTU4uSizIKSzPw8uG6Fty0b
          3uycofBmXuvrBUsV3rTMeb2z5U3XEoSpNvpI7gEAUEsDBBQAAAAIABgGFF0AUMPrLw4AANE4AABB
          AAAAUEpTS0JPVDE0L2FwcC9zcmMvbWFpbi9qYXZhL2NvbS9tYWNyby9wanNrYm90L0NhcHR1cmVT
          ZXJ2aWNlLmphdmHVG12P28bx3b9iI6ABVZ+Zk40kri92Kut0PiX6giT74qaGsKJWEnMUyZCUztf6
          gLwUSOuHNkCbtEAR9CFBgb73oWh/TV99/g+d/aJ2uUudbAcBSiSWjjszOztfOzO7irF3iucEedHS
          XWIvidz4s/R0EmUH1675yzhKMoTDaRL5UxfHsduNMn/mezjzo/DgKoDGAochCa6E6+AQWEiscEOS
          rH2PGGNeFGYkzNwW+ygdHi5wQqb9hMxIQkKPpAbkPMHxwvdStxEFkclDPtz3n5LgKEqW2JwNJpme
          wUTu1E/jAJ+7h/yzbGEG/CM/yVY4EGgG/JJMfey2lkBs29iA4KllNg4RJ9FnxKPidjv0RT//+5UR
          ypYVpe79lR9MbQPH8D2w44ih0SIB/m0Arft+aFsYcLj2YQCMJMv8cG4qd+2TM/dBgtd+ZkqVDXYi
          uqLm2mZEDOAR/GMfOQGuorMyYZz50znJQCBZZhGxGG37IcFJG59HK3N6ATMiTzMrE3I8win11ng1
          CXwPeQFOU9TAcbZKiPAeBCRIOE2R/PvX1xA8ceKvcUZQmoEbemgdBfAZkCKyHwJASH3QhjXzQxyg
          YZaAAlDjuN7tNtvj1iG6iyoikow9Tq9yUI7vhxnq9kato1ajPmr1upzC+7XCnAVDRLFixCqc7k9o
          XXAvFVTxHOSrXqQCaSaKxHqkwVoAJUhu9RqQZjjoTDcjfRnkDEVrkhhcS6NgUlylhQmMqAcjZJbq
          JAaL82yxPCQZCDBK0FR80YEOyWQ1HxAvSqh8EvGlMF1uOJMoCggOEV5lUTPEk4BMQYtZsiraDlV3
          6iWEhCcHJQPHBZQgAvuaxekww0l2YB06SvCSFFY5CyKcIW+VgCCyo1hK6uc9kGoCwYMDc9dZg1ch
          2LZArRlxqsJL6JOuYggzm6GDfEQ6B13nwpfkOQcgcngNPmrow5G+UdlDnd5hc9wftB7VR02FsNQH
          UAhBz7q2VA6kUgSgpjGH8lRVmPLYAsTGrFJJqVhheyPzJFqFU6fgjHsoVDZsp3L5/LuXX/8WXX73
          VaWq0VddQ3CkOY+Tg8qn0v9o+PH93uiGCDuVPQOEo7qd+idUUL1Ba/Q4h1HWoE3ushU55rB0UY05
          R8cFnbWjCHTuaKuT5ge4w/M0I0tXGNbIX5KOHwR+6qjw/gw5cm9yPRweJvisx9055apRjWyjHwGj
          Mn9xjf9bbr3UdaKQ8deIlktYl8OTIzoCH3sMYhbgecq/MgG1pioLlGEOje6CfFZBgJ49U6Iseou/
          rYLVgbhCNBzVB6PxcNRqfPxYXTgQSEi6CoCVKfUNTpTKFXhqPs0S7FQ2AOAF+6rcBN8c4BBn+EDj
          kCUZ7qPmYAjG6Q4PPx63uiN07y66dasozw0JjYk+TjwS0ACl8ULhgBc+vct2UlUFiAQpefMJNK1q
          C1NFdhftU9mr9KXsdQ7SLIqHJJip1sI5UzQE7pxryTK5PcFDy3iJ7hre6NihqyzSMbcQmYPTaR62
          6uCyvY+aDRZIhs3Bo1ajWdXCZG5cd+mEVHqFCRS57CkCsVNxIYT5wETSwEEwgerGjDjU7wtTuDl0
          Ubzy0X2u+Og7yBBUUkpom842qjHemFFRj2dqQNxEdb7H8l1oQNJoldDdp0qFLGsUAqmbR99BPpkt
          WJmTHhQoHO9GYUH8+SKTJDTTlpx8ICkWxUNDBg2sWlpgriNPDsxhymRm9y2gLaRFaRDI9p0OzhZQ
          8T513r+9v5dP8A66WdV29xzx2EC89V6OeCwRNcwpCVMoPAAxxzGUWAMixssdRC1oH8Y+ndqqfCWb
          BRaUPNcFB2iJvMXkSAqq3ODMEaU4dgcP7tfHt+ExwW5Z+dSzc2BVcWa+H+rpfHkKUZ5BvM6ihIjN
          Ab26dx+1BqOH9fb4sDXst+uPx0ft+oNx/eGoN+60BoPewCSgaIYqd7hKZhhUUTUhacB/Lc9Xp0hJ
          1guZ/utr7LNdqU1DZAj5TcLt48a9gjsycE4F8X1HIU6fLDm3BDiJwMm62Pt85SekDTpMM0bSFvFY
          1sER9fSiMCV98jT/+nXLKMuBZjNYcCdlhgQpuEg6nAofGC/TYrohHz3Hdtk8dWaHKcLi09wO5SMT
          dtqWAL9NTTO1CsvUbvERsWlXQIslFx8polJAm3SolpTCrmx7qwNI3aMC8Cd+AP4j2wip+CyX4DZ0
          qkXHxpZkTZJ/y54lqY8AddPVZOlnjlDt7luxXTayDnP9dLAKQ8j5HSO9l08OC5oAJ+SGIG0MYjuU
          cBZ2LBOv4in4FtS1Rb+6gCCReQvkQEUTnVGNIX8eQn1nKO6Ct2ACqzvnnpmLlf0JuXGUGr68EdXF
          XiFGqZortxBw2av0r3KWbrhKaZCjuEtWoAobdWjrQZ0a4gHkj4sha5roRbSlnFFkrvYnWBZAv6xV
          UQoKzhq9jWpVnr9/iNboDvx/A9Ws1Fi6qKhQIcd6GmF0dkWpqYFDwRGnrOVCEW8o3RJNbBLsA1Tb
          39+3xNpNtwRI5QEX/ZTBzyDfyNOZWntPzqows0EBIWivZfUM/BXzQ6aSMu/lo24cpRmrm+/c0TRZ
          Vidrcs6i+TwgvDPCnLNQ9+7iv7RyEH0MwDc2TW4HgkzKioCSQLp9ubZll823mbfEtIsP6xeD9k4J
          bSJevUtReV+9pVQ60don6TsiE7v85g/o8m9fXH77/cuvv7z83T9fPP/yxfPvXEtmZmev3ew+GB2P
          h8e9wah8l3LTRXRWWkNZI6j2196m+URLNrCNStXsG1nrfnv6oyi/QGQDsUVNlqBNbLaxqwq3q67y
          4jf/evmXP774/j/o8vlfL7/96uWf/nz59y/Qi3/8e1el7aAsu5IudnDYQi9MkYPWModw4mgddUsj
          4qTVPeyd2NoP6gkMmkRPRVtQfS2bqBIFoFhKnfgQJHk/VAV3QQytX/S6o3rbROrjKQs+N/eQ+M+E
          uY+9U96FZUeSDvvXxcl84kAAhtyV/6eVm/yYCbGITfnnfxc5j9k2yWym0h9WrCND/1fEqdWMsY4f
          ntAGgbNvG/KXq2XZsFxzjTPOPgygXtgIfO80r0vWZrTTTxXeUv4sBNkfJMGgz25JhpoUFzgp9fYL
          FZLqHWREz3NMX44tHly0UJd/9DHsuqlD+xnv3q5ay0JhJxCnthoKjG8sZdBsVOxj3Fb2zUGrsWzG
          7NYixqW53GbWcls3FgFjtRZjg99ZxkD1VYX8s5vlQhabOxewPKkriljs7UKSqqefHLe0kyAd0pT5
          ZlycdDvi0200u6PmYGcxcEKvKomb771bLgrW1TuPaUugtGt/8z1jxg/1M1JtQnf0uN8c1/v9tjye
          6gHRdv2xQeXOlVT6x71uU2G3HB4FsaVypZIpxynfmLfwdTKo98cN2D5Ad+Ub7xsToEp5LfKsu0WP
          E456jYfD+v12Ez27Mqm7ih5or/eQnlKM261OazQs50ztNI4G9e6w/ZBauZl2KFoNYnqNZ81bsdI3
          Rr0+epb/1W4ejQ5UBJoI1G5rryh27da76nkgu7vAjpg/fYJghaFwev7q5pODAii4AwBGiT/3JSh9
          ZQKKk3RKNcHzOb1bwcHlQO1JwatZVBxFK2+RR0VnvUfzR2MjTc98lmWyPa8uznDSU9jKrA0LD0P2
          q9yTcev8MAcyqu4dq6KoJD7df0I75nSKAT77pCxLZ6A1FfRxGSgXG6dLNbQVqiagzkumFVLl1GYY
          Enw7oCjrBcTOsulATLLLhl9ImD7VhQPVuhCanQ2Bda7LSWJpxqA+NIFhxTqepM70aRXdQ7Wb9Fhx
          8/Kcv9zWL9OFxa9zlMEK19no6jqfi98qABa2op5vUGtF1POy7h997OWY+mg1g8ubLnQbFDk+uNAe
          cLCFva0dNUtrTj7CgsrFZnYY6TOB6ue0WDQVkktGWNFOSX4pbhCBbGGVyntTaLqQZKIg8Avy2b3D
          uJmfnyNY1mNNlGVRyM9W81tqUBrGeJWSTSYO+wGLfCOSZlqhWLjJlrIzeu02G30KaX4hWLp63WGL
          BKUFB/a8kn73K/W5WesdSG1pF8GwvTph/BrVt1nmuFe3pCQMb0htacLxOfJvtv7J/5/I9G+2hkXB
          iAv9RVkVlB5xbQ6vdj+6ekUx7ixCcZ8TqNCaQ2+7M9J2sQp4evmz3mig3tFR5Yo+Wo5hVTmn0kUV
          dL1kHEaYIsUZOY1IdIFxRrOZMqx3Gha0RrSMA7Id7xMbHo0mQbAVb2DBGxB6yL0V7URBO6E402g+
          IGAJei+hWHnmpbtBVu1VQJFVoafUXL535B9HR6hi4yjvj0uXQm+/jWw9c0p30Gz895vfc7JWaty+
          3BlL5J3KT9z92SxOEZj35vDByoVwkHv8eKVyvXwKAWkOVJbpL0ObRQlbVAtZRb6W3mR+j7Lg6ltK
          3aLHWH4vgWRvxjJmLyk3167thZPscpd0ci2/xXBbnX5vMKp3G81xu3eioRVDrQUdhUtx81Vrw9om
          Kt6yo0+4FBc/bBLwrjrtUZH0a6siqmWgZFUPKgL/BQOsYGIJSa/SwpDPh4Yq5RSsI7SnKK9aSuTO
          diL6ESfLCicGLRoVGvxnMSM/C4iTW4U5rwpLAwmTmBVquMRB0PJAuPJnCQMXMlKWD7q+N2a/JRnT
          6zJ2/F44j2jYYCe1JsSErrKQD267u30IGWAS6acFP+J5s8wctqTY6lHjVaG0ap4mSjK7ViN2BtSr
          YfrJvrgyZJzvv9l8hSte+ZT6ezchAcE/5Ly2m8vK7bIfVqiyzFGUqh9UbclF9cIrIUsgptZeW5Lr
          N2FZv66f86dfhv985WdDPCPB+evISv50IvfMq31Z/N4L3Jl+0W+xW65cbIrKi2sX1/4HUEsDBBQA
          AAAIABgGFF3dBkGlrA0AAClEAABLAAAAUEpTS0JPVDE0L2FwcC9zcmMvbWFpbi9qYXZhL2NvbS9t
          YWNyby9wanNrYm90L0F1dG9BY2Nlc3NpYmlsaXR5U2VydmljZS5qYXZh7Rxrb9zG8bt+xVofAl59
          pmXl0TSy1KjS+dHoVencBP0iUHcrHSMeyZI8WZdEgFxfCycOYAe1EBmRDAd1bKdwETkxEhdw/pCO
          9x86s3zccrnk8VwnddEuHOm0Ozs7OzM7Mzs7F1urbWoblNSsptrUao6l2u+7m2uWNzEyojdty/GI
          ZtYdS6+rWq1GXVdf0w3da7vU2dJrVJ3mO1eCzolCM89T12s5dJa6NUe3Pd0yU/M2HM1u6DVXXdK8
          RmrUctUL8NmgjmxozrJsyciWTi8n6UluobJFTU8+6/fwY8Yy1/WNlqMF9EZw72tbmtrydEOddhyt
          Pae7fRz9sRmraWsw1XIkgxc0tzGv2ZKRDGxy4CVHtxzYx+9atAWCGLFba4ZeIzVDc10y3fIsmcAI
          3faoWQcA2eCHIwRaiEg3Peqsa9BdBfmFMpzRDGMNFCkExbYFbCOWuUzdluEpK56jmxvEYX+VJhjU
          zkiA19G3NI8S1wOe1mCeAb8Nmk2rbgKoiVomm7+um5pBDAtWm7lwaeGd1fkVMklee3NiAHB1eikA
          HX9tEOi5uYszId5X84DXDUvzQujZiyvV6YWZCsw58/rr6wNnITkLl2bPV1aX3kOi8maASMj89Hur
          K9XlxXcqSNaviuz2wuLyxT8sLrCNxGLDFvPtFJmHcwdmYVsJ2FOO914KuX/6dAB+fLRLXh1vuv7h
          k+43u90vD4h/d8+/egV+Hfif3PO/3e9+covAKPGvHxwfdYi/d83//CbxfzzoHj1m/bd3/b1npLd3
          0L1+T42Qc+MHd/3r904j2ge73Zv73a+fIL7eFx3S/fvD7l/vEv/On7t3v0LY7oOPe3eu4YrH3171
          DwHi6GuYxePO5s3FhVXY5fkL1dXqxfnK4qXq6gLTizfGVsfG2H9zguoFkxfX3qc1D3DAOZgkJr0c
          9iilCQl0aLlIU9PN6HMwK/xLCQyYukG9eYAJ/lJKJenaiVN/drnR9hrNWerB6pajVjWbWbUp4mk2
          gxAEjqsmMUwpfVul1thHOL9zwB5FI6emiKbWW3TBzaAGLNPZi2AnNqhTJgIxFyyjXtUc2NUUqVNX
          d2gdu1wJSaFFBGIKLAMWxtqkKyBNCuTVPH2LBl3DYV6zLINqJtHA+jSZka+Y2ppB6yAcz0GLKoPW
          zXOGvtHwAGhdM9wMKLvVtJcs12PIJHBM+8BOe+ccrQncBaiUqsXmkQHXddfWvFoD7aQd4MUZgyeg
          dA061Aw0uYYxxIxlitpfYMJlhK5bG+ArqCfdNQOLmLyiAyUxd3gwNITR6uepSQMvjYB5viJwjZz+
          cF6sb2D1+oTQm45f1AAJ1wMrYY84NbDx2/LudkgsNo4qJaCiPMy65Wil6EO7xG0Om9fQXVVHGfEb
          jEcCNDAq7iOG2IbBbUl/G/rb/f6dhMsPQolQCpmOHmyEwtPrUNi3yfn/TJTxuXQhXjOZFuZhIifA
          8rYMQ4aRqR5QMiscNRk+8TgWwRefxDyEMVAhjNFJzcUYARXBGJ3kPIQRTB6+dxMHXYYtaQpkuCLR
          enAKwLEpCc2LtF3S2U52yoLXWviBAfLE6etEiXVlMtAV8SAhTIQg0qdSjFKNI+HR6ZkZsnju3Ggp
          eWhCBnBugds7Ns9pC0vipYjYYdSAfygCTlttWlu0ailw/tvCGMZWh8+63++S46dH8A+CMb9zQMaO
          Hx917z+CsO2z4x+e+Z3H4cnH+G5mcX5prlKtzPqfP+re6KTQXb8HwR7pXXnSvf8P/+BZEAR2utcf
          QbQG0ReEfJ9gSNbb70BgiFFZ79az3t4+LA7BXae390TE6FmtWoO4hmV3v3sCkRvpffHQvwXE3fnM
          P9wl4/Y2RoDdG7cRmX9vNw7u+gwwdJMxgJxMhNQBPxKwge9qRT4jMRa1OByWjkbtzbG5ci5A6iKJ
          QR4oc1VvUqsFRk86WyRY4gd+09KNOgSSaxn0o6JkT1PEFdZUrV4PfIt8xxn4Uu4on192PrfG8ocj
          keVDsXMlZ2uiN8WC0NxYGNP3Ywu2Zfmu1tQ1ZKdSkhPEsSywCJH5UUSLwre3F7eo4+h1+RawheYx
          vHb3vUouV7Cl5QemWuzKxJJHNLaUBzt5UuCw2OSGNH8VbGlTO3BK1EZjy0beJqPkZOGJzB44Vsus
          K9ulIeaNlp9zlbbcNPBNsPNi28kc3cmWy9DqF4cgL4v6RQS9nOqHmaG5uf919ZP2yq0olzXJNd8o
          TWtTJj8xVpcqxjDKMKQCYBxYWSpmcoaR82DZDpanRIZJ6ewQCu40h6vRbeAn4OrocuW3lRlgnBhB
          S8hMrh2G2NYmF1/DAkAuUaoNx7qMiR5CRVIG7qnofobQkNHK8vLi8lu5mkExapzB5IVSwo8rOrrY
          Ba1JJQGkwCs5Z1KXDw406QJsx/KC5E5o8cM7u/y67bYwkSkD6i/Wv1+x/MFEztoJVwNeAqLNtpJ3
          X0OEJX6F4LLfp69t1kD+pv4BbEjBBG4qTRImTtUaRIOOeM/i85hyiERCUg4izyEKwoo4Ge9adkVm
          nIH787SYw1SiaJYGfydkNJAHspRoiEhyIE5I1ijGzWIcLcjVfM6KEOnUYoKoVGoRTQEPsSOTmUP/
          2AJxLbWatjKWI7DWWlP3FCFdzlLB0zVczGX7hd+iqofd/cxEcJyHUnAmspSEJaiwJXPUK23Xo03V
          1EwLL7CpWyRHogqSd/NMZKwZcPGcNozEvHwTJteYTEIa7M0hh5J1yyGiMPpvF6RB3iIJXFkOLEGX
          DZf7hopJ3EYB5yXZaZ4uxbl1UCYeLkhsUENrz7vDnXhkWP/Roq8MPEziUaP/QiLQzcVrqg3Qs0gO
          GCQw26emhFUH05VaV3Ksd1JU8qZhp9zP5YyVY+7kcDTAkHoaYMw1rcsDT0IALhhg8QGg6MMZ0zhx
          clx5kPv+54b5wj70VILOYloRGUyZZPjxyKCeQItKXnklM5gJWHgqZYmnpM+xuKwUVfLFeO8a8fcf
          Jp+gezduHj89wrTjd3eJf/9j//oB8a9eCx+PSfdvD3u3Ot2vnhH/T0+6949SKcV4lwOdCg+V71iw
          FfRl2Ab7oagl0+kyqMxIHpvsvLNJeYaYxsFByp0MGSYUCwLyg4md9JK894r0MtY/fnCKnBl/PX7z
          fz4KhfUDtzMpPELzaKRp6Ybl6B9kZqUD2uUXhdjKnZkrC1UfJfILckYsaYja5QY+zyonYu7qbqVp
          exhnZ5ziGNKmdBNuJKxAgJydjInPnueqLpgbQH2Wr2PJiA9cjA2U/moWhAmlfK6/sM3EavLLsVy9
          EKgrECTyZwH1MWkOYnolAVkU1UigERHTuGQXYyKH8sO0wjGHiLVKY4JeFHPObDdpbmfFSGHZwPo6
          s5By3p+SeVcZsoj0Ym81ZwY81YRUneZOCjmVOyNqOScPNjM+Vzj1kt6Ubiqso0zGQf+GzoL0Q0OG
          RfoQKY3i8l6cwt+TBd6Y+hzKqt8x6baXspKJZIEXvkvOWC3T4yo8sLHQna/ngCMA4boY9SQPzZZm
          AFtAR2XhDr/W1GTSSK05VNsUTknevWEyPJIOxcdZBT7DhUB2VWlE1xM8sycaKjXrEEzUNvHPHK85
          8FUYW/wyjMtvl5FDqqgIAVz4gNpAqIaaejXNUAtJQUqG88KGqwcsVmuW6elmKxSLYpcJhOdRQWKZ
          XTBkJITqx71XitdFbKhW7A4WML3MWMSX2ET9Lu413LAED6cOqQxAEE+l5PeSiA8sT7IetRgzn1ty
          UbloOQiSB+Yli3H35+KaAPdTMuqNF8WhrOAiQ+UKpDkCcxXbxwx3P6yJxDac1PJMEDtv8RHLijOe
          7zhgG0LS2F5MXURMdn6IErUBdRJRi49kIejsuomoFX9CyrtqFnI02P5tZ4PtZZZP7OwKQaNDzBdP
          YY2WeUxssddsSH1mo4jHlNQWDGvEgnui5XhDlqZjk1m5KCuGiMHKsQyzLCkeXco++ojk2bi0Whe7
          KkXrxPaZT4HjNXdgfI8t8im51+DoZudp8+7AC1JWDRuSFF/J2HW4lLgdJSYNqLHDvarrLCj6df9b
          NW+F38WZSE91Pc3xksQDndGexNWK10ciHaC8+CtleFA4MZ3STHRkungsMs/CT8o0hqwuc7/7zVOs
          kWRFlCxruYe1lDeRM+l0JEyZDr6nxr5RE5Rhzi6+u3D60hI5/vZHwIHlm73bezDWu3ON+FcP/c5j
          /A7NjU73y0MZwnF7u/vgU+Lv/yWq5Pxi139wxT98ihlRwPqpf6cT1Iyyr9kc3caKzIjMXufI/+c+
          m/bDw+OnH3dv3iW9K4+On8rzqUkOpko1I7Ek+CeU6RXzzz9LvWKopP/JqsUM2yqEhIkbNFyhReXm
          MwWvFs8S9L8z0Wz3U9TDPTH0k+vJJyV+sJ9TH5AZ4skA6JMn0wl06UbSFdfPUQ0aKuZLVRNaqObu
          uSo78yYU94d8Q0VNCPDEpOQBpAgmbFkvGmLLqYWM2hAPNtnTIKzCZ24MsQrMLfbmJJsx+P0patkF
          ethk789yLC9ObeNa0hertnxFaN6E/6st289/kepJe3/OOtLEwsOUSoowxXVvCLG+6JfrYs/RabHk
          hRfcDTBdoalvmJaTTmUVY9ZLXDMmMuU1vmBlJPjJfsUmVDCV6f+RhZLuIhR/Amt2cnHhw4zjtGz2
          FcydkZ2RfwFQSwMEFAAAAAgAGAYUXT0nhw7cIwAAkaoAAEEAAABQSlNLQk9UMTQvYXBwL3NyYy9t
          YWluL2phdmEvY29tL21hY3JvL3Bqc2tib3QvUmh5dGhtRGV0ZWN0b3IuamF2Ye0973MUN5bf81d0
          8iE1DvYwMza/AvgKAsHskoQCsoHaSm21PT3jTsYzrp4eM7O7uQLiZNlALuQCCSSYc+rIkr1z7hzi
          5cwW+Wfuo6f9P5zek9Stlp40bUJ266q2K8E9racn6enp6ek96WnRn3vXbwbeXGehvODPRZ3y4jvd
          d2c78cHnngsXFjtR7PntetQJ6+WFoB765ZMLDDxLfMdf8svtsFM+OoiDo71GI4gO5tJ6cdgqH4ki
          f3Aq7MZE2iudhUU/8uMOlXHG786fDahsFmwI/Nxib7YVznlzLb/b9c7MD+L5hWNBHMyxQrzfPeex
          R0B0Yz9mfxph2295YTv2zl04ffw3r79x5rUjp7zDXvXgaOBXT5185ZcMtlYAduaNU8cY6GQB0BMc
          dIq1xgbLm3fOXzy+FLBsvGEKcIYxrB+kExutjh97fWfqwJI62+m0Ar/NoMK5dy0wrU676dV7wetd
          0Q54ZI1LvGrjshbyZTCexz2uoBlTmglPPB92y2GdUUptY5rSZwl94vuAfR8Q37E8lqa1KU3HOrB0
          0SSZ9t5z/N8RXTXTadXP+VEz+Pt1VtCuv8rblsJltSrQITL/z9wPshiWnNV4h9Q+Fsz2mkc7fRut
          RSOr496A/d+vsb81C/WALvFgMVCoJrGXMjSCWOkboBTf2JvEQVKuXwUCVSkKQcqASunXIE+NygMp
          AyoFKsDSeFuehp4n242Om6Dv9OrN4FTQiJ18ilBnwuZ8AbALFhCYAg7JfphmLNoPui5QKXemvdhf
          dEJmQ2Lam2fvXb3jgQylHHnh0Qgw7gLAtjshLpipVIstUPnGWoCMdqZgJJemLWMsRHRzHg4bKAG1
          ns5DXpBQFwgIbCMD0Ho3TYfWAUfnejRNxUaxZNGJMq0gx78a+QvBkbk47LS7Nqb/6ZxFAmeDrQ5v
          Cv+plSpRXW0paFzHSXbxU5EzTUe8MD3yOtPkjsIlPw4oep8Nmgt5TQaEZl9K54O5z+1OtOC3xqWK
          AFUa95r4b9yJ/ZZCMoG3JLHhXyGSBzuUxw6pm5/L3svKX2Lqs+fX6yXrHAAV3rUrjzRseCUurw+r
          aumYaLkOHrS6gZkHtdMxTqRiOUBHHUNyFoM/gfBNDb5olx9tdWa1/l4I2+cZKU+246AZROXXjpz/
          za+OnHrzeL77F/x+Durk6yRU2L5QCNeF0bhYfeMCYFHnYnennCqhc2rva370LqymTDaS48TQhgXp
          XvPj+TJ7L8HvcQ/YeSzflYJ6HNDvl+A3AtZ0QE5AFeMFAByYCC9oCEk4SUSWkk8AsukMxwnn7QJw
          /p5P59o6JhMKO9CZJ8JbPq2ZpjWNNOwTnqh1jzKk+Tw91y+xLvCiIO5FbQ/J7e1C4o55L3mV8p7G
          QTESsjyNqNOOL6j5gFYm3MWwHs9rYOe9CexjE3o+gBlWx8rBCeR+d5GthlVwWdzurA+rjfEU79hB
          U6DNdjvRbAlHcKcYJ3bg/XwhXuyUkYxFuBGxXijEkIhVB5U8mcLiBwDGlzGTUYE7OuX8SIcnY9iO
          m2E7LobtOBi242LYjoNh5dRT0nsKBTpiOHTYq4xJflBmHEUE8UYgwzWEHsA4hq+BxnRplgE3GnJN
          XQS6CdBNErVRc1aNaVbt8uTeRr7qMI2Z82lDgNdqGjjOkyZ80wZ/wkBP0S3rB6U3HLPh6504OBf5
          jEz5KVFdU3Ma9fQPA/3DYhQshZ1e94KesKSAomEFuFy1ZuBHmf11bTLrBkH7oMFVxBQWRkHd/Awc
          czb2o1hNxAK7c/NBvdcK6sfythVe6Tqa74L6WyCmbIlHUKrpqXwgnp3rRIGehCxJpmA9qYSmLUGZ
          s5X00X3+SqfVic702kqXZyYFVdEkjBAyr2GE6D+9wcGu4FqMB/qcyDSTIMrNi6ywXQylfU405jpW
          iQmoXuGRg8udpxs5fWOA9DXWZLxMjBAYNmfZaNBHyELY7YbtJq7TuuYIyNuzCiyK5Lhgw2Zh0eCS
          nlYr3diazy4YpTfSpNpjHd0jeKCQAVQ0Rln2poKNrVHhD6BoBxe91DFwaLok5lkid9q5057PFr5L
          wYxYhxZHkSfDdCZt8PfOcGXrbVznsp8z7HMnGtBYcmhwPRD0YyDIybriYtDSoYU8vQIPgaUB/PXW
          OP87w3TtuYgx41vyZUarPvZ7t8+SB0yz6cXn8d8LGmLT6kakZFYfIlGx9ORTl/x22J0/b0+i69Jk
          6qXf+hXQdqLayHtDcvaZxagzF3S7eascequ8EP7Nm8BQOKJ55KygmzN5xkzuNBrdIH6Nm8zUMcQ7
          BizhUGyZ4XiLi7eDeZAZFWRG6NkZjOhPNMYo9dQBZjSAGWXsd8HsLqqz26tNTlUaSvaBTJxhidXK
          fjURGARWaaIOmR7GseUAL6SAMzqgWpnU1Le/ur/BZoKuooaohsXJAxVM7mvJ0p5YPbDHABC8BanV
          fZZUKLq6V5acSWzQ8iSPgQbc0OWhwoG1cmWPXndlAkSZ2u5cRAl5dtCNg4Vy2293zoULQSoJ4EG2
          LJ9u+e3AW1TZAD91S2O/rrydlZC5Vr3ZHujGiwDKv6gcI6wPZ+MorAcS7Iz8oEMuhv2glYc9nX3K
          VRdlGazzpr1Z9i/Kf1S5ZgK/Dt+7JVax8azwcRW7imn3bm/75nKyvJk83khWbnsvDJc/S1Yuedu3
          7nrDDza3P9p8YfjRTW/7k++SlQ1v+B9/8JLHm+x1+Nkqh3l4dfjguje8ujz8ZmP4ZwZy4+7w2v2y
          WsBwfQVRfnB9+OmN4Z/Wdg+vbAwfXfKSe98k11a84a3rw7XN5IsbSqFb6yz5i7Xhv615ydfrW+uX
          k7tPhl/f9bYeXkoe3WVlsLcfky/X1WJwHgsiQDRcvr21uc7+85LVZY759vDKbWjgcO0Jq4IoBlBu
          3/pz8jhfZ0nThYAN49Pzg24457dggmDyDQ09jLwAYhDy+vBP33nbd24mVza2P70LhHuBF+Rtf3F/
          +NndF7Bdt5aH164OV56Ij15ydxlr9uhS8uHHHsuYXDNouP3R4+17V72tzavJ+38UJQFRh+s3GR1v
          JA83ADUsghjiZJkhff+P2DE/YK8kK0+G67e97fe/2/rhibf1l7Xho+XhjdvJA6jOR6yiufIWmNKM
          KtGROZDgnSgMuqZzBTjM+JhxnJGkcKCZiPRMv6qEzSbvvFndMbfD01usszkrVXNEj41zaTCeThbj
          iMsYW1KPnxairsfms8NGpfmYgybNxb+QcDsZeddvJKu3kuVV6EbgRcEJWd9t/bDqnTtyOllZZh9X
          kuXvGSNbOg3wLa8nj1n2lY3tf7nDuG73cP3u1san3vaX37JuBwZhORhzKdyfrGyyMQis8Dnjki/W
          kz+wku59MFz9hn0DBk6+ugEwKxvJF1f18lLaACCs73efPXXy2HFsBtTj0c1k9TIbftCY5Mpa8uWf
          2QjPIeG9lKqT3VKKUvQUzQm6L4W/O5RGIjtXX+eYptJbCOrHxSJgFFs1OpFXytY2897Lqgasz1RK
          3cpgJwbMinffYCjMUw7r5vjgKX021aGqSKaXxIy+yztQ45PiGIcnHJccn1z65JLHxiizTtm20QAe
          g4rY2nnNUJctMt/LDQPchDO8vKKKtZvf42zA5qbh6tXk3jKwEJdG4WzYCuOB4FIm45GNV5lMXdO5
          S+mZchQsdJaCI61WyajsmKZ9PA8ioRx2jy8sxoPSmN5gbY0BTQW0Qo4QTZyDZWZvseRg6MyFXBdv
          wQhuRkZEU+8s40E+HVEVRVQp86WbJEiGmEVrMM0smGZhpFk0DTvSrPm4AdRgP/muEFHYIaAROYer
          gZj2risj0UxMKUPvIpCPYx9BDsSykyAHY6EIPFm32WF0xtB4cqx4ToUwY0am7MsYaR1Bt4Mx0+bQ
          6KpqvmaZgm5fz42b+PKagLHgOxvkDBy9blAXg0lsX9SEOlaszPScuJRtfizP4WvYbh7rsNVtgIPt
          5Ze5t2iMyZOlIGKIS2PG9OAelem8z7SxS6BJr3+MEg+nZJz9mX5473byHz+CTAStO1MY2dwNuvDq
          ZS+5/2lybU1qxT8sJ1fWdeknCuMVHn7Dcn+2jho610iHH/4rlP7g+vZlpone+i55/zKoicn6x15y
          +2py60ehADBFe/vzb7Ae967qSgC2mZu7GYVLXEiwCYiP+tS+SMCDPQvWVm+yTOC1G/cG+ryTGd9n
          gy6sNNu9FumfgORXOgjyKnxQ3cp5cOieDG3M+ohbv6hJDaYCYB3GCO3YD5msidlcAD/Cdi/QMGeV
          qTOWBVrwZeeEF5e5OR88edXfVCoV+F8jiSwO8+Ka1/v97zmmaa86BUvgkeUuQg/E5QGjfuo3qzBN
          NC4voR4A2MxSRZ0H0tvms6XjgNV6UfcTK8A9FbiHTezpfZe2aMBacGCPVEeyVpDAPQZcKVf214o0
          eI73eB1azHK+5E3VUksDiR4zHEq5hepzeBRughxmVSUQ0NtMfe+5/C9DleJZOTdTdZDMzsRVyqol
          ojcAju/wzOyXusM+hSPMx2kaseczTUudVg6YJUAgjTIWGD4GoK4wLEYUNhIQfF6ZqdZIFn4RqV5Y
          oHIeLAS/qJsFSXju1MIM0mtv5mCCP4iWgnNQAcg97s2yoRj1AgKWiyDU0QBU15r5Nh+aT3L9wzuz
          CG2VLhklx1JZYtUoqoQZQD6pFFRKzAtCU+ew1ijyL6LRDwUUbyzg4oKNHPE8B8gUIRoG3osvWivL
          oQ95e8oVKa9+Z+KVuDNGZAK7ahMm8GSDBEugBYq1mw0sVggdEibfvWwluGtkDt5ygJ/cT0xNWD+a
          Epkt1llICgZlwHTgrlNWn4quPVjqIoWcm3w93saKq3wOs6/SIHhqpLgsJOaAaShBTcqMhs/YoqAI
          czc+D4yEcHZEKg85I1EdQcrFYrUQ0EWqke6NIuuhMQNqbIooJaffMrHB0hx5C/5gNsC9EWBCEF2i
          2Q+LCmuOS/g42fKFxpZaI/MNJJoq5gxu1TjZKMXexLRWrNhY1gxeo2yX8IzUUXO5xAqcI5z2apOo
          pZKIYZBMe6k5SniAVB+NYz1pkMqyKIj/FktJ3IxVxr0zcr+RutxDEsdR2GwG0bnOYrpvntG0eqBC
          +raANoeUPFa0S1yhX+ITmPTRGfT+J4QxPr+saGQa4iD2+RIlrSufSQ0c2TqiXBUq/Dirlm4v4/gO
          eRO1KVy38N/TSAGidXLfBeNctrh+pdNm1F2AFbqpGPH5dfqwV6Pm7ZQ2NZPSbOGb/PXr5OFt79XT
          Z9HyfeW/2DraSx7+p2JUfHRpe3ldMcMnP95Mbt1DD9KV22x5Prxyl6257yerqcn8wXXwniRfG6tt
          8HMtXx2usfU196AJ23tqjEdjOqyiv17f+n6DlYFemtW7yZ1N3WcmKdRpB2jrOhN053qBnUBMkFVp
          Ag2AeGk3763ZlSBkSwV2ygWan0pYEZOcO/tFwFkp6UrNDS/mCIa/Wp5iDFgEGJSx/Q3doqvz2osv
          es/nqWsdhnhS7gj375S0lS5w2eqnW//zJFn+XhikhTfOSx5cAncKOG5u/bi1Dn/uDa893nr4Lfh1
          kvcv55BwHquH3UU/nps/weaGXhR427c3k0d3BUY0Dd37FFiL40YX0X9vojcTMRIsefoXZ3959I1z
          e/55H2TfVastdL2tH1bB+iQreAmYcOv79bLWblmZU4FfR3GhaoZym1/LH2AaH/ITeqZdqeRViJZt
          dCI4ms9IpjYwehlSOWVfhmDuqNNr10uyzi9lE125Qlg+NQ4Ku8d6i61wjs1S6c4l4IZx3pJxb3JK
          ojtleAzEBALiPNJtH5Lr5G91jgc3hLTcp2d0iSFAOYzsrqKduInCrvADg7G9FBN2ZWx++jVnDGXK
          SbAwC7svTYIpOg4TYrmdpuZmNop+ds0hVdiend5gUQuUvbP/v2dx4YTDKYrJhA8/9ppcBKHRmVuD
          f9hgwkWdKx9cTlaXwSSNUgnM1FchafWyVtEuUOjcfBR0gV6kMpqdcKg12FBik8OEqmET2sa0iZbQ
          RTPNxNxF5Bh4qn9X+A3kF9XWM59Z3/juQHVRN48mN8bw6idiLskSlyBVtQzPl8U+V3M9OV/ONrtS
          qbktr4BWIaLqFdXdtDmeHjneDO+9qV5nGykicOpbRp4xvkhfPV/sPFMHfbrXG5ZjJyJuVnS5GY71
          KSeDFeXpsP3uCIwAQmPNZ4B2pbgj1iwgKLVsFXNzX7XSR+V0F/gE8KHNXB+ZK2OXxYwVcshLN/iN
          hOQEdNndkRB1LTCBCiD7KCpkFSKaxKODjGyTS0E12sS70NWutJNdbRPMQjbN0VBp1OCked7uWPg5
          7LqqIKImHwPp0xp++w7DUtZ8nc0L1MhiPuby2Jobk9Ee5TQm8poD3BRpUMQpwVFIv4DBkmi83YLJ
          p6W5Fhw9sNMTCp7I9jsUIWPukKKyP1hFY+enioPXqsVYxT0lZlDE1KgCWC14Wk6Y6y3s6jK5wfMM
          Bo9FfPOS2RJ4zx5D38na0YejiYKB05ObmHXcg3N1tITi2ssIzhGA9s6EJ9tcvssTdoMCGSQ7iRxk
          BqLqhUQnSl4hOW0SP+s0qZVNe3v3ZIs+kmX6wtkGBaTDk+LKYryrROExV5Lw0P51rdViA0YbbEej
          bcM7YVIrg+JeClkg3xBgMR3rA3SaMTNFW64MFt9nSOiFHIWO3Nw0mCuAPFglAwEcxx3j7bkBavhs
          yf70KvGzNGIX0x0t+p9t0wYHly6iQ94ktxj2rTs3sn0/DiGS11QLz0BPP/vYZh5t1tFnHKcRCx6b
          IStX2woIXMVKNqaapfRj3lYzVGaEqu5XjVCWfpDWZX5eon6WDTMer+4wdzb+1D1T0lrj0JwNkw+T
          vZVTrhzpSgacuBNeDzgOvMMV0ipM5NIKnJBHLdFe7JTiWGGTVrQARgJHgf/uU8xEeiHWHixoGIRH
          3RpEM3qkqo3PbnM5teyiIfMWRHiMHeimJZGwI5KSWdl+qp+QypWQP9JlCl/LuRbt3JYheTGgEToG
          jaarQkCxT++RzqwcERDP0U4cdxasqJgSZx0I4ljhhFctZCTfl/axU/XGWp2NA2fzqrnmTVoa198Z
          mpqYa3Q0jAgwxTnwHMjjqRKIMtNS/ojdSLMT0gN2h7AeP+ihP010GvxiSjcSS5cxwokMZ/6CCJ1Y
          TP84VzK2w2LII34k0714r9B9rDTbOZfKs5ujtw3BU8q0+QmZFSQD+1ko/2TFpc8752Acl+IQqnsI
          iCO3Vvb/OUkjFZEcbYoh+Am0SSNSBU3S/ijjZ53odOp4kttMbvqLmuUYnpTRYWkD7HiQvTFGx46A
          d8bmfYrNJVo+LVjb38XTdCClfxmO6g54yFOI+uM4lag/zlOK+jNi3QqP6dORj80GiwR6HkP/0MoI
          AGG/2k198hHdzwSXDLnXH4cwstTubngsu/wYGhGGhM4G6aCPYHQTGkRhNguSlN+MSmWB7qA9Dgun
          QEPaZuDBs+WsmGlvagTVeHNlpS3oJEoBP8EzVmHNyiciVyHw4HJR9kwhkUCcoXG0ohggzkpOSEuf
          wmPhGFEBUvaoj0MGqY+VN3gV3F8IVVvhI9v6Ia1ZsW4leEYHyfW2OI4MnSTUggJGDF0zYer3KL0E
          lQtWbYhbMVnTIzGIZL8PyXv3GpEa0uwQ1cKItJDmhtS95iasAqeh0AKHgdvYgq7msjXMKrYGbI/F
          gJTBTWPDrKsojjSN03eIN9OKNQVEtDMj0KZ7VlmrYO+SFRzjI6xDNAPY3/P5H+DE99bmhvfmSQ+9
          7Lg3x1XAtFfba10E59pXVba164CFDIeM3fjWWucRTQZFuowVvnUEVsgVqGQJ24u92FxfgU0EUsrd
          8LcQSo/vxRc1wRSHYt8Ku9T4wWy584HCYjI377ebgTob1DsaLQWIxZbCSBNEL9P6VIgCjv05hPUS
          DWIfdu2iOgyHlQ/yBoAxVjzpQJPo34GoJmz1Xj3IXrUi3qGLSIuZVYt5hyoG+wJslEtB1PIXL4w4
          DpB5Hfjp4PS8oHvNkC57fH4YWRxKtlUoE14BXyUUQ15oznQ5R02srqU59fjpsC1Winyy4V4omxvK
          TVbW0TGM3jd4j5/x47AzgsIpc+zOOsXBS/OdKPwtHL1snfAXHQod8tB5cMXzYKYOnSuHEk9wYVjU
          CY/jcJ7M4WJXFOXvuChfFjU7uqjiWK0akZWqoKIfwfrYDsepkEdzx+joKUYKRzguHYezLTzAMoIV
          RC0Oi0Isk658Sim4ehuMw+6rF3UUlD3Fo1GkvKM/obwj+fIslMv2qCerVzE8zy3Yxjv8ZJlpAOvJ
          /UvieHdyazn59ydy868InrR9DQMvEdGL9CKW7wKS4effJp9vJKubcIwbN/qJfe2f3IFwQ3x3u9ii
          zjSO4Z/W5I6/r75Nbq5525fXth5e9yBuEEu6YS9S8kPXX0in+KN+NIIhNO4ZQWtS+GBc2H01p0MA
          nvwYAoVhynpsGB5cL+Qb4xr4flnEYZ51rJpwNhXexXcccJk6YXc3wIMuB65ePO0aKX3zLs6HrcAr
          ibLzO3pRr2qFXVrF47twrYtadyyI1GRlmtizFapKea6bUKEBst11GPnVtWVPxg2HnbQYhXUXj7qe
          hi7Y6WoG7h0AKc+DWE+TvcGN5i954PurPbU6rihcltGVah8iQotoGq1lpQqQCAMjw9Tn1VVic+Fc
          HxsMURx08PQky7u+7YiobAEbvhPFdLD9bqVIMeaK/c59WtGxzgO4sa9YXab2FNnAkj9KyfLQ9SFW
          ks8D5Ua41Lucx21NGdHblXHZBbx2VXLzBi/jUDambJEL5IDr5kMyqyCgUxQwdoyKlaDESYBRqasy
          PKgLcaheKQLPggKI9CNSS9ZsvwYd7y1X6s/pR6w6PT+E10cZCekhgdp+3bNnDUrHzx2VQA9YebKb
          zfzbdz4ew0AyTF25fslLPrqf/PWmMyJdLvohHMMjQ97BebvP7oN6cvs+6iC3LydffMdD4G3mUCId
          ak5/j8vVSRFkr4se/IKan0p34R2b0oWRUVKBllm8WHqR3Ou0q0CZz8bxukM3cI1wA2cmmPwOqREW
          ToyBDwcWNBOy9HARn03PVnYrTH5RhXGdxY477TNetWB8baZf83qD9JhBCHX0l/VrLmcZA//12958
          mMY0hA973rb54tDpXJUu55rL2ywr+g83nHie2g0HvfNrgHqbCuZgOY3A6XomnJ3ttHHTtp20TpIW
          IGUhEjpIZ5LMONgoHyRFut610CP/y5j+RNAezaIhboNyOaJDjAQEhlO4ndVmL8UgllDN8G1uwbe1
          hZcmQOnFlKhq+BR7vAA7nGe3VZFLskN2rpOizuJETYWYlFpCTDUNaWWpJDxCbBJF0HsCZOV3cDka
          PDu/IM2ey35Jmj0PfVEa0kTxOCO9py1ywOZszhzNky4vPhJ6wkvLqO2Te2jt9gWYEtPNf+l9IyMF
          IJYxWk5CjUZD1TtMQfGL+qzhEVeuFYbnV7MVBscr3ApDQ5ePBLYbx8d2uHmCUE7Uh1BScpW1boso
          toTKGJgyjBXlwB1wnYPT7NxVjKOKcFEBzhnNLVYO2UmsWjSE4RIRt9sXWWFmWXLlaFBh21wgoiPU
          4gXNKbo8zqnROEfgUx9iC/lgDCJXEZTejhsTjDJcanx6PGGuF8Hc2kZnY4XcY5nN+F7aZnLiT5G2
          M5SGmxRI1053K7Pi+bvtGBDYCCcQjC3XGKHlSVHSjIdtKSaoEeOo7bmwkuJFj0NNag7/oGyIqcUV
          PPAmvf0MESHwRNMK2HFoPCM2C/BVnX0NotpZntbKYib2CdOzOdQ4BxoUgYB12W0f5g5POG6nlK4H
          GAGlD6IngZO+BqJ4ttwKF8LYDEAuSFchZQ82H712nNm9F71Kv6FEFcBVagYAWwJooNlWDqqWQeUr
          3uUGMb6aica95jjLaqs0cRXgezQ+ODJXDJ12VaAF3wkICVII34ki1Xsdp6JiCM3bB/VhULG7U9So
          gLkSrBFNuI8i/025BbBLb6N5HpPM0DXKbX3eS4flweI8THZtnxUkvb/PCtEcCaHf6EcAaiNBEK9O
          u7Gh2RmEtm5x0WEXm3/UQrPlgoFOLGd0bArFdoCMilSoknYHqE6QqJpWVJpdXu0LS+vUjnJjs3Ce
          WGbLqh8kxheJUtwyieFXXHdNIoDjxklMt987icnK7ZNpOhjR1bsrcGffxtXh1ysiKNzwwXXp2r99
          eesvaxh8B4PUiZDrm+vJ1xts/mNVG3gMLnlw2YjShQYNmCfaEM0M3xrpm3mXvKQmJYAzNmmkCBsF
          0OiCN8PTRDzu3CeoSrgyFLrEVQq6fOQqRVaaYZwo8wMpzPM++PwlJuJmJryPibs0xAaL9Doo7OBH
          d/CinXtXITIc3HwFezjw2pOsZ2VpZcNaQUfAM0Yb7oTYIwOl0pGyRt3w9GwcWcRZZcX/b8xDRVzs
          manQsjHJZlEi/JUq6X7amXrVYmyVr4WxaRUjdfx5vwsqDVtPdS4emYWNJNalAKIcZaAvaJwvbJif
          JVNHnddMryV2t+7n4E7Od6S6P+ropTMuoZ1M4rqMiR3sPa2NtnKph0ltpzjlU+B854jTq3+jdld3
          1vBq5Rk0fd5vNZ6q6UpFpkS4EsdCXYHW9onUGqMrCd7pZ9s7ufrgph6IAsJoMboutac/nOw4nWmp
          1K5ilerGweL5p6JRsepM2rYYURWhNsY/24oUOLIt3Mqa5xrO4LwVxvMzaWp+Wh55uBnbR03XDDOB
          NIeYdo1j19kc2JQJRj6jTDHysZtk0pJo00yvYTPOyMd+0w3lGZZGG4bXYrZRQZsqKG3AUcG5IUeB
          p0w5uQYXMpnIR3Qv5XeDZ96SNtJVKtkGwkuTEYAUhjUceBYtfXjt2+TqXUVZ3z18/FVyfxlWXHfg
          esw1CKf8vx9+mr/FVV5Fu4x3ZrKCQb/f+n4z+eGGij159GfYJXXrbnZP64/JB5d41O+N5J5xQaHQ
          9OdFM6v7KQU/NzCBGKRan267dm8w+IfdVB7Mkl//XrZTURtcKVcPkM65JpsTI0ifIuPfQzIrCPJP
          kozDg9uQqHm+fXucvKTZOk12Mbu9aX6iVWqmEbiUhWg8ewfxY0b68KnIielcmuZn70Z+EAS4qRHH
          qNyRuFsL1Y83JivXUfNb+Kg4/XBZeDv2T4VtaktVxIf2HrIbHGlN6D6VILOgiE3VtAGgFL5jhs9C
          zw8/eAwST9xKoLZdHDhBEtxZhpDP2yvrjHDpzYTXc+i+gJsRvOThd8P17xnU7u0vr/M3YfECbKv3
          xUZPfon31uPrsIN0+xMmH781qXuRicfgjei036KoKzbUWEYQcBmk0gMI8k4gDAyUyn7qyOfAp/iU
          j1rL0MK0fbQsh7T9ZGXS7fQ4rNGHS+PgUgFqPFkz5YlKLSYVof6Fxji6W57ZCBeVwebWKmR7BetP
          WVm/esBCwglO/pqF+iK5WivU7hNGpPhn1e7qAYvUhrQ9FpqgxLa2G2k2aZ0rOEn3Fmu3qRs8g4aL
          jrE0ABq3zy4H6XYjTWpV6wzIJ0jrSOE0mbI6memNJ7gf2Gw3YWmaJwhmTnjSVq9Y6NM3w0xe2FXa
          SBE1RiJyO0lpe30hp6jN0UnQGne3mI5MSPIL6Q1w2jcfnJw4wTPrdJcVJq6vhQx3luTyGhQgv5+3
          8juLogzLz7KjMkFBhJrMlSoCehIRTHk4SvN7HC4E5xj6yG/PBUTYf7QHpKWdjf2FRdhOxv592evm
          PpNH79IpFPOkgSLBG1Kx3B8Ej5atbgSI1KpNh6MlPEScuuabqZdRPhoz6OFOqG/QVqNfupkvT+4s
          sKLjhjZ5oX0WrdZVUHpHnUE03rUT055K+ENppOVqrZIG5kzzanr8seNH3zzhnTn+Cuin1UpjsQtX
          luTdrw/uwqKeX2PiJV/dEJeV4K1JKxughw7XNpkSDEebtm9tbD1cz51hEhoyz89v4MZbvb5a9mp7
          Kwtdob4i4mWm3367tbmRWyZol7M7CBL7SA72xyAGK4okBtFH4j5oNZiguKObmLEtsXjxjlUesu6C
          K/juDiz4BQ6IpIeyRMnWDIQ5nQrkqwTxdZGK30NOjC7NriGoaIqtAhEcRUkYv9Gopz2uoDW8ooE6
          ssQ4GYWbik9oLitsbAILqNaIAM254MyRKK5Fh2T+Cb2YXqwjJCPB7Erk+RHUUCJPv2RtGCcKk5hw
          z3q1QVeOybY4nJPnzE0yinAqFKcxzZT87Pdt+rd9OBq44EmtCyzLuLc0ZtL5vef+D1BLAwQUAAAA
          CAAYBhRdPV9avXcUAABdagAAQAAAAFBKU0tCT1QxNC9hcHAvc3JjL21haW4vamF2YS9jb20vbWFj
          cm8vcGpza2JvdC9EZWJ1Z1JlY29yZGVyLmphdmHtPP1v20aWv+evmPqHQk5i2lKTNo2bFI4tx7r6
          6yQ5aVAUAi1RFmuJ5JGULe5tgNtdL9Dd9nA5ILnNLZIgxXYvu8AC19vNYlug98v9OZHyP9x7M6Q4
          JGeGVGK3vUMHiGNz3rz35s37mk9Hbx/qBwZp2wNtoLddW3M+8Q73bX/53Dlz4NiuT3Sr49pmR2vb
          lm9YvrbK/q8bnt0/MtzlHLhben9oeGqokZ+pP3B1p2e2PQDo21kiA6Nj6lptALxL6rbw56rdMdq5
          ADWra+cCbZpelksOaN12B7oSYms4EojLMnxtzzUz321PuzE0+x1RRdU6Ml3bGoAAM9WOax+ZHcNl
          NBu+7RrxWH6iH+maaWvrZj+WG/9xzfDarun4nMij6tpOddQ2HN+0rWSdBZU3At+4Mex2jVQ7HFut
          AV8Ate4bKSFRkKFv9jWsFHzetNt6mlNaAerTHrouatCK6+rBjb7dPjStg78fGsMc+KY5MPYsEzXc
          Ge73zTZp93XPI2vG/vCgbrRtF6RH/vEcgeK45hFwRjxf9wGwa1p6n5iWT3b2mq3b5Bp558rScj7k
          BkC+9TZAUtDFRTK+f3/855MXf/uajH/5zct/v//iq38ik8dfTz57TNZ3G+Pff0smT76YPDgZ/+Gb
          yTOoevDr8b+cjL94TMpLXccbP/ucTH7x8OX9z8fPfqamDtiAdjmPyRu1Zn2lWUXQ1pWlpdbSkqpF
          37YOSGNla3ez2tqm+LFB9G+TLCLZsLMRAtYytHbSjqw+C5IdzvfWXX1gXCf/gH+Qa7RNVCzjWNTi
          eqkyn2LgyO5DF/oG2bftvqFbxB1aFjQA9rt63zOWxdC0r6AffkNHJd72AH5pM4W72XMNvUOObfcQ
          DSBRF3sQ6DX1Rpla6hjIgLkHvjZilVY1fN31jY6YXxxENHu76YJHB5iFchagja40MsFELe2lhwS2
          vVQV+CZCnRh1UnwN55B2dbdt9JMOhDjdTgpXQouY1dGxDa0Ny1QnP/qY6O7B/nKqhnLq+N5exCcW
          iqQUN7rIgc1zyLH4PdPTEAiElCQwraXtoDokE9XdPcd+si4x15FwGqWUevOkKeLwe0qHsYQ12oHh
          rzgOYNbRz4b4SvPLAtKRcphenWlyiafnGv7QnSq5qL0XWO0eRBHzJ6BURzCQTAFK8ymBuPaxR6au
          H0hM680uKYUE5kOC3KA4ruHorrEz9J3htAtcBbWJ0jzXIrZI3x0acYNQMeF7I/B8Y6BZumWjG+ex
          ymwUCzNM+IrughlrKTMEOEJXrwIPm7btXMxUz+3+XeODGzvNhWi056Yg8xlSWijKonK3ncTgoWDf
          kEs247liLXODlLojqrD7b0D/h/1+2iA4rj+xTatUuby0NJ+0iruxDRDQzHaPlGqgma47dMAjxbph
          HliQbnSAwt2YJ7Bb0+tNRzv6TKXh9ZLqkZQUFY6NSUVytGjaR0z8mRynei/we4M1wzfa4IA0apyY
          3JEO/kZBZWImP/1pRiqUArnGxCYCoGgjgLRco2GLhRjrKnonyz6W6fQUEFKFyZf/Ovnt/athwCeT
          33374uuvyOTpyeTx8/Efn5OX90/GTz+dPDkh47/8dfLzP0HmcG/y5+eYQ7x88DDMHiaPP0/0OmEs
          b6C1kDffzHSPcbiQNK334sg/S4+T1kkxc/1krrtLY0HWOQ70QyN08XTMmdx5OcXuXtB8S/d7MLkZ
          ZU0+KkubWXuPSimSQuiF5iG9KWOak2kxn45IpBu6HMY87d7FMCotJ93oGzS50Ziyd+fTkmW1jt3v
          l1KmmWwnC1ZxEgBijsV5NlYFmYZ3DD2nqDCi3TY7fo9nnIL0eJANwzzo+Qndp/xou33dMogjGNZp
          WwrileY/WvqYax7PSMi+oLWDLVl9giqyBhGv4buQTcna1SOATFPHHBl9dePdGCTdHAbHHorSA1Qi
          rGfTjvNsUsH3tgv5FiZAJMDYtwz/vceA4NcLF9LqROXvtu8IKGFhBgOhQGoUWGAAF0hZbjhYAuAV
          4BYZL0JQXgQRb/u6JxIfpYpsn4+HKNV6KocRk8MolMNt+DUrh4geIP1QQg9LMXlQ7o7zZYJlhHI5
          DuVyWwqelk3Er6lglsrugrSadvU8r6ciGuCRTHIdJCgKC1MocoFUQL77Wt8cmGC883xymObZVfBM
          +UbbKJnz5E2yNOp2BVxFmA6KYQLuygWw7fcLo6vkoAPb/SgIrfM2wI8+zkFN17Y0mITkaxYWN1+x
          sBwUA9vvK8FScQbL3XPiv/hkr2/rPjkcCTrOpLJIShRmHvR/OdMukLTb4Nv1uHYdVz/eNC0jK0AY
          jKwcqCW79tDqlGjw0j4Zdg6MTaPrw7AdjuaLtkAXdBgUBq9jcDslCkxntlZuVrebK9nqsnBWggbN
          kO/bI8OTTQWo9xSF+xv2COabI3JVqDIcZqELmK49SFwNtNT8wMFUW6qSKa6ad3arrfXN2uoHIp+O
          hRI8XfurXL5czLTeWSoGV6kszWyDxIAp32uJbWNnc+07lFphYRSVbrn8fUjt5ncrtcLSAB0qBnjp
          8itK7Tvr86XT7jIIcfYYl53lQ4ypgybIOyGMNVHh/Dvq3qgsCwSSBkFZFgpkFCqzUqjkUaCDLZrw
          8n8qEgKv7RqG1cDNHFGijalw5mMU7/On74qEO79xVLgVWNzaHLptnFMWUjMs2G7N9Jy+HmwZkFe3
          Z2p8jDNkOjH08jX7e+W0RyfqjFX5vEW5NpJRCdE8FGeNZ6kSRWZzP6pEocanoBJxfurrzkzpaVN3
          qkcGJJjQUJmeImJ5diqasESF85a5QgEqGkzu8xcKeIeYD344mnmNoC2aS0Vl1i4Fs3XpTpEuBTN1
          ia7wusZAN61t0SIvz21naNAVW9XKelRMpjqriunJlOp18tbl6S63LBfEJfsHJ5NnPyPj//x6/OTh
          5Df3yOThp5MH/z2+94hMnvxy/PT3woYRF+QalzddWbpIypfgB6Qys2ZoyMlnX06ePiIvP783efqA
          AFOTpyeLk//41eSzoqygPLt9s32oHND3Q5br1TUl3NUQ7vZGrVktnHytmm67L5jiR0WZfrVHirpA
          XveOvCoSzyslRLGr69n9zky+bgMaNHUXnDXpKX0dxXz2zq73/83V9X4Aju57U/h35VXMaG/Wq9Xt
          V9L58DACsJ3c5p0etjE7JNx4T+yDH/fwCE4p3qIl4T6Z6VUHjh+UMhtl2Q1wLNPdOGkPuQ223AEt
          LxWYfkanzLSt2uZmrVFd3dlea8ym2eAourLN5aiAtkAmS48BCMIDFkwNTYs/ThEVgbc1LDyjlNhI
          pJDRrn8TT4Po+zAo/FZ/jJBDmxjcEG84DsVPmOwHvvHRxyQYHgnGDk/vNO07wyP5kHXpSR/5aNE1
          aXX1Rs6smJ2nUme3uGVjOcKdPXomTOsYVAFrCBRuSpZpmpFOkhka3JlJawS332laEk1nxCB+8IQo
          yswuHKWlOjJiWhr4KN1Nb0iHdXioA4ZNpNiMi0yHpWKmDMpHQWGMwIDWN6wDvyeH6bLjXgr8r+Ty
          soYpsovkUSiRWXCnbnnD4FRPpFQ92/aM1Rgmkfpyx5VJdyBqz0FoEOyA3Vt4tjDEJQ+1XLOt2laV
          rpveqq1Vd1ort1ZfzwqVBga90DzUat84EGkSz9gH1Tut1Z3NnXprfae+tdLM0hWZ9etQu1FrtvB0
          bZZSeOz2VKis11e2qhI667uNU6FRC6nUtpvV+q0VwakZ8fYTtXiZnlHlD9WsSuOEeyNoBo4i/1Er
          mlJVmPOBoNg1D4augAbIJNstdIJFv3KdgqC/Xru5V8etqpWbrer26s6aeLQZW8JTg/wB3qxd80dM
          M7lP8vYC6eMPcWTAAyZJaHUelITVVjY3W9i3VXGKk44CdHKjuo0BvYUf4ikO9gJj2BTYk5w8oOeq
          EBGmi0yxEDJOiDItoiO1+lFbcLgywT2enYCU1JcwSekjaWC0MXTwNoLRQaX2sjkrz++Mms0XDXII
          4LhGE7NV3TNKvpQUFtbJ5EnbjEDAKg/F1XczXwX5JB0CIKSUenLoNfrbqu7o+2bf9E3Dg+TTUS35
          RHLm24AI1S4kQXx2gYvymunZoy65SnnWuEiSOYfOi6ir2oyccqkQUW43sWhh2KP83Nm7damy1DAG
          Jh6f012VpoTTt+5rKML/QdmchVzEf+VMr9LT6Jk7LOjcet8Ymft9Izc1jc5nF56yhY4RQtlAdGoT
          A036PpjcSucCKFtbnU5rY2Mw8Lw5eZbIroppe9kINK91GRmkjVTBBS9nGLbEZ4+jY/+tOcGhOtbJ
          7Pc5beBcmktN3ehtPu1Wtd6o7WxrjbUPMI3CqVzl3bSSpa5YkrZso53b90m1ySx2J65jkiP2nzwZ
          SIBnkLHmdJInxBDfPdTozIGFd22t1tjdXLnT2oYkUjySOAqJilOijK69hb5dTHaO3p1axFE7C+r1
          6uZKs3ar2tpdaUrWE7grnSCmenW1uVO/09rauVWrNhTHOSnzi6GOngnvtUZrt7q9Vtu+KWa8rCQa
          3RyT6a+rmZZnuEWyzQxrxRx79UOYq2yvYH4Ks5btZmuvXlMv3zFBFUpk0a7jLsoXS6jDpHbFzecV
          bi/uMGHygWTU7BuduUyTzFpE4k+n25FL3nYMK3llTz0KUUfV0ptzj7NchpxmZEf5Oz2xZXv0inJL
          I5FJEfhH35uSYsYI6P3OnIkXvQSqHoBuRy36GI/GwrZkbVJUtK29D6v11s5ec3ev2drard5sXZIN
          Y/SrcPcRZUE6pqq/CKLuKRfXqiPfcC2dXi711swcEUVF5U6VCBSHoLDMCV3ttLFAxd8AWWiQbHm+
          ZOqH9YND+Omll1IFSkm6+CNHtIDrIo2kZ6aIQIVeVd2HZGPoG7s63u/5gSmnNLNlS7PRXN+wOuk7
          geFyVeSXMvcvESbVjH5WLPNjmWGpP6IiX+6PEX4XC+mKquIn7FS37KJSypzZIAuFVARL7g29qKiO
          Rsardzf21tdB68Klu7XWznqr0axXV7byg0n82/RXHjEdp3idSzxLEjZIxJZwexSXcES6KL5KhiWh
          icwa83SHIe3a6iEEqyDvE6bPMNEXn9MWKTrlVXIbLZZDbXt9p9UER75yc6W23YKkuloX7k2h36UW
          KljA4s6Cz0A19D1sz6C1urGyfbO6Jlx25J9hkAqLemJN73QoYJGjiOHOHe87FYf0ROtTjGZijTlT
          HT8ykV0YTAlO5pW4jciO7usKIaQ6Faqgnd2NxELPzSC+cE9SeTMN10U88ycGua6+wsb3WXp7Dalq
          ju2ZNPukuO1u1zN8yY47hWdX4nLNKcRELsQ8F7KZRAe0Y9f0DXa9eg2Iq8nG+qm2ZeyGGgJZzgvD
          URGsCU4jsK1a3WUC7/b1A4/IBzIqsdkWjhpyP59/Bhavzkt3uF0DuucV9K/KIz10J0IUdYRWAvIU
          O74CuVHisQbl3hLLomjs4WcExVYyxe9UsLxreuYg2hPDQ0FnSiIcqNOjknClEvfDcnHFAYvIXSe7
          Hw/fKbGZz4JAPKfJBa4BTHnACXW7b7/aYIR5O0UVtw4nPamvdOVBBCl8ZgmL8Hkl4cp58mWT1ORC
          sQwsUpXp6hI3TAkg8Ym31Gqvwr/mL/bSzsvXDbG84tohFuHxGoFHlS90S1FrQ6eDy/25brzYyhaW
          o3wQ8akAEZQqe+P/LHz8Ltbk6Zokp+IpXQ3P1klO0XGPaWUmFsfZT73sp248v0/bQDc8uKQ6ETLj
          Zp5yAy/RKtxFY/2uAVyJPRl2fJH0EusH018XF0m8UUrGD++Nf32fRDtok9/cm5w8wi/bt8oVMvn5
          nya//aPGt33x9VeTL54TJDV5fEI8QLXgMFzsXKSLdwTGJ7+b/NtzQEUmv3gMTcb//JBHMnl0sogP
          Aj55SCbPPx1/8fh//jb+y/Px428B/FcvvvnD5Nk9RD55+ujFf3318sGj8WdfxkwkuoxsZrusUg7a
          4rW0I6sFqCDsuR9yTM6TXiz4kLT8IRQKwBqfJ2/BZL/Cv4RCH0Ex6esfiW/DI/xIm+W8m9ITvpki
          elnkWPmqiOjEU1RQdPStiGP6ToTkYLvqfm2pTa5fJ+W3FW9S5D2WwVBcycEgej0nKm1100B1ML9U
          evttfMklZ3cLSxli43noSj5k5TIA7hdCCf1mvb8AUhR0gL7mYV64oHrEo4S6OI9PGQ6cUhDIMvJS
          AHIqz+OSonI6WhrFcMrHVIbDnJvXpdLCW1eodIstn71zqaCAsZTLlYJSptAJSVeuKN5iOVIlKlhK
          JUa7aLfeZd0qBly+cvq9QiUCz6PWIiwJTRoOZfP9V8N3dPRqr7nk3NtIBAkaSc88SJx5lOCCBP89
          Dh4w3Oz/RXLpx0DCo/gxkPwYSH4MJOQMA8npxpEfShihLo4SoEMneMVYvsco2Jicvu+AT+gAuimA
          4h6O+ImXMIBlQ9WonP0WCL6NKgI4wbf4eRW+89O3zfSLSBEpIEb6P21xEUx8WQ5eCcErxcDLcbM8
          8ArHTBZcJmDRrVapiNO3WNk93+w3t6g0EwF6waUR+hpx80M0wo5CWEWQxhVDfNZxBGaM8TiQ7WGR
          64owAP4Inxk8P/1N4eQ7lCl0YlIX7xk5e1A5Ozxt7I3iPjGFCbDHOTDC6/JYZvIo7KdYu7KvAH63
          5pv97PfM9qFleJ4wse2gblFfpe97pVEFhnvEGxyFCXiYAGGCNIyHeEZlSCIBx/ukTK5OF6enIIgm
          QJBABmK4uEQOPC0A0WJHDKZGYlOLmvZWsClqU1tTQzDLytTEVEZ5VCieUR4lBiWhhuV1bQbG4gJQ
          yHkYlwKdpdUk1REcD/AF6SAoicSlBLQ+qIgcnHA3MaPwRgWGCLMq0CbBGQ+ovk4WOoGIAOrfwjWq
          e+kqlOc1UHM1eYb/PVBhGfoLqN9Z9AFDH6TRJ38TeZ2MosgdjsCPFI1bdOigY0uiB+hHuHHEHlYV
          1AayZkHUbGOGJ9z1/Ldtw0c+WcO75/4XUEsDBBQAAAAIABgGFF2LIbgdXQ4AAM42AAA/AAAAUEpT
          S0JPVDE0L2FwcC9zcmMvbWFpbi9qYXZhL2NvbS9tYWNyby9wanNrYm90L01haW5BY3Rpdml0eS5q
          YXZhzRtrcxNH8ju/YrIfUqtCWcvmGSjnTsjCKMiWTpIhVEK51tLI3iDt7u2uBL7EVZCYFAeuirkz
          wXA257uQSkjlqhwgAer86X6Od/Ufrntf2tdIsknV3Xzwane6e3p6+jU9Y1WsXxMXKakrbaEt1jVF
          UD/Vry0oxtkjR6S2qmgGEeWGpkgNYUaUpSbVoSfSIaqqkK0bUlcylmOddUU2qGwIBfvB7K4uiRpt
          lDXapBqV61RnQqptoewwDQzBXy0GuaiJ6pJU14Wc0lLi3W3akERB1ZRPKTCtyMIMfij77yyyMjWE
          OU2KfVd04VxHajWSO+RGiyb1XBCxJz4KdBUVRU3oAY67UoNqQpUahiQvxkXUleh1YVoTExfC7pxR
          cIb5btJS2ACX4M+0pnTUWPd1qbEIEjjXMQxFZvUWJZmKWlFcVjrxAVyYKqXXzonx+XndoIStFvLB
          gqjRG4bTf0TtLLSkOqm3RF0nM6Ike3pIAIbKDZ34Hz47QqCpmtQVDUp0QzQAsSnJYotIskEq+T/M
          57Ll2lwlTybJeCYzfjaEkKwkRI2rTRArptbQQ5t6GMibD1GaTZ0a+MoAMJROfakmaiCFgRBgpVWY
          YCcyEM7TB8gpHXidJJkwzIKitKgoO3Aw3wWa1cBiALAptnQaJ6giTECv9DjNZksRXcAp5br8EUC8
          N94cCHNlCMycOozKnOrTCIPYS+6aH2mDzni/J204r8kgTbeHdyxSALGjjjlvfCrlUv59qUs1DUzT
          HUcxQCNAZF3QWaLIOY3CuLzjCogudmmjIIP+gTrgItGUq5rY9A6O4+MkALtjuiNFtHGS8Ml6miLA
          e3VZN2i7SrWuVKf8TH6qkJ0vV0of5nO1Qml2vpqvXCrk8qmzgQFAV4Eo4kYVmefcQMGlyUxpKg+U
          CpeytXyQQalJeNs1CpfylSqMIVSnLs4XZmvkg0ly7Bh5992QxLHVl2j9WpW2mmWqtSVdhynwXuAR
          VP+bUC5Va/OzpVrhfCGXRfarKfLOJAlHBqGcr8wUqjjy/HQlO1vLTwWFjU2jf+wA6f5oOo8LXzU0
          8LAfX/1stLFX0ugxJgKiW+lLIegTiaYoaHQ4RvA7byxJegAdwQTwBSVNApMScSX5IDwKtAajFxNw
          3ADAu08hl4eJVxIAy2KjAbPkj00A+yfTBJ8TxxMAz4FUFyEoyA07ovL2X0FbXODHTwHqaUA7kQou
          fN8dSQbovDNf72N0rjaM4Do+nit/WL14rlTjWBBBFi5fKNTyLMCq9CfKA2MJ3aOJCMTj8ItoadLs
          tFp88jT1zsKQSQJEf4q1bJn85xWZLhWn8Hm+WMhdxB8X3A/VYmEqjz+m8ufmpiE05bhkUrHlOJmB
          tTh2Av44K5KAY4tlfCLeOVQoIQV0HmVRE9s60VsqBghbQAG6LRXpzkC8ksCugLXjaZJBU2FJGjhJ
          I1pQyE7CQURXwM5rVLxiX7jjArF27u+/2rNWfybW6pb5ZtW6+5RYe1v7r3e5KE5JzkECca0ogWuU
          wal3yXsfYHKgGV7iYPsDJ3vlvcxLyDouM5vL5cG9nCsUC7Ur4EBrtcLsdDWVYs1PTJMFm/+iGtYk
          d5LKwEkq/UlOCKS3sWb+Y6u3dpvMFcj+r2u9B1tcFDhxdmEHiD76HX9edVGe0sTrGNBa4rLucBD1
          mfbaskQUg/RaVHYz2dnsdH6+BJ6smL0y33fVaSYJyL4FVdR0CsHHcfRnOHIUw5Pr92fFNgXBxggE
          FwTbSt9Ps5ZKYS1VP0kbYvJ9wFFcVxzaMdQTTJi3sFcj0V6NmL2etO2Vaa59ftKIHJSSm+S7LLuS
          cj8mC8oZ+gY/kQmOhxmmnQUBCTsdwSQMVI3nHKz5ts6FOexTgyxoUaO67qRRoCjjIdIdtQEJVckG
          d0ASqZRkl+3ckigvUt+WAhMSWDBRywlnil5zNzFuuuhx7ZBq8J4kF0Qt7SXcNkDaz9WbmtKe0zHL
          ixsqYnTFVofaAnQwyXsoirMxWEfAkEAafEpQO3E524RSuOFvLfOpOIGQSB1gluGFxBERQRWdS00D
          mwaHUcONSFAKMMtRySjqaFTYXsCeSlLsdz22AbmhTXug5/ah+h78GISpJ+vm149Ib3XXerNJerfX
          IE717r4m1r2nvW/+zLHwR3Dq2Y6hZOuQpevSgtQC5+Am/UR3n5OJPpaFhjbHBydvKxYEDp8cTB4k
          lKR/kQ2pLwCmk+esL2/1vtw6QyC4ktL585/I4OMHQMdj/f7uTWI9+Nl6uE6sh7v7z3fN9U3re/x2
          19pe4+LRITIzbOH4xhz+4LlB0ujRTxo1OpoctZyw9GXj46tEVXRX7/B94moYJVAtwBUsKnV7IwHO
          qq5RKvOAHZ26s3++wdAPQPg4c5WxGpHRLksNYwkc4BiZaCYOsjxgkPERB7lApcUlI3mUsTHPwKzt
          19a9bWJ++0NvYxWVo29qi6CYHY2a3+0R69UP1leQRW3u/7xrfrFJzFt71jcvzb8+RdUxf/w39jxf
          iw4RsNrvb1k7q6h02blaCca+be58Z22vEuvRKnT0ntwh5rM71q+b5r2nQohMTlSRCc/YVLGjUzTF
          tr1c5xWt5tlQzAjjVRpD69CwGgwo0IRAYqWZWO8VZm+kHBPpCxdiwms5omfwvcKpTAYSGHPtJmTz
          xHp6H5bekff2nnVvy9p5AMvFdhmc+eOz3v0tYv1zDR8ssBnRWBLsDS9/I8UilR4Bezls79HlQx39
          4ifr8TPQ1LBims9Xe3f3QJvAqxHrq/WIIj0Elbz3FLxZlJz5YtX8GkBRFOuojEAWROcGGdRz88VL
          84vXMSUMFMIEMEFjisIGANIPMK5YeMHGDjEMux6ElBhgsNlBZlB4wXbgEIPNV6iAKmHEcSIGWP/d
          /Tc347ECW4LHxpbktbGtJEQXwY7oosrm8QZ7G7TM7oLsrtMycMWi6zlYGthYK53UnPoYadteJWHd
          khquZYIvAmfEWtik5gwJDoULkDlDMlzyokTbCqEtnR5ivJERvBbmb1AOw2pxYR2cBkemSpdnDzV8
          wI314wPLGw7kgekpDzr8lUMNT+bKv4kAIMj976YPUZThd6Itwd8ktUN5zWjzvSjWYVznc5Rwg3P2
          pOaa2aFwOcj+91/8QnqP/27d2XR4CR9zjURuBPGuMCGG5vUraUxdgicEzHKzt9ljVaACSfCw0nog
          XfZ3nsxt5+Yt6+G/PpEj0sxwgwkOrMfHwZ2q1mk20NCyVgSefThx/ESavJ9Jk9OhUngEfYTddFiX
          jh5l77KGpLAHE/wQNU7aj0dsGk/Efvt9eS1bmc7XSM4+tQBOrXs7w/boB7bPgfXaUQqc9noU1YS4
          HT16CyGyp2/747YkD/ePMHCF6kpHw1PSFKa2U5KuQjY9QyFrquO367g5Lks3IBfBWtzJDDuj89qp
          kxm282Gjj0/E0YLG4MopUvcdn7ALv6eZLqqv82mfRtxF9RVxFDc1gi5GkvZkteNiuyjYO5l3Vs3v
          XprPXpKMcMp6CVuovzwNF+D6uf5wzoKeplibrmSvDMdxHN+xwYAHPJgMEwiWKWOFSrugNbBIaUP0
          w8RxgfQebaDE3PoJ7imf3OeSMEY9Z2Lu/yQ9p8iyfW2CTzxvGtnL2hrglw7NH/asnZvBA8FkH4wb
          495Xv+y/2Os92LRWX1uPN4TEQmH00/97nTDE33lFq9g5WjKjsfskQt2+huKUC90qlTsLhssJ3KKK
          BiufQebhL7I65IBUNxR1iBIraiDVsSsmuLe3vr/JJYC9VS0dGBlW0AgScmoZfki27b1f5svL4kIL
          tN++ZRXBRG69azsBTcKpp6PVQ/sqXGo0eSsqS9z+zQZJbipDvDeCDHDZngkmG561vUlC6QGWwcbB
          5bzEqpW1+ZO5vQefzLsbWIbtPXoAzqhvoowAsP/qtVseI/vP16wnoAHfr1pPbpPe31ZD5+YM/HIV
          puwxDOA7d4AfUpodYx5HcJV8DnEe2B7Gev6SmBsbEH1sTm6/AUc6GN12WLNIIeCpsIDs1aOwsPnl
          LRb2WG7so7EKoj/esJ7/awz03vx2bcwpaY9hQfvXm658P5EZRFw2e2tr1vbeGTKjdCWqj7m3cQbi
          WA/XYX0Acx25XN1J+xX33Qewymlv0a3NOwiws47S3N99hI/e/S2IK+b6M/PeHaxJJkbhoIYNDL1B
          QCfeHk/ofYuDcynx4FyKHZyPDzk5R1bSiBc6M/dvvhLd/ukdm/vfY97O7sGxz0sOBN6X5fEMIA7l
          jY2MBIcF7Jxzt9pxCza0i74SvjvJFowjkoDrdGLTQbNt//pxCE6YydZyF+bL2QqsVDzwMJAuV7Ll
          +VwJ1na2FtWqkefVd4+BubHBW2rC5b4hc/Z3FgffOEyAjr1/PJMQjA8hE2yMG1uhS4HOwrbUREna
          R++hawD2BYSg9OI3XXjO8R14NgEPZ4cIsfiDSZIhvyPcUY7ANy4FX7tYIiJtnQsvZOQKrnMNwLse
          0QApigakj5hD2pVUPlBVJTTEnb+N7p+qRfNRnJFYd8vQtIsLlXXTJv0aJrAJO3MPfpIEhvZSQCzR
          JiW9sQJwtPbgA3lndw43FfH6R0nXM0IHeT7olSioWyMfyvZc+e2Ydg4NR2DZOUFkM4xt4H31g85s
          pnQpf6i5jTpALjubyxcPLb7RJttPAY9Erde5Z55gGGAMgwwrerfd21m42wq0DPdGdU5pUOe+klMW
          dt6dzJWAexCTrr1HyIVIBcnY+JGL5gFgTLKD/8/x+ecBbKezOleszZcuYhcS6x8xensqn7bLsn/V
          hYyWgQfCr3eu3zHyNwxN5Lk+M1xwXiPgTAGvXPL8mRftJ06mnG0gbP+oUyn1NhPuMIGBbfW1oeMw
          PtBvsiUabTvkpjI+Vlvp0hq42ZqCdd9gprNyZOXIfwFQSwECFAMUAAAACAAYBhRdnweX7V4AAABt
          AAAAGwAAAAAAAAAAAAAApIEAAAAAUEpTS0JPVDE0L2dyYWRsZS5wcm9wZXJ0aWVzUEsBAhQDFAAA
          AAgAGAYUXbKiX19GAAAASQAAABYAAAAAAAAAAAAAAKSBlwAAAFBKU0tCT1QxNC9idWlsZC5ncmFk
          bGVQSwECFAMUAAAACAAYBhRdsCtUv64AAABFAQAAGQAAAAAAAAAAAAAApIERAQAAUEpTS0JPVDE0
          L3NldHRpbmdzLmdyYWRsZVBLAQIUAxQAAAAIABgGFF3E1/j83wUAALAKAAATAAAAAAAAAAAAAACk
          gfYBAABQSlNLQk9UMTQvUkVBRE1FLm1kUEsBAhQDFAAAAAgAGAYUXR9gM/72CQAASgoAABkAAAAA
          AAAAAAAAAKSBBggAAFBKU0tCT1QxNC9hcHAvcGpza2JvdC5qa3NQSwECFAMUAAAACAAYBhRd+dCn
          AkQBAAAtAwAAGgAAAAAAAAAAAAAApIEzEgAAUEpTS0JPVDE0L2FwcC9idWlsZC5ncmFkbGVQSwEC
          FAMUAAAACAAYBhRdacsLER8CAABxBgAAKgAAAAAAAAAAAAAApIGvEwAAUEpTS0JPVDE0L2FwcC9z
          cmMvbWFpbi9BbmRyb2lkTWFuaWZlc3QueG1sUEsBAhQDFAAAAAgAGAYUXaYcQsTsAAAApQEAAD8A
          AAAAAAAAAAAAAKSBFhYAAFBKU0tCT1QxNC9hcHAvc3JjL21haW4vcmVzL3htbC9hY2Nlc3NpYmls
          aXR5X3NlcnZpY2VfY29uZmlnLnhtbFBLAQIUAxQAAAAIABgGFF2peVG/rQAAACwBAAAsAAAAAAAA
          AAAAAACkgV8XAABQSlNLQk9UMTQvYXBwL3NyYy9tYWluL3Jlcy92YWx1ZXMvdGhlbWVzLnhtbFBL
          AQIUAxQAAAAIABgGFF1qOCeGbQAAAJwAAAAtAAAAAAAAAAAAAACkgVYYAABQSlNLQk9UMTQvYXBw
          L3NyYy9tYWluL3Jlcy92YWx1ZXMvc3RyaW5ncy54bWxQSwECFAMUAAAACAAYBhRdAFDD6y8OAADR
          OAAAQQAAAAAAAAAAAAAApIEOGQAAUEpTS0JPVDE0L2FwcC9zcmMvbWFpbi9qYXZhL2NvbS9tYWNy
          by9wanNrYm90L0NhcHR1cmVTZXJ2aWNlLmphdmFQSwECFAMUAAAACAAYBhRd3QZBpawNAAApRAAA
          SwAAAAAAAAAAAAAApIGcJwAAUEpTS0JPVDE0L2FwcC9zcmMvbWFpbi9qYXZhL2NvbS9tYWNyby9w
          anNrYm90L0F1dG9BY2Nlc3NpYmlsaXR5U2VydmljZS5qYXZhUEsBAhQDFAAAAAgAGAYUXT0nhw7c
          IwAAkaoAAEEAAAAAAAAAAAAAAKSBsTUAAFBKU0tCT1QxNC9hcHAvc3JjL21haW4vamF2YS9jb20v
          bWFjcm8vcGpza2JvdC9SaHl0aG1EZXRlY3Rvci5qYXZhUEsBAhQDFAAAAAgAGAYUXT1fWr13FAAA
          XWoAAEAAAAAAAAAAAAAAAKSB7FkAAFBKU0tCT1QxNC9hcHAvc3JjL21haW4vamF2YS9jb20vbWFj
          cm8vcGpza2JvdC9EZWJ1Z1JlY29yZGVyLmphdmFQSwECFAMUAAAACAAYBhRdiyG4HV0OAADONgAA
          PwAAAAAAAAAAAAAApIHBbgAAUEpTS0JPVDE0L2FwcC9zcmMvbWFpbi9qYXZhL2NvbS9tYWNyby9w
          anNrYm90L01haW5BY3Rpdml0eS5qYXZhUEsFBgAAAAAPAA8AUAUAAHt9AAAAAA==
          EOF_B64
          tr -d ' \n\r\t' < /tmp/PJSKBOT14.b64 | base64 -d > /tmp/PJSKBOT14.zip
          mkdir -p /tmp/src
          unzip -q /tmp/PJSKBOT14.zip -d /tmp/src

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: '8.9'

      - name: Build APK
        run: gradle -p /tmp/src/PJSKBOT14 assembleDebug

      - name: Prepare APK
        run: cp /tmp/src/PJSKBOT14/app/build/outputs/apk/debug/app-debug.apk /tmp/PJSKBOT14.apk

      - name: Upload APK
        uses: actions/upload-artifact@v7
        with:
          name: PJSKBOT14
          path: /tmp/PJSKBOT14.apk
