name: Build PJSKBOT2

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/PJSKBOT2.yml'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Restore embedded project
        shell: bash
        run: |
          cat > /tmp/PJSKBOT2.b64 <<'EOF_B64'
          UEsDBBQAAAAIAEZ+E12zXdMl5wIAAMwEAAASAAAAUEpTS0JPVDIvUkVBRE1FLm1kVVTLTttQEN37
          K0ZiXVJYsivPUqhApVTqDloVqSpSKyF1nZBLFBKjONQGp9iR04aXZFSTF44UfqZLz9x/6NwbJ6G7
          +M7MmZlzzmQKNl9trc1vvIVZw6DzI2x4+MNDy4PFpfntFXiztADYEyR8wMglNydNa9owpqZAOl0q
          h0BFlwLHMJ5xPEpaj0CdIjZ8yh+TL+DlxvpiZmt9dXGJgYHcJvmxdFw8cQHDmAIP0MzKyh3wT+l4
          jKIqsGQDOQLDzhO0c4sEQ5Q9qlcZgq6znFNK2gG/NRXSMBXwKJalGOR5kxdJoizwxDwhiYAhACsC
          y6F0AkDHxGszBUwbp18gLwQn6zH8DgUCqGAxFPq83u8BtrPku+N+VyG2Yw3VsynIMRT5AyZrNEnS
          ylKPx+Md8jnAlk2eoBrP5Toyz++NKLnvKLKSyJE1WzqdEZXbqyllHLKoYCqSn24H1PWYP8DCqZqT
          MfmB84B+HcmfDeyLCa8z0hYYFKnOfR4GFFRhb3d//8Puxy9AXsBsKvA/MW/DPYvkPHJZ2k0v26xi
          uwt01mVEvByMSefcwAEpIuq7ir4kEoCnzaRvaoVG0GMRxm15Yl6rRn42baNQscoStYrAYIp96QrN
          WXSbDmjb2BLJQ8wlfeYKZp/vfTsAarlq7r+FU5gZPuRdabO8OfIGynisGPOp6dNlEy54KToM9UK6
          RjsgsJT6StGiK8+OlSJUt7BSA4XKhTz68uYWF3ekGyvBDwck7iFps206qVNHrWo23nJ9PpdRxi/f
          qOKhdTJcj74eMOnf8IbqLN5vvwNZCfH6YXxafGzDY2QLqUOj1p02XuRQqTn3v9vUjj0hayfjsBr5
          6k6VpX5N37Xfhz4a+grZ+KPgCgeVan4EdGHNjWR++2JT5fZvlMpPA8vrqwtrkx46NLl9rWM9nFyR
          AtG7g/pueOyLuYlFDGPEnWnycsohO6+/fv/86SCT/lntqFOmIEv1S7RusVzEcnPa+AdQSwMEFAAA
          AAgAynsTXZ8Hl+1eAAAAbQAAABoAAABQSlNLQk9UMi9ncmFkbGUucHJvcGVydGllc8svStdLL0pM
          yUnVyyrLTSxKL7bVjcitMDIwschV0HVJywRKpOYl56dk5qXbhoa46VpwJealFOVnpuiVFqc6QpgR
          tiVFpalwibz8vJCixLzizJLMstQg55zE4mKIAgBQSwMEFAAAAAgAynsTXbArVL+uAAAARQEAABgA
          AABQSlNLQk9UMi9zZXR0aW5ncy5ncmFkbGWlj7EKgzAYhPc8hTjp4gMUOrRiobbWEN0lmJ+QEvOH
          JBZK8d2rpUjp0KU3fscdd1aPUpmKGy5hABOiB4lmObDoVUCnwL/RIokoNSTpCgZ+A5PPOcf1B5aO
          Cw301U3RhdWcyEQEWDACTH9n4FGPQeHvARUKyDyEhH3Dw+547upLR1ldFnnbsYLWTfrvg2WkQwzU
          4RX6kBk+QLSNYlo2p33dxkSZXo8CknjDrY1T8gRQSwMEFAAAAAgAynsTXbKiX19GAAAASQAAABUA
          AABQSlNLQk9UMi9idWlsZC5ncmFkbGUryClNz8wrVqjmUgCCzBQF9eT8XL3EvJSi/MwUvcSCgpzM
          5MSSzPw8dYWy1KJiIENB3ULPXM9YXQEkWamQlphTnMpVywUAUEsDBBQAAAAIAEZ+E12UCsFo8AAA
          AOABAAAZAAAAUEpTS0JPVDIvYXBwL2J1aWxkLmdyYWRsZY2RwU7DMAyG732KqJfeIigCHqDaYRw2
          iaFdkZu4lVmaREk6qUJ9d9I1VNG44OPv359/J1aNPWnPvgsWiySrhBk4aOkMSQ7WKhIQyOiqmIsi
          6cmtYUBvQeA6NIBwhtsvf2lNqG6OKFtSeJIX9vRc3CSJHYwqNEZ31CfQUtmqvWTlH2C5OQfSC7B+
          2ZQArseQtvyKV3Q+whojkdX36iFGZ2XNH1bsvGZrR1LyY7Los2AOFYLHTEkhqJt2GlqFknWgPG79
          OWemJzja5bKc683oBDaxHY9uSVGY2Btc4bwm5Ofd+2l/PHw+vt7d+e+ROX7ZD1BLAwQUAAAACADK
          exNdacsLER8CAABxBgAAKQAAAFBKU0tCT1QyL2FwcC9zcmMvbWFpbi9BbmRyb2lkTWFuaWZlc3Qu
          eG1srVXLcpswFN37KxjtjdpdxwNOMSYtqW08hjSTFaOIi6MGJEYSafz3lW2wTf2Ipw07dM89Ovcp
          5+atLKxXkIoJ7qLP9idkAaciY3zpolrn/S/oZthzSsJZDkpbBs7VgPBMCpa56FnraoCxos9QEmU3
          5zYVJSbVC5agcHOGhr2eZT6nVqD6FciSqfWlVmMfcFKCi1qGPcCOH+MkmKbeJFgk6UM4G0cPyMLD
          f2S7jRbBt0V0PxuncbD4GfrBh5Kl02Aceul8Ed0FfhJGs/9gn0dxks6iJLwNfW/NFW/ItmykqgpG
          iTbAzcH6axlJUYjfI0Jf6spFOSkUoCNMQZ6gcNH8Lv4xipJjuzYVNbK+Kr0qACfrP7sFNxq2Oqhm
          r0yvdieHJNvQ7Clh3Gtw6CQQ3iohNZiO0rKG0xhFJQCPJAOuN3G7SAFXQk4MQlFSARp2HB3GtcH2
          c1ZokF3bTvvZQmyd7S3GnnrhvpQdElMDWAq5ukzTouyJdz/zvweLIzIHn5Hr4DbHh3lXIF8ZhUtp
          90mlawnxFvle4v/qk0NQLiQspah51nAlq8pcUELGyFyKX7DJ0b45rxXo1Vp4lIJp9ydWmAAvSt1P
          xslpGZnNkHq+H8RxOAonYfK4G/CrIv/I3iGHQTWJsE9G+m4XdK0laNLPiCZHgq4Xgs76mnUtaknX
          Y2/2PO44p413SgXP2bIj3MGNsV1O+GA7mdcDt8/HsPcHUEsDBBQAAAAIAEZ+E13lOyeOQxkAAMp+
          AABAAAAAUEpTS0JPVDIvYXBwL3NyYy9tYWluL2phdmEvY29tL21hY3JvL3Bqc2tib3QvUmh5dGht
          RGV0ZWN0b3IuamF2Ye09a48bR3Lf9SvaXwyul0uR3F1p7V0xkF9a5WSdIclnLwzDGC6H3LG4JDEc
          rsjcCcglSuJYDmAHp4sDSMJ+8OUBBIjO1iE24PtDWuo/pKv6Mf2onpldyxcEuAGkJaerq6uqq6ur
          qh+cRPu3o0HM9seHjcNoPx03Jp9Mb3fH2fa5c8nhZJxmLBr10nHSaxzGvSRqXD3k4HnhJ9FR1Bgl
          48briyx+fdbvx+m2VTbLkmHjcppGi2vJNCPK3hgfTqI0ysZUxd1oenAzpqoFsCHwucmsO0z22f4w
          mk7ZjYNFdnD4ZpzF+7wR9stzjD8SYppFGf/TT0bRkCWjjN3ae/etj6///MY7l6+xS6y1XQ789rWr
          b/yMw7YrwO7+/NqbHHS9AugVAbrBuQnBCvZuRZO3jmJeTTBmAOcYk942XdgfjqOMzQtLF4HS7ng8
          jKMRh0r2bwdghuPRgPVm8fWp5AMeRXFNkFZXVKgPi7qNu26gWTHYhCc7SKaNpMclZfKoS+a8YE68
          X/D3C+I9tsfLHJ50OdLAyyVLquzuOfF/SVftjoe9W1E6iP/vOise9d4WvGm4nKoKHaLq/8T9oJrh
          xTnFp5T2m3F3Nnh9PA/JWjLZqrMF/zdv87/tgPRALtliEhtSU9hrORopLP0JUMp3/JPCQUpu3gIB
          tSgJQcmCKpm3oU6bqgMlC6oECOBlgpezyPPqqD8uFugns94gvhb3s0I9RagbyeCgAtheAASmgB3V
          Dx2uovN4WgSq7E6HZdGkEDIfEh12wD9P3Y4HMdQs8cLjCKBeBIC8F0Ls+aUUxwEom9kAkMenBiO1
          VHPGVYjoZhsOGVSATk/bkHsKao+AQB45gNO7uhy4A422elSXIlO8WHaiKquo8W+n0WF8eT9LxqNp
          SOl/vGaRwPlg68EnQ/9MompUVwcaqrs4yS4+kzh1OeKF6VHQTIs7TY6iLKbkfTMeHNqeDBjNubLO
          29br0Tg9jIZ15SIASXU2wP+zcRYNDZFJvDWFDf9Kk7w4pT0usLr2XHY3b/+Iu88s6vVqwTkACF5d
          tZEmfVYT9vqS6ZauSM5d8Hg4jf066J2uCCFVqwE+6gqKsxr8FYQfOPBVu/z14bjr9PdhMvqAi/Lq
          KIsHcdp45/IHH//i8rX33rK7/zCaW1BXr5NQyWivEq69clyc3qwCWDq+Mz2zpmpNUUPBc3ildN6J
          soMG/1yD73UGGrti95YUkACM5jX4joBtF1DIyMS4B4ALH+Geg5CEU3LiJXYBSMbVKSEbtgrg4rNd
          LhxyLCZ8chClKIRPdtlAlw28MhS7KJQ9oEqMUSum4v15jXcBS+Nslo4YiputonBX2Cus2djsb0tl
          z+v00/Eo2zPrgax8uDtJLztwwD5ga9jHPvRBDJOoi1WAE8ij6YQHvCa4au583oetfl3jXdk2uVem
          quYqIBoAlN/OJdZcUcgNC2Xos0F9X84bvHnhM68wR/aGAPsqBqsCPQDoAYnao5yT0eFkN9pbfZt0
          MHu+/e0r8LYDjnbVhx+E4K946Cm55Vpo6GKB9bw+zuJbacTFZJtQMwYTMpq5Lxbui0kaHyXj2XTP
          LTgyQDEQhwFuRr/4UlW/7hi/aRyPtj2tyt/oSD9J457/GjTmZhalmSosF8ob4+E4vTEbGTLJYzRz
          5iaiOlXXi+rmZ4/gwh5DIBpzLRCfB+LUskK8sVWOMmyBPMvCiVgD8iqrFvqPZ1OtuadBc0dZeGcT
          KgR6dZOri6tCh8l0mowG6PhOfRWxEwQVvMzZhCvrdBpz/3jiKcnMIWo2ypKhlb6y6ktFmdUtaFJD
          ZryrZ4QWyDpQqtrKdYFgyYgm9Pjnrj/8ASSj+A7T+dadTk3OzkRt3cUdFvF44ijele59dRSWLDps
          qr/SWCw06BrF8wyYuNozsq1OOVAlypvwEFj6oBnv18XfXe6T7Kdcjd5XH3Yd8rHHpnNevKiz8Sz7
          AP/fcxD7CQiiJA+AiUIj6LVLj6JRMj34IFxE0zLgvnI0/AXEGWutvp0YtkLVSTre571gJygwcc8S
          +N/OBqBZw0jxppRbYfGuXzzu96dx9o7IHpi6LzoGkoLQbIPjeF8Ypm0bZNcE2ZX+SA4j+xPjUoNO
          F2DXAdg1Bu0UMpCSnPOsvb7R7BvVF6pwlxe2mltmISgIeLOShtzFENgswD0NuOsCmsTorMdWa6vP
          bfjUmGHNHMv6q00snjvFKrXSenXTA5C6BaWti4FSaLp1QbWc21pwYJSOgXPXd+2YoYHtRnPTpd2Y
          utAajsZ30K7dXEyz+LAxikbjW8lhrC0BPKiWjXeH0ShmE1MN8NW0tvJh86O8hXyViXVn4PZNAFS8
          MTVGBmI3szTpxQrshnrhQk6SeTy0Yd/NX1nkoi2DoLXDuvx/XAvAlaXdOOrB+2mNE1bPG6+b2I12
          c8top28KDCc8s0mPGwRt93lr0GZdiLquR2IdcXmEK/emI/Voxo3FJauH4REMAcX72V8quBK2NBIe
          vL51GPNBONpfYGXO3rSmmwtTanOo5ya/rtlaLiY33yU+F8xm8PTHKavlns4Be82cCV3tN9A2IEYH
          xMbiiSdHrNNIen7yVZTM+fDB6Ycsr0krscpaG2KgrQh4Ii8s8ClHyCpeWSHH5z64TrNJrUCieZ65
          Jz/FVcSJGZ0ulyRqpivDHJUWoV5JIdnqNjDDES4LiKPbwIRHuCxYT0S9VYQofWtgwsrKeojpFLyh
          T36hlgy91KCegsUGCySw3GDBBCQCT95tYRhXMXBcVwc3pLHiVcrfrJBuPubNPNtooXEtt01ZPl+F
          3Zu6j8+23Z7/czO2fPRZ7hjLjQ2OdUfCGtNxmtXybRGNffzII6A3x9zZi3GEvfaaSDKtNHjcHacc
          MSRwzp1mKMo8AKytNFTGikqvQNwCc/F7tW4DsmF1tlhxMit5HqIbT8EzGc2GZKoGit8YI8jb8MLM
          yNrgQH+ONuNMiAjH5QI7iTsuIFsuqVEWJXwEZisrDL4ko1nsYM6J6fE+5YQIG8jD46whMhuQIWt9
          zEMN+NffJpvDuugjsV/9SmDqcEMNLlNpuxOQedZYcNOuE3FNPrlmjSO08YDNb1XSvFAp2Ii7GgtO
          9cTNvxrAMxN4hizO3L7THC04B69uqqkm54IEnnHgZqN5sRLD+6LHe8Axr/kK22hrz5REjxV2tLZQ
          fQ6PoU1QwydVAYG8/dK75+xv9sDnZIiqQpspGpSy8/GsVdUdQwpObI7I4103Ea7hiDSBLiO2S+gy
          nb8rgDkCBMqJD8CIMQC0wrAoaawUENJ/eWjvFcsMmJp0fSgx6NFXgAoOxF2xJkX3jCURIb4q3BhC
          KLMcevQGJ7lWPzwBartjtGibHn8aDFKURncwLEOTIJgFXMKUkGNM1IBRLAfjgr38cpBYAb3DNhtN
          ZSF+6eNVuPOu5yayFRq+8ORqiS3QQzjYzR6WIIQLCYnTC+0+Wy2tITgH+PUtYjJA+mhJ5NFyYSMa
          DNoAA1xMU04PD8ApoxY0K8Ximwkem0XtC5iLzT6hU6UGqpJhAaUJmkZpLTC8vAUGQ7+taxPiWgib
          UPQSDGNCmvwGsR7u695htOjGuDQBMSBW9ILbquZK4No/iHuzIQTMNDYvVBYMEqxKq5nGh+Oj+Gq/
          lrG1Dun9RYP4HSoFAE+pX2TVkrGQQNhh7XX0jEjEoCYdpsNbmaUy80gFTr4nqoAjmv0p/HtcC23g
          0pVa7jN9cBRxliaDQZzeGk/0Nicu01aePXOwgZXN6wTRHgkn8kiYcJVH9OT9FwjjvX7N8AIcxHEW
          CbdY0yrmEg9H7rs2WpKZOidrxeFI4Ntha0Aj95XFd+4s80oEd2pVhzuV/aQHWyB87ZRzS+cSa1M6
          hvplyHqzSYr6Jd1EUMi4bfWySILVHN/5/Hm2PP7y2f/8sLz3e7Z8/Hcnx7/jf75YfvOULf/9r5f/
          8mT56B5bPvjjsyfw5/HJ/e+fffMf7OTbp8u//bXTTDKazLJrcdRDwbfMmEP6G/EwWmChkN6aVWVV
          a7BBXr5lmhCgGNm+nS93aJrXwg4N1k7Hs1Gvpgh+JTcYjSYR1jtdkkzzBSWQt8r4eetpYszBCEjd
          EEV1pfpumkU+hnXaSe9CJ/SHytmFs3WnydQ5kwtuI/ChsN/ylIerdl99yvWKLe8/XB5/sXzE9e3B
          vZP7n548+oG/+3p5/BAhjh9orURAdvLPXz/7/nOum2z59Zcn3/6BLX/7Bw6sMavFO0ogswCNnOeN
          LdXD13KKDYKpvgobdj2fvjizHrDaxs6C/99GlmsE+Cgnn/2GgdX5+39iA+49zNIYFQJ1hVudk/tf
          s+eff8HVYnnvmFuoXy+P76FmPP5SqBBozPLYNU1TkNCtA64XIC/SV9AkXujXGchozfR/iLmg42Ml
          rLieN9r+OlTBGDez+TLVpt6Y8eVBHo+L9WXT6TzAIJxrvfmKmAvywiMoNe32QUPucfD93YNGvtGB
          KrW2OwBac3UlX51AQ3ZgUGGpdOlw85ZZfOcnXy1KYfUlMPC84eWsyYjUp3BFSxa3Trcco/f5gLN8
          JRWJhqLE45tzKu0YRPluMrpdghFAaKx2BeBL4045WyBQKqiQ0/3czNulDb0DaA30MJTAS/24pSii
          543sML1EXAopBFiUiUNB9JxTPiaA6qO0UtRKsCSO2pXy1D4NT6ILi/jSnVzEm1QWkrUCRlXIKUTz
          UjjV+FPknUxDRM09HtKzJqbmBbmHnH1XzStQFEhvCXscrI3FmAAqTHYIygFug0x44JRQ0Mi8QkKF
          YD6cYRHT0v4wOpyEe74GDa/l64JVxGhtBzZ2mJhowvrULNC1VjVVKZ4ScyhiajQBgvkVpybM9QF1
          LUqIwPMCBk/AfIuWdy6xzU3P38n5mMOudanAesc+Vq0z2HRMWyjhvZRojgQMdyY8+fakVSbc4SoV
          lDrJGmQFgvRKphMtr7ScIYufd5ryyjrswqaOWyhxC5GpBvTwpLTSOKzqh6PwCOfHc9jUQy+1OezK
          tdgRZD7KU3an0c6gZuKyqmpQrA0GMnruyOxwLaaEWiAIMo/JQxstXLGz7+R3P7DnDx6y57+5d3L8
          6fIxj2GOefD7X88ffPXsuyds+fDe8wc8mvm3f+ShDS96+Oz3T3gRBr0PPls++rzI1xTUUecdXso7
          mWLL9MoFkmrs+fWu9msHbK1TpGSEilO9zjtsY5OMzA0irIiA3rl11rDgRaZZq/nPAR84tJQtwNVG
          +R22LnI38+B6dr4bosCQ2t565Vn47DNwaPZ1Zl5qrcPKthm5tgD/kHl69PTkv79jkPT85qvlo6/Y
          8m+eLh/cWz7+FLIPzz/77uTxv2I2AbMOkAA9uf/05P73MDq/PWYcbvnwh5P/fMr60XDYhXH37LtP
          +eC02lEZYFzEwEiWQ0+93jjtBhGVhyoICnTIBatha2wGagHLbNzwFdRyl0kgBGk1CycXeHL26EkD
          RZHG0e0zzIsSd7ArC5PDOU+035qnpIyFLjPT6x4Aq5h2xXaN/RG0Xqemp/zidk9SkSYNaedm4Vlx
          B5fOpPJBpdOkhrthJq7E/5Y1NnaquXuLrWbszdC+wc0363pFxuZdz9riqWhcrvL4N7veyPZvbKpt
          Q1bCD/C8Ps6y8WEQFXdeg+NKbshfY61KSw5bakWtZJkBqLqZxYXstSz21gPMzU+Hpi3nFxcNFwJM
          awV4XrXxtAhEeUrN3pxemm5DecCqPe/xbYb7/mWnwTcebKCw6L2DsPlpEqd40JQ7Mrdq3sZAPDct
          DjMUJy2adB8bbBfOn+rUQ/l2DnhqeRSzpqqCeeBfK9VfbxbFMcXzLoxLeXyjeAjIwypB9f8pRaOc
          D0s21RD8CNnoM+/xgMy7qkP4V8bjHp6B8osH0cTJmMOjFR1COlDHbf6JKzp2BHzmaj6n1FyhFXND
          kP8pHpUAK/2zpKw74PGsNfUErDf1GNa8HLgkXofHX8pSTyj3jAJ6Cc+D094OAGG/hlOc6pHdzw2X
          urdjXoe7qKh9rvAEdl9xNPLoLV0NysEpwRO9NIihbAEkWt88ovLbMoCfgsyuREPmpODBU1m8mQ5b
          L5GaYFcRHUCnUEr4NVGxBSG7mIiKGoEHQ0TVM5VMArHdvoCLaoA4KxVCBvoUnoDGSAJI22M+BTbI
          fIK6IUgofkM49YYehcIRTVm1biV0xgWxelueNYNOkm5BhSSH65lwH7zML0HngpMNJz7X2+4ZRlkc
          zaH4wgXvjKOuDudBvTOKujaWbng7gyocnMDMYwNuM+GhXrsov9A18gvITyB/lsN1kLFg4CaQ6ptA
          dgSbQawaENHulqDVN4bwALZxcTO8s//8eXby5Mmzb/6IKYDf/gPE9s++e8reu8pwcwGm3Yoa6LD2
          hWBMbfHXMrYbu4CV8qZc3cSGz8IjXByqYGdK0OIVnynS/owff+Xmy2RMqB11giZfcr65P07jonVs
          dW0N7C7BaylWxaU/6q6IU6s63Gy1xntF3Ovj5ybhERHVK6zNW2ufua8wS3gUp8OICqvg0S6zPN4n
          WaPddh1xyDOE6pYkIpKxV9z358gwHHZywVVyanw7Cu3rVhxw07tWvlILz1bxnGd4+nIP0NyPceFZ
          CVkCXO2uRsvGZpVVndxg4fropr/Mh/QQZuYlkFxJjnUqdDzESklvQ1pKdIGgrkUubIg2dvIxFTrg
          owYcVqA3psNCUYWZsOxIkXGcCEalu9gkDgcSJ2GMJnD7OoBM6US/k8CnT3pbrf6USaZWYVqASAkY
          IyHfSX3RTft46Z52YbBdlGfyG1xlXprJywv9aL5kamLDHexeSxU4C6QQ3CZFyL9aoc0Xk/U6ZQ6u
          TeTgcv/RXpIqcS/xVirYJef47yq9QLz20wr5vX62j4/X0cjFYOc1Xn7mvR3ot/a8rNIVcGcTJivm
          7aJMBQf/8CN2kOgbD+DF5kehRAhm/Foq39cuSvUpQv+cA5HPmXMg0DsfAtRH1AmnwBY4IdcbSbc7
          HuFOobBoC0VaQZSVRFggOl9k3sZ99aAo9BJtQB72N296kafBnABb3udZlAVM8EAq/7MD9+uzZHU1
          tGaIZCYfifApxItoTYLS0b4kNTnDUh5gh4MuIRKFJdsJa50ydYEMljZiympJMzXwrFWASHik2SSa
          oBOyivhTXG8Lz+mvuA3XCl9zG65DX3WLMjHSfSjvTsAOhDJ9eZaP7GkFgoJeY7qN9kW1aSGctIMp
          US+/6gsOSw0gtlFuJ4GicqjemDsoUdWEITzy0tzK8OJy3crgeAlvZWjo8lJgOibDklNmrgnnxHwI
          J8UiNpiTrhai5ApMZWiqauAptK5A08LaVU2jqmhRBc0p15aghpzmIiFMNGEIhvubqkRweRWrHQcq
          GfkBGGwAGjWmyV/BFb/imL4kIxlZjq64j8ZjruCCmgiOG0eQbCGjCMpvx6yw10aRG6/3g+3PUphb
          R3BtW61JLnDnMz7TPJMTv0Y6ylEmVBpjpPeL8ObF59DeU8jBrSEYD9dA0O2wzRa8VDPUiLFsbwRE
          UqLpOlDSLtjHrRjxvbiKu6xVqpUjona5CtYq5EloPCWZWhHVhWMQM49x1iyGXzgnUrv+UBMa6EkE
          bnHILyn0l9dhj7fRuntWFpw+OFCdQM4VTHG3MUwOE7jJmzwuZ04JzkXfKd7BIpSdvcya875xlA2j
          1BwAtlTRQN2hBdXOoWzCpyLhJKKZtM4GdV41RDRxOfddGh/s066Gzrm8O4DvChxDrYTvShXyruNU
          VA2hfx+4Owya5CBQ2emSoPHPY0FtKSUE/CcdD5KaAZDcepV0uAZ88kihfKMdKuYNQf11qjzFKWeL
          RC3qXdws1CVHf3118bt94L/qkprAXbiirYFpPf8Mg8bfOhdRR7D0xKfr889efcXfHR65U4ktoA2k
          enGLEh20jL+8AOK92KYusFhEFHOp6KpNui/BoW6SZd2CMr1whcqA3txG29cywSkfJUBapT5Hk/rC
          elySgRJot0ixSi4DAwE1mZRAyhlH6a2Tg6SritvFdtMy/T8N3+0Ab50gb13kezPIN8rsQtg4oFiq
          jXFirngBjAvJtwIMAHMXafME9WijiDIJjAZtMGmRaZm0toKOJB1cYs7f55tYFDsgBOYbQEgwAiGw
          E4Lhp4H+5O3XqewO9TWifimiYkdoUFo/6PiEnBlC1vltXp7MokrzCJydtE+9E6vg3cL7vCoLN3LO
          ohe2JBOTZxV/ZOUdi5u6UsLUj+0ow1DkR4as1tTvYFgvC26JwNjc/imOKXvN+AUJaiuKOJayA7/b
          pH41IxB1W7eecmicFOEsj3+ZiCEG/yQOGaD6PiS1bYi+TycsJ8mRJ6lcJBgVe7TjTlnrN0lmdf1D
          JBq64OCfugs8761A8/qMokfDFDI+onc6eeeUNC5vwzUPEMg7iYlJJHDmDu+7lL9qUHTIrtrmF3iK
          rk5Qj958IFsOViDSLdSBPeOwXpGoxC3MhDo5oZeUoj/mKpzakC3hmQ2PzvBZguCRCg+1PP1watzU
          mQTfxw2pCXjrw5KDmNYhzFQ2N6SPXv6IXtSXCElTQCi7ccq+RBrGCdNXgowJoXCrALdMt/o0ceqX
          ksT2QV+M8kYsStO4s0S+juYhlzA8HD1c8OS/TRjN6+yIsGp3z/0vUEsDBBQAAAAIAMp7E11sMVVf
          YQgAAOYpAABKAAAAUEpTS0JPVDIvYXBwL3NyYy9tYWluL2phdmEvY29tL21hY3JvL3Bqc2tib3Qv
          QXV0b0FjY2Vzc2liaWxpdHlTZXJ2aWNlLmphdmHVWm1z27gR/u5fAX/JUI3CKrnL3fUcu1Udp8mc
          nLixO9NvGYiCRMQUwIKgbN2d/nt3wReBIEhRubS9YiaRBC4W+4Znd0GnNLqnK0YiuQ7XNFIyTD9n
          93Opz05O+DqVShMqFkryRUijiGUZn/OE623G1IZHLJzak7fF5NmglX9jmc4Ve82ySPFUcyla61aK
          pjGPsvCG6rj1VGbhW/ieMOV7NJMy9TzZcPbQlKepwtWGCUv3z3RDw1zzJJwqRbcznumz9rNLuU6p
          oloqz8O3NIuvaep50sHNT3yjuFQg4N9zloOFT9J8nvCIRAnNMjLNtfR5grBHzcQCCHwPfzkhMFLF
          N1QzkmmqgeFGJvCZsG6eXACpQDf71i+5oAlJpFiRy7f/eP/Tp+tbck5efHt2gPhuelOQfn+I8s3s
          3WXJ9vkPPcTLRFJdUr9+d3s3fX95hWu+e7nsWcWFJtfTf366vfv44acr3ORPjqIF3Yf5ZxZpkCi6
          BxrBHsqZYHTmoS4DlawpF9X3YlX5KyjiNVwxfQ00xa9gNPLu3YiFVx/jrY7Xr5mG3aUK72hqgviC
          aJoaCnJueFQDd21yuAj2ERxG5isXqxkYO6Dk2QWh4SJn77MOaSBeX70Tmq2YGhNHmLcyWdxRBVpd
          kAXLuGILnMo8IpXnBIQZsM2tVvKe3YLjGIgXab5hxdRxnOdSJowKQiHW1xQx6ErQecIW4Byt8Jz5
          qLl4k/BVrIFoSZOsgyrN1+mNzLRh5qEzsQynV79RdA3WBarJrO9MFUfd0rw8wDj2scsXZ85sG2jD
          gok1AzvhjLu0OEKP/ultKSwOS6qgkGJ8zL7jaqfqy3ZkKYdDxzwLOZrSVrB+UrCBp64eNcUjPHz0
          zG9hfruf350U/xduKDC29EInIEJ0B7a8ioHewsJJi+VfPmyYUnzBSj9LPCgQIhtITkSKkuWlFMLM
          N/hmOSKEj2gvf7UpBjCo17d3oVy5MfgELLdt7MeXJNjzKxiO7B1EniRWEGRbEcVKCv4zKBQgMra8
          WCJSGMERUbbcOGyA8FM0TrqfxH84LSvYlqy1PvO43VgmY3rqgkNQHXFW/G746KANfFhTMrJsWdn/
          1LPHMGsOs+jOZx7F/pWDZW4AwYJJj23y+ZrrwIF8A2fTCBXMjMPg042qchqDCmNoVB6Zo2LJWKdl
          TA8rHE2cvd0CLK9DQYW842tWpwWPiCEYOSOnlZw9TqCLxTRJGutath4Q7p2CxCZv9kiylIq4ztjn
          XxKTH0mDl49HS64010EcIpzHnvja/bZYKrOcCSabzqTGBUvo9jo77nChwfaJdx8MNk0jMe+zvCO3
          VamFKVC/RnHg7ANCQkXU3PWwXK19HWxqGxOp7cO6G0MFpGNo0h6Dybi2To9FCw6tIsEYV8iHgyeh
          IHewzi0FhhZ/JuLcxXVP1VvDZmWlvKe+aMg5LCqqvNABEKzG4hakHInKhzEXRz9279pb2gh2iqUi
          efKkdOOzBrxdkOcvXn6aTCb4b/ZlEjr7F9Bz7hTTNhsXuEyQxdBi/Aw13nkp59N9R/gH8rwW0Vn6
          EGP3GZzWFuLZ1TrVWJo8eeIFrJoyZew+GBXNCnl1XgvQvQ4qRwgbYP3Kbvo6cD5DjA/2u0mA+1G/
          5b6aMrWrv5/0+taRbkCyt+MZY6pZY9Xyes5NlZ081MjIRE1zyhjRYvlLO2gMsGGbPnHiYhjIGm3a
          1u7KdcWWfLk0aOi3/TMfSvqYVaLXOP18Nq6Y/9EKeOD4w2wQDy4CMzEmL176Vrj5t/HTzqiGi8PA
          zY3Wck/r9tecJwumyLz8LNCgm9A2UnfrLtijbgFLo53RZUt3KXOBpHZYmIrHbogh4qDKcZNFM0Y3
          NAGzQEj4soS918V5ExPmitF7Jyj7yq3z8gQotpYbFsB3qKN8FV5cVXV4RE7jkIkF5KroHn/2JBq8
          FCVpaT384YvLNMTN76TZHtpr/HADoaBLuEC6GKliQ9MiGtbROzcw9sDdCxOHkRSai7x0S5COCVQ1
          VX4Ym7rMJ0IZfojE5Uq3ysaBYWVK18LoY2Mi+46ims9Q11JhDx8rHJ4+dbCUMKjg2v77nbgPMKZ5
          8znMmF/suepSdlxUtqMWoy+y7n/Lag7df9JQ330tC3Xl8o6QG9AdFnBV42NHdj0WInEc57U+CDLn
          rT5iXWn9y44DjiM8jaMjB7ZQsZ9LLfZ4ENlkGFl9JAdRm6DspWxHrJn1VCVdhxfHoESD4zcnGxy/
          Z//UyW4QNSbEfvcMjmhfxsRRZ83YmzPjIRlz1xbiWBAr2jKp9JFvpXD4UK66TEDGgHLmYs53l1j1
          QL/+Svowrh3WwzqTap8an+2bQ+wqD9b3OKqc0tt1Vo2UpteZ3Y94ZZrM/AGIItUdkOk+R40uprHI
          2/8vcmXuUYrOKlyaoujP+/e3P5Yvfc/aSzNNlbaE5x0ntFTSr8H+vmy2Ly1BmUquUa8KB3NWna9Q
          OTgR+NFCM/R4rbz3VrDCQ5uLL13ZizoR1sut/4piYMb7Okh6AEFLt/cTVe7rp+rOZ/1u70Arp8hq
          9KTQlLqetXvvb4b33QOuMvevtzqvrrXaOquqS1yJf6uw4FlKdRSX3vQ7rIoK8xmM/La2YuIjy/JE
          X9IkmdPoPugCQBzN15C+0Xw1iVkgYfiesx1/ZNWa6tsax3C0tseAN4+Hl0FuxVdEmGcHrO1+k+kb
          7VRhD99bGD+Xr+c2fEmcJP+XbvvfmN476z951tupXjQzhY30mmq4QY8w4mHDtdXsw0qrQCQRghYJ
          7kDoByyhCF8Jqdqd7jDFBirVr1BTGVuRb+1XdyfF/+ajPkbOcWn/FWLQniIM/wd1dr288K5VqTw1
          f5ayO9md/BtQSwMEFAAAAAgARn4TXWDYFvXyEwAAwGgAAD8AAABQSlNLQk9UMi9hcHAvc3JjL21h
          aW4vamF2YS9jb20vbWFjcm8vcGpza2JvdC9EZWJ1Z1JlY29yZGVyLmphdmHtPP1v20aWv+evmPqH
          Qo5j2lKTNo2bFIotx7r66yTZaVAUAi1RFmuJ5JGULe5tgLtdH7C328P1gPQut2iKFruH7gL7Q283
          h22B/nR/TqT8D/feDCkOyZkhldjZj8sAcWzOm/fevHlf8+nonRP92CAde6gN9Y5ra84n3smR7a9d
          uWIOHdv1iW51Xdvsah3b8g3L19bZ/w3DswenhruWA3eoD0aGp4Ya+5n6Y1d3+mbHA4CBnSUyNLqm
          rtWHwLukbgd/rttdo5MLULd6di7QtullueSANm13qCshdkZjgbgsw9cOXDPz3fa0uyNz0BVV1KxT
          07WtIQgwU+249qnZNVxGs+nbrhGP5Sf6qa6ZtrZpDmK58R83DK/jmo7PiTyqru/Vxh3D8U3bStZZ
          UHk38I27o17PSLXDsdWa8AVQ676REhIFGfnmQMNKwedtu6OnOaUVoD6dkeuiBlVdVw/uDuzOiWkd
          /+3IGOXAt8yhcWCZqOHO6GhgdkhnoHse2TCORscNo2O7ID3y91cIFMc1T4Ez4vm6D4A909IHxLR8
          snfQat8nt8k7N1fX8iG3APKttwGSgq6skMmjR5Pfnz/743dk8k/fP//PR8++/QcyffLd9BdPyOZ+
          c/JfP5Dpl19PPz+f/Ob76TdQ9fnPJ/96Pvn6CSmv9hxv8s2nZPrTx88ffTr55h/V1AEb0C7nMXm3
          3mpUWzUEbd9cXW2vrqpaDGzrmDSrO/vbtfYuxY8Non/bZAXJhp2NELCWobWTTmT1WZDscL636epD
          4w75O/yD3KZtomIZZ6IWd0qVxRQDp/YAujAwyJFtDwzdIu7IsqABsN/TB56xJoamfQX98Js6KvGu
          B/Cr2yncrb5r6F1yZrsnaACJutiDQK+pN8rUUsdAhsw98LURq7Sq6euub3TF/OIgotnbLRc8OsAs
          l7MAHXSlkQkmamkvPSSw66WqwDcR6sSok+JrOIe0r7sdY5B0IMTpdVO4ElrErI6ObWhtWGY6+dHH
          RHePj9ZSNZRTx/cOIj6xUCSluNE1DmyRQ47F75uehkAgpCSBWS1tB9Uhmaju4RX2k3WJuY6E0yil
          1JsnTRGH31M6jCWs0Y4Nv+o4gFlHPxviKy2uCUhHymF6DabJJZ6ea/gjd6bkovZeYHX6EEXMH4FS
          ncJAMgUoLaYE4tpnHpm5fiAxqzd7pBQSWAwJcoPiuIaju8beyHdGsy5wFdQmSotci9gifXdkxA1C
          xYTvzcDzjaFm6ZaNbpzHKrNRLMww4Su6C2aspcwQ4AjdugU8bNu2cy1TvbD/N80P7u61lqPRXpiB
          LGZIaaEoi8rddhKDh4J9Qy7ZjOeKtcwNUuqOqMLuvwH9Hw0GaYPguP7ENq1S5cbq6mLSKh7GNkBA
          Mzt9UqqDZrruyAGPFOuGeWxButEFCg9jnsBuTa8/G+3oM5WG10+qR1JSVDg2JhXJ0aJpHzHxZ3Kc
          Gv3A7w83DN/ogAPSqHFicke6+BsFlYmZ/PjHGalQCuQ2E5sIgKKNANJyjYYtFmKsq+idLPtMptMz
          QEgVpr/+t+kvH90KAz6Z/uqHZ999S6ZfnU+fPJ389il5/uh88tXPpl+ek8kf/mf6k99B5vDZ9PdP
          MYd4/vnjMHuYPvk00euEsbyB1kLefDPTPcbhctK03osj/zw9Tlonxcz1k7nuHo0FWec41E+M0MXT
          MWdy5+UUu3tB8x3d78PkZpw1+aisbmftPSqlSAqhF1qE9KaMaU6mxWI6IpFe6HIY87R718KotJZ0
          o2/Q5EZjyt5bTEuW1Tr2YFBKmWaynSxYxUkAiDkW5+VYFWQa3hn0nKLCiHbf7Pp9nnEK0udBtgzz
          uO8ndJ/yo+0PdMsgjmBYZ20piFda/Gj1Y655PCMhR4LWDrZk9QmqyBpEvKbvQjYla9eIADJNHXNs
          DNSN92OQdHMYHHskSg9QibCeTTuuskkF39se5FuYAJEAY98a/PceA4Jfl5bS6kTl73YeCChhYQYD
          oUBqFFhgAJdJWW44WALgFeBWGC9CUF4EEW9HuicSH6WKbF+NhyjVeiaHMZPDOJTDffg1K4eIHiD9
          UEIPSzF5UO7O8mWCZYxyOQvlcl8KnpZNxK+pYJbKbklaTbt6lddTEQ3wSCa5AxIUhYUZFFkiFZDv
          kTYwhyYY7yKfHKZ5dhU8U77RNkrmInmTrI57PQFXEabjYpiAu3IBbEeDwugqOejAdj8KQuu8D/Dj
          j3NQ07UtDSYh+ZqFxc1XLCzHxcCOBkqwVJzB8vCK+C8+2RvYuk9OxoKOM6mskBKFWQT9X8u0CyTt
          tvh2fa5d19XPtk3LyAoQBiMrB2rJrj2yuiUavLRPRt1jY9vo+TBsJ+PFoi3QBZ0EhcEbGNwuiALT
          mZ3qvdpuq5qtLgtnJWjQDPmRPTY82VSAek9RuL9rj2G+OSa3hCrDYRa6gNnag8TVQEvNDxxMtaUq
          meKq9WC/1t7crq9/IPLpWCjBi7W/yo0bxUzrndVicJXK6tw2SAyY8r2U2Lb2tjdeodQKC6OodMvl
          P4XU7r1aqRWWBuhQMcDrN15Qaq+sz9cvussgxPljXHaWDzGmAZog74Qw1kSF8++oe+OyLBBIGgRl
          WSiQUajMS6GSR4EOtmjCy/+pSAi8jmsYVhM3c0SJNqbCmY9RvM+fvisS7vzGUeFWYHFrc+R2cE5Z
          SM2wYLsN03MGerBjQF7dmavxGc6Q6cTQy9fsPymnfTpRZ6zK5y3KtZGMSojmoThrvEyVKDKbe60S
          hRpfgErE+amvO3Olpy3dqZ0akGBCQ2V6iojl2alowhIVzlvmCgWoaDC5z18o4B1iPvjJeO41go5o
          LhWVebsUzNelB0W6FMzVJQzC66bbGQimelFRhuHOWFEXyOvekVehZHoDs3OS29n3w1SoUdvIhb0V
          wt7fqrdqLxRzY2vq24PuXOa0BQ1augv+gPSV5kQxX7499f/arKn//9mW3pVXMZ2/16jVdl9I58P9
          bmA7uZM4O89hdkm4t5vYaj3r4ymPUrwLSMKtGNOrDR0/KGX2YrJ7rFhmGz7SHnJ7OLkDWl4tMMOJ
          DjJpO/Xt7Xqztr63u9GcT7PBUfRk+5dRAW2BZInuNAvmS1gw+zAtfsc+KoLZlGHhMZjEXhWFjDaW
          W3jgQD+CQeF3k2OEHNrE4IZ4w3EofojhKPCNjz4mwehUMHZ4QKRlPxidyoesRw+TyEeLLnuqq7dy
          Jl7syI46gcJdAcsRbh7RY0da16AKWEegcN+rTM9rpfMwhgYX/9MawW2pmZZE0xkxiB88IYoys9FD
          aalOJZiWBj5Kd9N7nmEdnhuAYRMpNuMi02GpmCmD8lFQGCMwoA0M69jvy2F67ESRAv8LubysYYrs
          InnaRmQW3MFO3jA41RMpVd+2PWM9hknsZXInYklvKGrPQWgQ7IDdQzy+FuKSh1qu2U59p0aX5g7r
          G7W9dvVw/eWsUD1pHfqah1rtG8ciTeIZ+6D2oL2+t73XaG/uNXaqrSxdkVm/DLW79VYbD3BmKYUn
          Oy+EymajulOT0Nncb14IjXpIpb7bqjUOq4KDGeIdDmrxMj2jyh+qWY3GCfdu0AocRf6jVjSlqjDn
          A0GxZx6PXAENkEm2W+gEi37lOgVBf7N+76CBuyHVe+3a7vrehni0GVvCg2n8GdGsXfOnGDO5T/KA
          PBngD3FkwDMMSWh1HpSE1arb223s27o4xUlHATq5UR34h97CD/EUB3uBMWwG7Ek2t+nRHUSE6SJT
          LISME6JMi+jUpn7aEZzfS3CP2/OQkvoSJil9JA2MNkcOHng3uqjUXjZn5fmdU7P5okEOARzXaWK2
          rntGyZeSwsI6mTzMmREIWOWJuPph5qsgn6RDAISUUk8OvUZ/W9cd/cgcmL5peJB8OqKjYzMioZz5
          NiBCtQtJEJ9f4KK8Zna8pUduUZ41LpJkjjrzIuqp9rtmXCpElNtNLFoY9ig/Dw4Or1dWm8bQxBNa
          uqvSlHD61nsJRfgLlM1lyEX8V870Kj2NnrvDgs5tDoyxeTQwclPT6Ahw4Slb6BghlA1FBwMx0KSv
          HMmtdCGAsrPT7ba3toZDz1uQZ4nsNpJ2kI1Ai1qPkUHaSBVc8FqGYUt8vDU6Wd5eEJzbYp3Mfl/Q
          hs71hdTUjV4Y0w5rjWZ9b1drbnyAaRRO5SrvppUsdYuPdGR7udzWQqpNKe2hEjf+yCn7T54MJMAz
          yFhzOskTYoivt2l05sDCu7ZRb+5vVx+0dyGJFI8kjkKi4oIoo2tvo28Xk12g13NWcNQug3qjtl1t
          1Q9r7f1qS7KewN0aBDE1auutvcaD9s7eYb3WVJwYpMyvhDp6KbzXm+392u5GffeemPGykmh0OUmm
          v65mWp7hFsk2M6wVc+y1D2GuslvF/BRmLbut9kGjrl6+Y4IqlMiiXcddlC+WUIdJ7YqbzyvcXtxh
          wuQDyag5MLoLmSaZtYjEn06vK5e87RhW8laYehSijqqlt+CeZbkMOc3IjvJ3cWLL9ugF5ZZGIpMi
          8I++NyXFjBHQK4Q5Ey96z1A9AL2uWvQxHo2FbcnapKhoOwcf1hrtvYPW/kGrvbNfu9e+LhvG6Ffh
          ESSUBemaqv4iiLqnXFyrjX3DtXR6f9HbMHNEFBWVO1UiUJyzwbIgdLWzxgIVfwNkoUGy5fmSqR/W
          D0/gp5deShUoJenhjxzRAq5rNJJemiICFXob8giSjZFv7Ot4heTPTDmlmS1bmo3m+obVTV87C5er
          Ir+UueKHMKlm9LNimR/LHEv9ERX5cn+M8FUspCuqih/iUl3kikopc+GOLBdSESy5l8Ciojp9F6/e
          3T3Y3AStC5fuNtp7m+1mq1Gr7uQHk/i32a88YjpO8TqXeJYkbJCILeH2KC7hiHRRfFsJS0ITmTXm
          6Q5D2rPVQwhWQd4nTJ9hoi8+CixSdMqr5MJTLIf67uZeuwWOvHqvWt9tQ1Jdawj3ptDvUgsVLGBx
          x43noBr6HrZn0F7fqu7eq20Ilx35m/5SYVFPrOndLgUsctot3LnjfafiHJhofYrRTKwxZ6rjdwyy
          C4Mpwcm8ErcR2dV9XSGEVKdCFbSzu5FY6LkZxBfuSSovP+G6iGf+yCB31Lek+D5LL0ghVc2xPZNm
          nxS33et5hi/Zcafw7NZVrjmFmMhSzHMhm0l0QDtzTd9gN3g3gLiabKyfalvGbqghkOW8MBwVwZrg
          LALbqtVdJvDeQD/2iHwgoxKbbeGoIffz+ccs8Xa2dIfbNaB7XkH/qjzSQ3ciRFFHaCUgT7HjK5Ab
          Jd4DUO4tsSyKxh5+RlBsJVP8FALLu2ZnDqI9MTwUdKkkwoG6OCoJVypxPywXVxywiNx1svvx8F0Q
          m/ksCMRzkVzgGsCMB5xQdwb2iw1GmLdTVHHrcNKT+kpXHkSQwpd8sAhf8BGunCcfz0hNLhTLwCJV
          ma0uccOUABKfeEut9ir8a/5iL+28fN0QywuuHWIRHq8ReFT5QrcUtTZyurjcn+vGi61sYTnNBxGf
          ChBBqbI3/s/Cx+9iTZ6tSXIqntLV8Gyd5BQd915TZmJxlv3Uz37qxfP7tA30woNLqhMhc27mKTfw
          Eq3CXTTW7zrAldirVGfXSD+xfjD7dWWFxBulZPL4s8nPH5FoB236H59Nz7/AL7uH5QqZ/uR301/+
          VuPbPvvu2+nXTwmSmj45Jx6gWnYYLnYu0gUcZHL+q+m/PwVUZPrTJ9Bk8i+PeSTTL85X8M25Lx+T
          6dOfTb5+8r9/nPzh6eTJDwD+z8++/830m88Q+fSrL57997fPP/9i8otfx0wkuoxsZrusUg7a4qW0
          I6sFqCDsRRlyRq6Sfiz4kLT8rQ0KwBpfJW/BZL/CP7ZB39kw6QMTiW+jU/xIm+U8zdEXPssherzi
          TPlwhejEU1RQdPQ5gjP6FIHkYLvqCmepQ+7cIeW3Fc8e5L3HwFDczMEgeqAlKh1100B1ML9Uevtt
          fCwkZ3cLSxli41XoSj5k5QYAHhVCCf1mvV8CKQo6QB+MMJeWVO9ElFAXF/G1vKFTCgJZRl4KQE7l
          RVxSVE5HS+MYTvlex2iUc7m3VFp+6yaVbrHls3euFxQwlnK5UlDKFDoh6cpNxXMfp6pEBUupxGgX
          7da7rFvFgMs3L75XqETgedRahCWhSaORbL7/YvhOT1/swZCcexuJIEEj6aUHiUuPElyQ4L/HwQOG
          m/2/Qq6/DiQ8iteB5HUgeR1IyCUGkouNI38uYYS6OEqADp3goVz5HqNgY3L2hAC+0gLoZgCKezji
          V0TCAJYNVeNy9lsg+DauCOAE3+IXPPjOz57P0q8hRaSAGOn/tMU1MPE1OXglBK8UAy/HzfLAKxwz
          WXCZgEW3WqUiTt9iZfd8s9/cotJMBOhll0bo28TND9EIOw5hFUEaVwzx5cAxmDHG40C2h0XuKMIA
          +CN8ye7q7DeFk+9SptCJSV28Z+TsQeXs8HSwN4r7xBQmwB7nwAifqMEyl0dhP8XalX1o7tWab/az
          3zc7J5bhecLEtou6RX2VfuSVxhUY7jFvcBQm4GEChAnSMB7iGZchiQQc75MyuTVbnJ6BIJoAQQIZ
          iOHiEjnwtAxEix0xmBmJTS1q1lvBpqhNbU0NwSwrUxNTGedRoXjGeZQYlIQalpe1GRiLJaCQ8/Yq
          BbpMq0mqIzge4AvSQVASiUsJaH1QETk44W5iRuGNCgwRZlWgTYIzHlB9hyx3AxEB1L/l21T30lUo
          z9ug5mryDP97oMIy9Euo31n0AUMfpNEnfxN5nYyiyB2OwI8UjVt06KBjq6I3zse4ccTe7hTUBrJm
          QdRsa45XwvX851PDdyRZw4dX/g9QSwMEFAAAAAgAynsTXfxxkWVQDQAA0TMAAEAAAABQSlNLQk9U
          Mi9hcHAvc3JjL21haW4vamF2YS9jb20vbWFjcm8vcGpza2JvdC9DYXB0dXJlU2VydmljZS5qYXZh
          vRtdj9vG8d2/YiOgBlXLzMlGEtcXO5V1Op8SfUGSfXFTQ1hRK4k5ilRISnfX+oC8FEjrhzZAm7RA
          EfTBQYG+96Fof01fff4Pnf2idrlLnfyBEs5J4s7Mzs7Xzsxultg7wTOCvGjhLrAXR+7yy+RkHKX7
          1675i2UUpwiHkzjyJy5eLt1OlPpT38OpH4X7VwHU5zgMSXAlXBuHwEJshRuQeO17xBjzojAlYeo2
          2Ufh8GCOYzLpxWRKYhJ6JDEgZzFezn0vcetREJk8ZMM9/4wEh1G8wOZsMMnkFCZyJ36yDPC5e8A/
          ixZmwD/243SFA4FmwC/IxMducwHEto31CZ5YZuMQyzj6knhU3G6bvuhlv18boWhZUeI+WPnBxDZw
          BN8DO44YGs5j4N8G0Hzgh7aFAYdrHwbASNLUD2emctc+OXUfxnjtp6ZU2WA7oitqrG1GxAAewx/7
          yDFwFZ0WCePUn8xICgJJU4uIxWjLDwmOW/g8WpnTC5ghOUutTMjxCCfUW5erceB7yAtwkqA6Xqar
          mAjvQUCChJMEyd+/vobgWcb+GqcEJSm4oYemfogDNEhjECWqH9U6nUZr1DxA91BJxISRx8mW9ovx
          /TBFne6wedis14bNbodT+KgKHKo4OZNCS8UcVTjdM9A65ygqqOIDyFf9QQXSjA2J9UjTswBKkMx+
          NSDNBNCpbhD6MsgpitYkNriW6mVSXCW5CYz4BSNkmugk+vPzdL44ICkIMIrRRHzRgQ7IeDXrEy+K
          qXxi8SU33ToKQJUBQeMoCggOEV6lUSPE44BMQItpvCI5DKruxIsJCY/3CwaOcihBBPY1XSaDFMfp
          vnXoMMYLklvlNIhwirxVDIJID5dSUj/vglRjCAMcmDvBGvwDwQYEak2JUxb2Tp9ktYSAsRkSVPhE
          IFlYJTiVIXZHukCpgtrdg8ao128+rg0b5f0MXYodKISgTl0pjgIoZS8ANcU46dxPVKY8xqfYSVUq
          CZUe7EdkFkercOLkfK6CQmWHdUqXz1+8+u636PLFt6WyRl/1AMGR5iNOBiqfUu/TwWcPusObIsiU
          KgYIR3Xbtc+poLr95vBJBqOsQZvcZStyzGHpiRpzjo4LOmtFEajW0VYnrQxwB+dJShausJ+hvyBt
          Pwj8RDMBf4ocuZm4Hg4PYnza5V6bcNWotrTRj4BRmb+4xv8WGyn1kChk/NWjxQLW5fBsho7AR4VB
          TAM8S/hXJqDmRGWBMsyh0T2QzyoI0LNnSjBF7/G3ZbA6EFeIBsNafzgaDJv1z56oCwcCMUlWAbAy
          ISAuTpTKFXhqnKUxdkobAPCCPVVugm8OcIBTvK9xyLIC93GjPwDjdAcHn42anSG6fw/dvp2X54aE
          xkQPxx4JaBzSeKFwwAuf3mVbn6oCRIKEvP0Emla1hakiu4f2qOxV+lL2OgdJGi0HJJiq1sI5UzQE
          7pxpyTK5PSNDi+UC3TO80bFDl1mkY24h8gKn3Tho1sBlu5826iyQDBr9x816Qw+TmXHdoxNS6eUm
          UORSUQRip+JCCPOBibiOg2AM5YgZcajf56ZwM+i8eOWj+1z+0TeKAaikkNA2nW1UY7wxo6Iez9SA
          uInqfCvlu1CfJNEqprtPmQpZFhUEMjSPvoMEMJ2zuiTZz1E42o3CnPizeSpJaKYtOflYUsyLh4YM
          Gli13d9cR5YDmMOUydTuW0BbSIvSIJCeO22czqFEPXM+urNXySZ4H90qKzpREI8MxNsfZohHElHD
          nJAwgUoBEDMcQ4lVIGK83EHUgvbB0qdTW5WvJK3AgpLOuuAAzRDCP6QiJkdSUMUGZ44o1azbf/ig
          NroDjwl228qnnoQDq4oz8/1Qz9qLU4jiDOJNFiVEbA7o5bj7uNkfPqq1RgfNQa9VezI6bNUejmqP
          ht1Ru9nvd/smAUUzVLmDVTzFoIqyCUkD/ht5vjpFQtJuyPRfW2Of7UotGiJDyG9ibh837+fckYFz
          KojvOwpx+qTxuSXASQRO1sXeVys/Ji3QYZIykraIx7IOjqinF7kp6ZNl8zduWEZZDjSdwoLbCTMk
          SMFF0uGU+MBokeTTDfnoObbL5qkxO0wQFp/mdigfmbDTPgL4bWKaqVVYpnbzj4hNuwJaLDn/SBEV
          AtqkQ7Wk1G9F21sNQGoeFYA/9gPwH9kkSMRnsQS3oVMtOja2JGuS/Hv2LEl9BKibrMYLP3WEanff
          iu2ykXWY6yf9VRhCzu8Y6b18MljQBDghNwRpYxDboYSzsGOZeLWcgG9B+Zr3qwsIEqk3Rw5UNNEp
          1RjyZyHUd4biLninJbC6c+aZmVjZT8iNo8Tw5Y2oLiq5GKVqrthCwGWv0r/KWbLhKqFBjuIuWIEq
          bNShHQZ1aogHkD/OB6w3ohfRlnJGkbnahmBZAP2yVkUpKDhrdB1Vyzx//wSt0V347yaqWqmxdFFR
          oUKOtS7C6PSKUlMDh4JjmbDOCkW8qTRFNLFJsI9RdW9vzxJrN00RIJUFXPRTBj+FfCNLZ6qtipxV
          YWaDAkLQXsvqGfjL54dMJUXey0fdZZSkrG6+e1fTZFGdrMk5jWazgPDOCHPOXN27i//SykH0MQDf
          2DS5HQgyCSsCCgLp9uXall0032beAtPOP6zBC9o7IbRXePUuReV99ZZSakdrnyTvi0zs8vs/oMu/
          fX35w4+vvvvm8nf/fPn8m5fPX7iWzMzOXqvReTg8Gg2Ouv1h8S7lJvPotLCGskZQ7Vdl03yiJRvY
          Rqls9o2sdb89/VGUnyOygdiiJkvQJjbb2FWF21VXevmbf736yx9f/vgfdPn8r5c/fPvqT3++/PvX
          6OU//r2r0nZQll1JFzs4bK4XpshB64xDOHG0xrmlEXHc7Bx0j23tB/XIBI2jM9EWVF/LJqpEASiW
          Usc+BEneD1XBXRBD8xfdzrDWMpF6eMKCz60KEv9MmAfYO+FdWHaG6LC/Lo5nYwcCMOSu/J9WbvJz
          IcQiNuWf/85zvmTbJLOZUm9Qso4M/F8Rp1o1xtp+eEwbBM6ebchfrBZFw3LNVc44+zCAumE98L2T
          rC5Zm9FOPzx4T/mZC7LvJMGgz25JhpoU5zgp9PYLFZLqHWREj21MX15aPDhvoS7/6GHYdROH9jM+
          uFO2loXCTiBObTUUGN9YSr9RL9nHuK3smYNWY9mM2a1FjEtzucOs5Y5uLALGai3GBr+zjIHq6wr5
          Z7eKhSw2dy5geSCXF7HY24UkVU8/PmpqJ0E6pCnzzbg4mnbEp1tvdIaN/s5i4IReVxLVD7bYG+vq
          nS9pS6Cwa3/rQ2PGT/SjUG1Cd/ik1xjVer2WPJ7qAtFW7YlB5e6VVHpH3U5DYbcYHgVLS+VKJVOM
          U7wxb+HruF/rjeqwfYDuijfetyZAlfJG5Fl3ix4nHHbrjwa1B60GenZlUncVPdBe9xE9pRi1mu3m
          cFDMmdppHPZrnUHrEbVyM+1QtBos6b2bNW/FSt8YdnvoWfar1Tgc7qsINBGo3tFeUezq7Q/U80B2
          RYGdJH/xFMEKQ+H0/NWtp/s5UHAHAIxif+ZLUPrKBBQH5pRqjGczeoWCg8uB6tOcV7OoOIxW3jyL
          is66QvNHYyNNTn2WZbI9rybOcJIT2MqsDQsPQ/arXGxxa/wwBzKqzl2roqgkvth7SjvmdIo+Pv28
          KEtnoFUV9EkRKBcbp0s1tBWqKqDOC6YVUuXUphgSfDugKOsFxM6yaUNMssuG3zuYnOnCgWpdCM3O
          hsA61+UksTRjUB+awLBiHY8TZ3JWRvdR9RY9Vty8POcvt/XLdGHxWxtFsMJ1Nrq6wefitwqAha2o
          5xvUah71vKj7Rx97OaY+Ws3g8qYL3QZFjg8uVAEOtrC3taNmac3JR1hQsdjMDiN9xlD9nOSLplxy
          yQgr2inIL8VFIZAtrFJ5bwpNF5JMFAR+Tj67dxg38/NzBMt6rImyrSjMAeZ6ODLzKjxG2BwQ7H48
          oOdf5qauFgCQuZTo0Q/qdkqQf4jvh4elMrphIJZ+GZYsr7NOlKw80PXryNadopNBco7++/3vEZvN
          Ogu/gedO2Z7plH7i7k2nUCfCKjd9PhueI+R0n3cySzeKpxCQlhWCNNW8sEiruWtJOa1uyRzzpma5
          L4xkqWMZs2dom8uK9jxENo0KGiOWu8hus93r9oe1Tr0xanWPNbR8WLOgo3AhLpJpXQ3bRPlLK/QJ
          F+Ic1SYB76rmqYqk3wITdztT8ApVDyoCv8ELKxhbsufXqQjk84mhSjkFK7AqivLKhUTubieinxiw
          IDs2aNF4UOfXwod+GhAnswpzXhWWhhAmMSvUYIGDoOmBcOW13L4LAZ6FV9f3Ruwu9YiePtvxu+Es
          orGBHXyYEGO6ylx43Xbj8YAkaRzpzbf/4/ENy7rKW3cstXN/Vbwsm815SWbXzd3OgHrTQj8oEyfw
          xnHZ282XuzGRTam/d2MCpcK7nNd2EVC5rPFuhSqzBkWpet93y+GJnsfEZAHE1FSmuBv9Vizrt18z
          /vS7pV+t/HSApyQ4fxNZyQvHmWde7cvi/3cAd6Zf9EuhlhPMTY52ce3i2v8AUEsDBBQAAAAIAMp7
          E11uaoyKYAgAAIEZAAA+AAAAUEpTS0JPVDIvYXBwL3NyYy9tYWluL2phdmEvY29tL21hY3JvL3Bq
          c2tib3QvTWFpbkFjdGl2aXR5LmphdmGtWFtv20YWfs+vmPKhoFCV9SVNtwmcXVmiHTW6rUinCLaF
          MJZG9tQUyc6QStw2QB8UIGgM1AESbIN1Ai8QoOhbmg02CZCn/TkW/R/2DIeUKJG0BLQCLFqcc86c
          853rjIu7B3iPoK4z0Aa4yxzN/YYf7DretUuX6MB1mIew3WMO7Wl1bNM+4bAyt4BdVyt1PTqk3mFq
          sevYHrE9rRo+cpeNfcxIr8VInzBidwnPpXQHWksqDQrBN0tR7jHs7tMu18qO5aSXB6RHseYy5xsC
          Sju2VhcvWpPfeWJt4mk7jKbeO1zb9KnVy16wexZJrcDmQ9ojTDOI51F7L23tkJI72jbDmZiGi7fg
          a5s5vptavkN7e6Drpu95jp23WqM2wayGDx0/7ZWIxiDkYBOnkYiWTXLXE1pAqLj+rkW7qGthzlEd
          UzuOBwQ0xO5xNHnx/SUEH5fRIfYI4h72gLFPbWwhanuorf+9Uy61zJ22jjbQ6srK6rUZhmxnITft
          viRXKrxghfT5LFFsD3L6fU488RNMExR/aw4JY+CxiN7xYC/SQ0NAAzl2mRHgV6WzEcdD0qvaYBls
          ZIB9pBAZLT7cd8HvE54M4mjPaKc5OzeQmo1AAYFLjEPukYFB2JB2iVrXK9VSp9VufqGXzWqz0TH0
          9q1qWS9cS2wAKIBQwTsPkapEpUAponqzooOk6q2SqScVpH2khsGv3dLbBuyhGZWbnWrDRNc30Po6
          +vDDCWn86e6T7oFBrH6LsAHlHExQ49KiuZN3WqtpmJ1G06xuVcslob5RQB9soNnc11p6u141xM6d
          7XapYeqVJNjiw8i3Poie7sZVG3xseAwS7x9ff7/c3veKIhbXEtDdm6KQzCXEHMcDRMUeyfeqt095
          gl2QaRBlTUahqmHhSTVJLwA1YfdaBk9UF9ToqZV1MLydQdjCvR5YqV7+SxGtwZ98ZhBuAqp7UEzs
          Xlgz1fBbY3u76upnYLlg+7SQdPwkVzzqQcxLe+OX87aGNFqUUqrS+sK4udk0lTyKpApf3qiaeh6h
          Qb8j6vpK1vJyEAE8Ul/BVkR937LUbDO5v7vASKCYmmiWWuh/b9B2s1YRz61atXxT/HMjemHUqhVd
          /FPRN3e2oeiVlWxRKXdcWQFfrH8KX9IjGTwhLKuX04sLQZkJQPloYYYHHHHLBfslQAm5livk1jHb
          o5BXoBpEilBwJQ9p0KQo2JIgy0aFcASw/DkPL56Cu6qh4PTR2Zv3weh3FIxOxu9GwU8vUPD+5Ozt
          S2Wep2mXoTUd1CiURpswdYg+vi7aDvPilhTWAzmfqHFD1kqyZJbKZR3Ky2a1VjVvQwE1zWpj2ygU
          8uzDRbQb6l9zZyMpMtK50EhnauSahs4fH43/fXJ+dB/tVNHZf4/On5wo88SZ1s0WQFGjP5jY1cV2
          heE7oqFZ+JBLDeZrZujbPIhSlPFnHrt6qVHa1jtNqGS10u3OtFQXc0XAfKW5mHECzUcW+qsK+ki0
          p6juN/CAALApAUmHiM+9aZ3Oc5WT56pp+1+Q8lPCZUpXmlom6me5NH8gX73MfPVS+bq6FiZsbr5O
          FSoK7iRM0XQY6RxBFb3MRkrufVddW0nuJ6a+cAwCEeE8ooG7IdZURXJ1BlyZ1XAqDcagPUY4l3MU
          RMrqjGjf7cFE1QzJJUmmlKYdqV3ex/YemSRTwiAtj2Y+dWZHxfgTzcfRvBhrLUX11BjJXcyKIRxu
          RAAR6jgWwTbqM2eww8WYl85UwTHElk9CACUn+lhAcS1FKwGGCdJTC5rrp3EOBRXEmc46VAtpATOQ
          SuK8zJuBYw4CQ1QXk0FSQ8UwHb+7n0QBrFxWjOMuJyW/DISmZDX/qGSHhfDCsh1STEv3OpTup4/H
          v71GwbO3wcNnKHh4Ejx/pGRxZNXvi0vxlsPahPuWp6ZOB1o3PFQY8CB2Gbuez0hUtAvF5Mkqt32F
          Oy1oYRwwXwCH407RCJ6OgtMRCl48Cn79UckgW6KFlXzPKXXhTMLpLrUAhOiIg8TZJW9RlJH5CBa9
          kItjhA3eLiAu9hf8g3AA1228a0E+9rHF58NaaBsfrBLNUJheRBHW8cbhMTiJcW7wCal5cE9mT2r3
          nQWdSJBMIE/Fj3L26ih4Dj74dRQ8v4/O/zWamS2+sqHHpplaBmwaPD8e//w0JD99EDx7jZqNT5pb
          WzksMMcKnie/C77g1Ws0fvx4/Gp09uYtGt9/B0kxYc8REFGdHx0Fz95fRXVnSAn/JDowXMgT/PN4
          /JPgPA5OnwSj02KcfOOXT2A6LKLz0cvg3S8o+OWBIDg9FsacvXwqHuePTiBFx8e/jR8+GD98oSmT
          TXIgTrb5mgkHz9s5hOlRPF79A72dZvZ2mu7tVy7u7UKVouBLRh2IKMubtpBGMET80YE3vi3J109q
          lkhhRiA77NSReIYrHbWTC64ZOq1eMss3Oq1SGwBLD5I5TF+2S61OuQkQN8x55y5t1zRNE7blk1tu
          xjXAApvr2NvXBtRWoXZBlXd8Ji5iCqKUVSh3YWKvE4/Rrnh3h/a8/Ra9S6yw26+Bqz+/vFL4UzAR
          n1Q8yXC6kgwn6VjLzUQy7NEz80I4qSTRS8/EqiJTGI3/8xoeV5GY/6EnXN9AK+ivSPlIQfBOKcDb
          IfwpCKaWWUcuuKyL+2jURIVK0RVR2ekROX+xcE3+loUegRU46x5vTtyMqKSYkH/u5ixBLHpS8urz
          hx8S3HLR2KmZneZNsSSEoY24i0kvJGRHKvOoScooXNywEq05eg8Don7XY1hVpsooSbuW4KmArkq2
          /bk3h2tXCnLogWGHyHupuPdG2yQ2hvgnkjpNMyH6UyaI5aYHj/kzWw+cITExPzAdccsWL8uAvXfp
          /1BLAwQUAAAACADKexNdajgnhm0AAACcAAAALAAAAFBKU0tCT1QyL2FwcC9zcmMvbWFpbi9yZXMv
          dmFsdWVzL3N0cmluZ3MueG1ssylKLc4vLUpOLbbjUgACm+KSosy8dIW8xNxUW6XEgoJ4EEvJLsAr
          2NvJP8RGHyKPVXEy0JTizKTMnMySyviU1OLkosyCksz8PLhuhbctG97snKHwZl7r6wVLFd60zHm9
          s+VN1xKEqTb6SO4BAFBLAwQUAAAACADKexNdqXlRv60AAAAsAQAAKwAAAFBKU0tCT1QyL2FwcC9z
          cmMvbWFpbi9yZXMvdmFsdWVzL3RoZW1lcy54bWyNkMsKwjAQRfd+RYn7ZqMbiQGfC7Uq6A8M6aiB
          JCOT1OLfW1uFrsRZn3sudxRjpIoNRj3ImlMxPR1mATxOxfmGHvPj5rSdH84iuwNjSFMBoWSy5aRF
          ZQcVkJAtuHxnr7eU72lmkqUwBxaduJXbhP7j/kouFNIavHVPoSOEqOQb+p2pbSip7hoKKvHwQHbQ
          CBJX+I/AkCOeGdPMEXo4XqxGy3E/p2S7TQ+U7P3nBVBLAwQUAAAACADKexNdphxCxOwAAAClAQAA
          PgAAAFBKU0tCT1QyL2FwcC9zcmMvbWFpbi9yZXMveG1sL2FjY2Vzc2liaWxpdHlfc2VydmljZV9j
          b25maWcueG1sfY/BasMwDIbvfYrge+NupxHqtlC2XsdW2HG4ttKIJnKQlGx9+7klh4XBdBES/4c+
          rbffXVuMwIKJnHkoV6YACikinZ0ZtF4+me1msfYhgAiesEW9LgV4xABFZkkqT5ETRmca1b6yVkID
          nZdy2pchddb3F8sgdtqZRZFrGqoIEhh7vSvsRDkft7OLn78ic3YWex6B9HjtQZzR3D6QYvp6V6+w
          bzydIf4DvwDEkw+XG+9MPU0HIGAMc46SYo3B33SO2EEa1JnH1TwUPL0C14m7A4gOfJfiAf6k3iB/
          DONku0+k+Yts4FsBU9jN4gdQSwECFAMUAAAACABGfhNds13TJecCAADMBAAAEgAAAAAAAAAAAAAA
          pIEAAAAAUEpTS0JPVDIvUkVBRE1FLm1kUEsBAhQDFAAAAAgAynsTXZ8Hl+1eAAAAbQAAABoAAAAA
          AAAAAAAAAKSBFwMAAFBKU0tCT1QyL2dyYWRsZS5wcm9wZXJ0aWVzUEsBAhQDFAAAAAgAynsTXbAr
          VL+uAAAARQEAABgAAAAAAAAAAAAAAKSBrQMAAFBKU0tCT1QyL3NldHRpbmdzLmdyYWRsZVBLAQIU
          AxQAAAAIAMp7E12yol9fRgAAAEkAAAAVAAAAAAAAAAAAAACkgZEEAABQSlNLQk9UMi9idWlsZC5n
          cmFkbGVQSwECFAMUAAAACABGfhNdlArBaPAAAADgAQAAGQAAAAAAAAAAAAAApIEKBQAAUEpTS0JP
          VDIvYXBwL2J1aWxkLmdyYWRsZVBLAQIUAxQAAAAIAMp7E11pywsRHwIAAHEGAAApAAAAAAAAAAAA
          AACkgTEGAABQSlNLQk9UMi9hcHAvc3JjL21haW4vQW5kcm9pZE1hbmlmZXN0LnhtbFBLAQIUAxQA
          AAAIAEZ+E13lOyeOQxkAAMp+AABAAAAAAAAAAAAAAACkgZcIAABQSlNLQk9UMi9hcHAvc3JjL21h
          aW4vamF2YS9jb20vbWFjcm8vcGpza2JvdC9SaHl0aG1EZXRlY3Rvci5qYXZhUEsBAhQDFAAAAAgA
          ynsTXWwxVV9hCAAA5ikAAEoAAAAAAAAAAAAAAKSBOCIAAFBKU0tCT1QyL2FwcC9zcmMvbWFpbi9q
          YXZhL2NvbS9tYWNyby9wanNrYm90L0F1dG9BY2Nlc3NpYmlsaXR5U2VydmljZS5qYXZhUEsBAhQD
          FAAAAAgARn4TXWDYFvXyEwAAwGgAAD8AAAAAAAAAAAAAAKSBASsAAFBKU0tCT1QyL2FwcC9zcmMv
          bWFpbi9qYXZhL2NvbS9tYWNyby9wanNrYm90L0RlYnVnUmVjb3JkZXIuamF2YVBLAQIUAxQAAAAI
          AMp7E138cZFlUA0AANEzAABAAAAAAAAAAAAAAACkgVA/AABQSlNLQk9UMi9hcHAvc3JjL21haW4v
          amF2YS9jb20vbWFjcm8vcGpza2JvdC9DYXB0dXJlU2VydmljZS5qYXZhUEsBAhQDFAAAAAgAynsT
          XW5qjIpgCAAAgRkAAD4AAAAAAAAAAAAAAKSB/kwAAFBKU0tCT1QyL2FwcC9zcmMvbWFpbi9qYXZh
          L2NvbS9tYWNyby9wanNrYm90L01haW5BY3Rpdml0eS5qYXZhUEsBAhQDFAAAAAgAynsTXWo4J4Zt
          AAAAnAAAACwAAAAAAAAAAAAAAKSBulUAAFBKU0tCT1QyL2FwcC9zcmMvbWFpbi9yZXMvdmFsdWVz
          L3N0cmluZ3MueG1sUEsBAhQDFAAAAAgAynsTXal5Ub+tAAAALAEAACsAAAAAAAAAAAAAAKSBcVYA
          AFBKU0tCT1QyL2FwcC9zcmMvbWFpbi9yZXMvdmFsdWVzL3RoZW1lcy54bWxQSwECFAMUAAAACADK
          exNdphxCxOwAAAClAQAAPgAAAAAAAAAAAAAApIFnVwAAUEpTS0JPVDIvYXBwL3NyYy9tYWluL3Jl
          cy94bWwvYWNjZXNzaWJpbGl0eV9zZXJ2aWNlX2NvbmZpZy54bWxQSwUGAAAAAA4ADgD7BAAAr1gA
          AAAA
          EOF_B64
          tr -d ' \n\r\t' < /tmp/PJSKBOT2.b64 | base64 -d > /tmp/PJSKBOT2.zip
          mkdir -p /tmp/src
          unzip -q /tmp/PJSKBOT2.zip -d /tmp/src

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: '8.9'

      - name: Build APK
        run: gradle -p /tmp/src/PJSKBOT2 assembleDebug

      - name: Prepare APK
        run: cp /tmp/src/PJSKBOT2/app/build/outputs/apk/debug/app-debug.apk /tmp/PJSKBOT2.apk

      - name: Upload APK
        uses: actions/upload-artifact@v7
        with:
          name: PJSKBOT2
          path: /tmp/PJSKBOT2.apk
