name: Build PJSKBOT4

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/PJSKBOT4.yml'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Restore embedded project
        shell: bash
        run: |
          cat > /tmp/PJSKBOT4.b64 <<'EOF_B64'
          UEsDBBQAAAAIALqBE13yoCyIbAMAAAcGAAASAAAAUEpTS0JPVDQvUkVBRE1FLm1kdVRdbxtFFH3f
          X3GlPNMIwQPKG21CCA1qRcoPCEGIqCGtRPu+btaR4w9hi93aTnetNVrjBrnqxF7cDXL+0N47/4Ez
          s16bgHhb+94595xzz8wGPf7q4OH9R08+dZw8UzzLiKuZrmeUT12ZhySNmH9T/ItHcqnEi0kGExkq
          iQPdbN9znI0NkijlaY145ubTW4l6pIM/pTFxHBQk9gB4o/s+132StMaqx3NXe4q+3js4yJVLrEI5
          i/TrmoQLfu/yEEO7Sp+5PG4aNJ5kEofmb56lMnZJgjrAuJHcc0ryBrwkPGjLNOXRgkAQNA3n/MNC
          pj2SpANeZowBayTSQHuhJQgtnvMRGapXKclZhRtvrRr8ESfoAFNlFUJSCyfrifzl66AHc3gY2fln
          FyS9inTfkcwDOW8CT6IFNJOOFKqbMn3H6tp86ctm8VUaLlEmjYh46kvoYWrATRfndx/tb/9f7UvU
          rK/dCYzWgxq+vHx6Zcgar4eRZTRU+XVqaMuriVyimi6lgGwCaPy6grGGLEyJrdEcLczZlYcSufTD
          4cnJd4dHT2HOBfyxioHYbYuHeX2v5BCH0s+MlasFsPLtXkFeBh2DxSrlX0OsmPIszbOLFfhyPQVV
          gJTuzH2JKyBck+CWkBuuj0A3zJVnlUFjhgy2fOvOLF2Lkbhj9u9d05PPHxN0ynmrOEjyewSkLWKv
          xhPsfDyWwLNiBlWOR8gviX8DTTZfdqbByVW72K3xn46enb44Pn15+OL42Skd/fjy9KkJ38ef/fSz
          1ZF42E7RifyVcShV2TmWVFetce802bsHZjANpuvXI5u8vgt22vfsDIti1vrF/t6Dh2arPPd41MNq
          CEmRqGMv6vbO/W936ZudB2aBJusmjUguqwCQW//ipt94hY/A0v3WqquYsaoWOVtVrdD10WrGg86q
          uHunqJtNHkDUmzZGw/dxhfg9+i3tYtHcLtWZ/kgVzUWuYErFPC9L1qs2vnlrd/vfTst8Tdl2GL6b
          B/t72zsk522z4+jWgNgbYHc+DJHgLcRUSeKuM108fd0qt5TZRD1zytfok/JGLG9bSPksNjQOnz8/
          OT6yQdn7fhMt/EdVv0pMXPIPGRZV3JEYcSgfpBLS9hQMJLgu74iXyE3PDsCzdKnoznOI7mFqus21
          s5b+g+zyLPy1Y/4GUEsDBBQAAAAIAMp7E12fB5ftXgAAAG0AAAAaAAAAUEpTS0JPVDQvZ3JhZGxl
          LnByb3BlcnRpZXPLL0rXSy9KTMlJ1csqy00sSi+21Y3IrTAyMLHIVdB1ScsESqTmJeenZOal24aG
          uOlacCXmpRTlZ6bolRanOkKYEbYlRaWpcIm8/LyQosS84sySzLLUIOecxOJiiAIAUEsDBBQAAAAI
          AMp7E12wK1S/rgAAAEUBAAAYAAAAUEpTS0JPVDQvc2V0dGluZ3MuZ3JhZGxlpY+xCoMwGIT3PIU4
          6eIDFDq0YqG21hDdJZifkBLzhyQWSvHdq6VI6dClN37HHXdWj1KZihsuYQATogeJZjmw6FVAp8C/
          0SKJKDUk6QoGfgOTzznH9QeWjgsN9NVN0YXVnMhEBFgwAkx/Z+BRj0Hh7wEVCsg8hIR9w8PueO7q
          S0dZXRZ527GC1k3674NlpEMM1OEV+pAZPkC0jWJaNqd93cZEmV6PApJ4w62NU/IEUEsDBBQAAAAI
          AMp7E12yol9fRgAAAEkAAAAVAAAAUEpTS0JPVDQvYnVpbGQuZ3JhZGxlK8gpTc/MK1ao5lIAgswU
          BfXk/Fy9xLyUovzMFL3EgoKczOTEksz8PHWFstSiYiBDQd1Cz1zPWF0BJFmpkJaYU5zKVcsFAFBL
          AwQUAAAACACLgBNdH2Az/vYJAABKCgAAGAAAAFBKU0tCT1Q0L2FwcC9wanNrYm90Lmprc42UV1QT
          CBaG0yHUEKqK9A5CEOktIFVHmgWiEJogAtISyipIDL23CKJADDh0EcKI0qU4LBAEKdK7tNDRDFVY
          5uyccfdp9+Gee+733/t4PxSRxQQEBKOI8C0YXC7aLHqXHcgEfEmEz0KI8MlTPIoiQiv/K4JSIERo
          7inOPq2nMNa/IjYWIOg0RJ9CHZT73xdQdhQGpfFzZEPJQ3gGkRKd9m1rE9+2GefDr9oUp9uYa4BA
          0ggQUATFBmP+9y4IDgWgzsPgTtFmQDcwBCgHQTQW28UWou8l9BeLICg1qg8hREjfMstRxLsFmfBO
          lm4fhDX5Gf8oImhc+iypJs1gr5A3i9N45AVlJNXTHostxinwZzWhx0BkGy777daRqXWyxFcHErkQ
          3lpd1hFHywEvJNle8PO7DAqunfVSyqqmZQVt9Z2nq58J65dMuc/O02MgaBWkvnG7xumIiyEM5Pvg
          YesjIGbOmjHELwjt29aPylwvXq1pzxTTREsKT4RadFz/RY6FGjcnBS4Avm0Se/v0WLIx7HozPV0u
          ciIqpEXn3DDyw+zNwoNO9uw/3iCbn/jMx7W8fa8NZAsMzmoxLC1PvaucaLlvNgNDqOdGJKwcdD6h
          bKl9KbdnTAkTDNKAkqXM0bpmZo7nRoQnn9KHZNVoq5QnMoqIbCB+gDXe+jPD3XFcVQivYztd9N2a
          GLAz+JbSyDE02vkhSntwiZfL1vq8dqD+FU+6uA7itkWkmt08Uuv3dbSnyRNVlTVcoNmvK269iyNx
          Vnbxmw94dL35pPI0xGrD8EzAH9WgoZgLsmMCizqptvuMm3aj8ahL01yTlVLb8eGZIRC6HjA93TVR
          4yBcpRigp4NFMIQsYncvZtVbI6bufEFzbsG2l3JnjNpw5aJkVuynPOtwEXMfcd0g9Ch5v4LkWcQ8
          9kZEPlRKQlNROK/VgKQjUVrwnYl0nKRPXZcUvx4T+9m4Jkl1ulsz2cdJsR57cTY8bLlaxZKnjZP2
          tYoKIw2DO6PAnXFrTjslsWhwwK4c7B5sH1rR1ovpXCDwy+SWKCWoUACJsrjC9wQqHnO1dqK3bfPI
          WKLfvrJYBVCv+b2zy8g9kriVukdoxwqtSyW/jaZBOme5wX4i0d/t88T3gXCNF1sfD4metsvgjW10
          RW3AEptk6h28GL8r3yvafIWUm2vhlPe7Yu1SKG0TnqkJj105Z9St91BJnWrpYHsnWlPL92zO3V4/
          c/x4me/eKsBiOSCgTJicDQX1hJJwyg9MMYy7DZYf7Ug7U9oQBOT3foGViFHVja/gxMXjVPv8/e4q
          9OBVMN45v5jvjRx8IrQR0ORA6hphnhGvOLFwEpoCs4tq8RW9v544uOvXGLhrWlvPKHrYX9i5w0Ga
          MBqDWZV4suPbBdMHTRsLLoaK+MVQrxZlc+o8H3+0Kj1re+Q3Kj9X/42hJfUR2RAg7XhxPbepV15a
          9bMqzJuf7qzxdZK6Rk05jG53L5UMMp10VOccF53zvsWcxmCVdtINsJEwyNe4ORPffKxbdcOnTo59
          W034saa/wGcWTe4+ES62z7nj8o3NWMIiQtvfF9CFtuZeGfMhlDtgsN0VJXh/l9L0kz+cA2sTbVe8
          TFo9GPcTljc6QZVLjnzU0uAdK+75+s0UgQE3/K/ZfR0RoYGIAYVPFXDy83lcBF0MO0GrMoq701oU
          EiksYQCrUmhLCZME+HN0vB7I6Wg9d4dOc3cKu33rUcEKFdJx+P5VxBp7N3wV7uKDJZ4c9EKCHB9T
          gL48uBs3rxy7BscWS4pnDwqLQlrlP5bllQYcilHeskWEP6ToB7GoOn4zXAjzshjn2D3Jnn8gLcfJ
          tfWRCGiLOY7PHeSe8GcxyeaPu7ZDGsBHThtsbdql38foX7bkKsUZFy08HKL5i+Qw77pnrW4kcBfp
          wrHTHTHGSVY9wd6PRl4OkWmKyoZ/Su8vXcJ5lBFCHAA/gCcAB/ACuAB8AXiU6M+YV5kHgrxx/4Gb
          iLK6hrqyquolNRWUqjKKCPm5xAR7SYQgTxEHCAg4bUz/YfP/JWrGBeeNorOScb/xGwaliVlrFug5
          I/4fUU8KzU+/NJT3sK3bWjJUSU4nEMGpmKmmfZn08T5gfqxFl+MloZXhdOeMiuqIRo9UdNdWbaK6
          3PHMLPZj3LRNR7a/E0dDVCJyRmjJAP0y49nSwepYr0xq99ilu75jFIdHPhncoE9pFgffJm305Vvk
          32Mko2V5NZ2o2xfScXiDb2nKbvl7zF0CaitnpDPM/1moMjdIXFQjxzs8lmoPSe0uaDbWHlzDE75M
          hA17txTzu9aRlfSiTNYod99BzmcQXF5hoqZq5qJCMj345GnqxxCFGwnezbcff04mQt60Pjbo5N8P
          GFApu+bnaHb04MVCpZI9GpOmYbehoEangmOrfdtO0LRtQu6ev01jQoZpTb0sY6XBOUxpvrtpOhfU
          N3UVDHTNVBIbtbRrEV5uSHJd3VEUUOgYGY46Mh91xw5fwRU9MLqkfpmKvRhUzmTcmMvelm23Z+OF
          /ocS4smAIfyOymhKrP1zBynxLWmMopop1EWHQIgl78w50yUDRQ6kH9LL/mg4I9jywqgcO2EM9iPZ
          tc39sAaKgyMnL1cHzzwjEdsertIdKNgVKoXl+WzKbc6C334EXxljqqwnkN0cd9fMduFWQS0tY4Rp
          D9gWSkem7Um61ZHuiNN2L2Jqum4NB2931d/j3lyMyZCcVD1KOJqKjTnsIAF6lgtNXvE2VIv65AHz
          MjCa7aPltguzq1qBPbzdyGhmQ+i91pP9gE/xcC5F9K2934JE21KywvmQ7LNvjH5w/xIY/gvAlGUh
          BykAN3j2dDGTJAMlmEcW5MLIC4V5eF9bwOzLvjaBSuHld6msAaHydNpQSEv7ddkfYd+/JHEMJINk
          JWuWm3lfL8xaKfSMenldwaUcUsdDtLqmLtXx2RV4a+k7zDicQfZ2Cxdgowc6K+WaF65xgu9XhalN
          St9qKKMm+W5ievYecVmkBnS9ZtfuHmsK4c73NM5TDgvt+XTgt6+4V/Rj41qJN2eyR9mNAnYGBwCs
          j8zjEOSTTVpp/V0ts+b6ZvWHqkYdnIvNF734dcVzLO+UQST+yeiSrBCPe/a1jl0nvF3SHY9Yrc/3
          OAK7yns96HonEECeNDzHY7hm0C/vq+2vy86vXo+5MoxxJKBV/ArqTM8nlrM8W+PfNL8jzNjCmxKW
          Y1e1kUKYFnloirFuNHgTBBMsy7N3samzY9qIK7c8m6GHBGmFBNC9Cu85SoSL2ycLWlh6NuyK7FbV
          HgqPoPpLivMtaF/91F0qYkzO9EllxaKuoZRR7H+/LQgIBUBEUFKM6KeHXjRDC+W9gmt1mvIY84Ft
          zr1983fInH4VigiERy/l6UjgdAfxtf/9OVLH81tyFoDhP5XwL1BLAwQUAAAACAC6gRNdB5VPREMB
          AAArAwAAGQAAAFBKU0tCT1Q0L2FwcC9idWlsZC5ncmFkbGWlUrFOwzAQ3fMVVpbCEpVSyoyqIpWh
          RRR1RZf4El3j2JadFEUo/47TuJVJB5C4wcO753fv2adFU5C07CtiroizSaaqBCQ3ingCWgvKoCYl
          J1EXRR73bAkVWg0ZDpcqyIxK9MGWqaonJ4aDNQnc8ZLdP0QniGMOjaiXSuZUeKG+glFrzuIrwfjC
          rEj2grPFBanBFFj7KWfwiMY6saXiyOZjdOOss3ieTAfZbvBmqZAki8GbDcx5DwFyotfK4LPLx3J3
          3MSelRxKG99eM1/B2k9lXDhPnE1ni/gHr8T2SRDYC+Wq/YtIF8ZJGxL8vdUYRuGYNsU4SJh79Arn
          9x+N6MugQLA4EnPfQ3m7kpAK5CwHYfG/w3wev01b3S9JmMmqxmS4dG23PykJqlv2AkfYD5+d7Fdv
          u/V283H3OFqZP1/p3PZ/A1BLAwQUAAAACADKexNdacsLER8CAABxBgAAKQAAAFBKU0tCT1Q0L2Fw
          cC9zcmMvbWFpbi9BbmRyb2lkTWFuaWZlc3QueG1srVXLcpswFN37KxjtjdpdxwNOMSYtqW08hjST
          FaOIi6MGJEYSafz3lW2wTf2Ipw07dM89Ovcp5+atLKxXkIoJ7qLP9idkAaciY3zpolrn/S/oZthz
          SsJZDkpbBs7VgPBMCpa56FnraoCxos9QEmU35zYVJSbVC5agcHOGhr2eZT6nVqD6FciSqfWlVmMf
          cFKCi1qGPcCOH+MkmKbeJFgk6UM4G0cPyMLDf2S7jRbBt0V0PxuncbD4GfrBh5Kl02Aceul8Ed0F
          fhJGs/9gn0dxks6iJLwNfW/NFW/ItmykqgpGiTbAzcH6axlJUYjfI0Jf6spFOSkUoCNMQZ6gcNH8
          Lv4xipJjuzYVNbK+Kr0qACfrP7sFNxq2Oqhmr0yvdieHJNvQ7Clh3Gtw6CQQ3iohNZiO0rKG0xhF
          JQCPJAOuN3G7SAFXQk4MQlFSARp2HB3GtcH2c1ZokF3bTvvZQmyd7S3GnnrhvpQdElMDWAq5ukzT
          ouyJdz/zvweLIzIHn5Hr4DbHh3lXIF8ZhUtp90mlawnxFvle4v/qk0NQLiQspah51nAlq8pcUELG
          yFyKX7DJ0b45rxXo1Vp4lIJp9ydWmAAvSt1PxslpGZnNkHq+H8RxOAonYfK4G/CrIv/I3iGHQTWJ
          sE9G+m4XdK0laNLPiCZHgq4Xgs76mnUtaknXY2/2PO44p413SgXP2bIj3MGNsV1O+GA7mdcDt8/H
          sPcHUEsDBBQAAAAIALqBE13UE70bhBoAAA6CAABAAAAAUEpTS0JPVDQvYXBwL3NyYy9tYWluL2ph
          dmEvY29tL21hY3JvL3Bqc2tib3QvUmh5dGhtRGV0ZWN0b3IuamF2Ye1de48bx5H/X5+i/Y9BerkU
          yX1o5V3xIFu2VhdZNiQ59sIwjCE5JMfiC8PhirxEgJ1s7hRJuXMQKZIDSdgAyjkHJLi1LSTyQflC
          Ivc7XFe/pqe7emZ2LedwQAaQlpyuru6urq6u+vWDI695zev4pDnsl/teMxyWR5+OrzWG0eaJE0F/
          NAwj4g1a4TBolft+K/DKF/qUPE781Nv1yoNgWH5jFvlvTNptP9xMpE2ioFc+G4be7GIwjpC0N4f9
          kRd60RDLuO2Nu1d8LJuDGyM+MZo0ekGTNHveeEwud2dRt3/Oj/wmLYT85AShj6AYR15E/7SDgdcj
          wSAiV3fee+uTS+9efufsRXKGVDezid++eOHNH1HaWg7a7XcvnqOkKzlIz3PSVdoaFy1v3lVv9Nau
          T7PxhmnEMcegtYkntntDLyLT1NSZI7UxHPZ8b0CpguY1B01vOOiQ1sS/NBbtgEfWuMCrVpK1kB9m
          pSTvksamqDUTnqgbjMtBi0pKb6NKmdKEKfJ+Rt/PkPesPJpmtEmlszrQdNEkmXbjBP8/o6u2h73W
          VS/s+P93neUPWm/ztim6uFY5OkTm/4H7QRZDk+MaH1Ha5/zGpPPGcOqStWhktURm9N+0Rv/WHNID
          uUSzka9JTXIvxGyEsNQnYCne0U+SByq5aRUEVMUkBCkzLGVagzw1LA+kzLAUqABN4205jjwvDNrD
          dIF+Oml1/It+O0rVU0Z1Oeh0c5DtOEhgCtiS/VCnKjr1x2mk0u7USeSNUinjIVEnXfp5bHY8iKGQ
          EC88hgBKaQSs7akUO3Yq1mIHVbKxDiKrnYoM1VLVMqpCSDcn6VgDJaHR00nKHUm1g1CwNlICo3dV
          OrQONDrRoyqVNYomi06UaTk1/u3Q6/tnm1EwHIxdSv/9NQsljgdbCz5p+qdXqoB1taOgkskT7eJj
          iVOlM74wPfI64+IOg10v8jF5X/E7/aQnA0ZzKq3zZuL1YBj2vV5JughQpRLpsP+jYeT1NJEJvgXJ
          jf0VJnl2RHucYnWTc9mNuPxd6j4Tr9UqOOcAqPDSUpJp0CYFbq/P6G5pUbTcJPd7Y9/Ow7zTIhdS
          vhzgoxaZOPPRn2f0HYM+b5e/0Rs2jP7uB4MPqSgvDCK/44fld85++MmPz158/61k9/e9aYLqwiWU
          Khjs5OK1k82L1jfKQRYOr4+PralKU+RQsBxeIZ13vKhbpp8L8L1EQGOLyd4SAuKE3rQA3xlhzSTk
          MtI57gDhzGa4YzBE6aScaEoyASRj6hSXDVkCcv45mc4dcpaM+OQgSp4In5JpHZXWsdKY2Hmi6AGZ
          oo1aPhU3pwXaBST0o0k4IEzcZIkJt0heI5XyWntTKHucpx0OB9GOng9kZdNdD1pR1yD7kCyzPrap
          uz5MoiZXTo4w98YjGvDq5LK4k3EfVtslxbe4qbdemqqCqYDMADD5bZ0hlaJkrlkoTZ+12rfFvEGL
          5z5zkRiy1wTYljFYHuoOUHdQ1lbNaTXqtNrllfV2supg9mz72xbktZpBzuyqTd9x0Z+32GNyi7VQ
          08UU63lpGPlXQ4+KKWlC9RiMy2hivpiZL0ahvxsMJ+MdM2FXI2WBOAxwPfplL2X2S4bxG/v+YNPS
          qviNivSD0G/Zr0FjrkReGMnEbKG8OewNw8uTgSaTOEbTZ24kqpN5rahuevwIzu0xOKIx0wLRecAP
          E1aIFrZEWbotkGVZaCWWoXq5VYv5j8dTramlQVNDWWhnIyoEenWFqoupQv1gPA4GHeb4jm0VSQIE
          ObzMZtdvTXo+6FV/ZGnJxKiViV4lswtFmWRiVBPa0RNEB3IhSqIxWhyhRj51+uEPsBj414lCWrfq
          BTEvI7lV59aJRyOJXX9bOPb5WSTFUCfjxHcHrwQz5hr50wiacqGloa1GOtSNp1fgQbi0QTM+KPG/
          29QnaYZUjT6QH7aNRrAeG09p8qxEhpPoQ/b/jsHYBiCQlDgARhK1oDeZuusNgnH3Q3cSXpcO9ZW9
          3o8hzliutpPAcCJUHYXDpj8eJwEKBtyTAP5PogHMrLFI8YqQW2rytp08bLfHfvQORw907ecdA6Ag
          FFumPD7ghmkzSbKtk2wLfySmEf3J4lKtnibBtkGwrY3aMSCQojonSW1ltdLWss9k4jZNrFY29ERQ
          EPBmRR1iF4NzSxDuKMJtk1CvjEI9NqobbWrDx9oMq2MsK6crLHlqJEtopXp6zSIQugWp1VOOVCi6
          ui5Ljm0tODBSx8C5a5uWTNPAWrmyZtZdm7qYNRwMrzPbdmU2jvx+eeANhleDvq8sATxMLcvv9byB
          T0a6GrBX40Lxo8rHcQnxKhNpTMDtGwEpf6NrjAjErkRh0PIl2WX5wqQcBVO/l6R9L36VqC6zZRC0
          1kmD/s8sN1tZ2va9FrwfF2jFSnHhJZ27Vm5sGZPwTYrhhGcyalGDoKw/LQ3KLHFRl9RILDFeVsWl
          e1MXejShxuJMoofh4Q2CGjejf5Z0Gc1STGjw+lbfp4Nw0JyxzLR544Iqzl3TZAvVDGXn1UuLxWTi
          XfxzypwGT3sYkkLs6XTJ6/p8aGq/xrYMMTow1hZPLDmyPOWgZYOvPGVKhw+bftD0grASS6S6ygda
          kdMjuDDnJx2hRHKxiI7PJrhOk1EhRaIxztwSn/w84mSIToNKkmmmKcOYlRKhWklBm9UoM4TDneYQ
          R6PMAA93mjMfj3rzCFH41tCIBCprMcYheE2f7EQlGXypQT4piw0JEsdyQ4LGIRF44m5z05iKwcZ1
          fnJNGkUrU/ymiLr5DDezbGOCjWm5kzWL5yu3e1Oy+SVtt+X/XPETnvpk7LfECBIbGwzrzipWHg/D
          qBBviyg32UcaAZ0bUmfPZyPs9dc5yFQs07jbDyljAHBOHGUoChwA1lbKErHC4BWIXGAufr/QKAMa
          ViKzooGsxDhEwx+DZzKY9FCoBpLfHDKSt+GFjsgmyaH+MduINoLHOWYrWCdRxwVkSyU1iLyAjsCo
          WCTwJRhMfINzXJkW7VNaEW4DaXgclTmyAQhZ9RMaasC/9iZaHMvLfCTy059yTnVqqMFlyix3BDKP
          yjNq2hUQV6GTa1TeZTYeuNmlijrPJATrUVdjRms9MvFXjXiiE09YEydm36kWzWgLTq/JqSZuBUo8
          ocSVcuVUrgY3eY+3oMU052tktaY8U5Q9y7CltAXrc3g0bYIcdlUlEcjbTr1xIvktOfBpNXhWrs1Y
          HaSy0/GsVNUcQ5KOb46I410TCFd0CFCg0pDtEipN4XcpNLvAQDrxDho+BqCuMCwyCsskBPgvDu2t
          ZIGAyUnXpuKDnvkKkMGguMHXpPCeSUiEiy9PazQhZFkONXqdk1y17Z4Ald3RSkyaHnsadNYo9K6z
          sIyZBN5Y4MVNCTrGeA4YxWIwzsirrzory6m3yFq5Ii3ET2y+knfc9dREVl3DF55YLVkJ+BB2drPF
          xUlhUgJwul5rk6XMHLzlQL+ygUwGrH64JOJoObUQRQZlgAFOr1NcHxqAY0bNaVbSxTfhbayklc9p
          TlXaiE5lGqhchgWUxmkahbVg4eVVMBjqbUmZENNCJCvKvATNmKAmv4ysh9u61/dmDZ8tTUAMyDJa
          wW1ec8V5CQSV+pQ4NytU5g1EmiqsZuj3h7v+hXYhIst11PvzOv47GAQAT6ZflMglYiHOsE5qK8wz
          QhmDmtSJCm8FSqXjSClOviUqhyMa/T38e7YWWmZLV3K5T/fBmYijMOh0/PDqcKS2OVGZVk9XUPwN
          ZLOl5XGy3eVO5C434RJHtOT9T4zGev265gUYjP3I426xqiufSywese9argq3sUSrVTRaxPltkeXa
          KvOV+fc6kwDSOrmqQ53KdtCCLRC2doq5pX6G1DAdY/qlyXoNF/UrqginkNm21bMcBCsYvvPJk2Sx
          /+sXf32+2PuaLB7/Yr7/B/rni8U3T8niq88W9w8Wj/bI4t7fXhzAn8fz29+9+OaPZP7t08XPPzeK
          CQajSXTR91pM8OuaVRfuht/zZiyNC285kWNJKbBWu3g1CpEfH9i2mc/2ZyoX3f4Myx0OJ4NWQVb4
          tdhelCtIVG/0SDA+Nxn1giYd7Gp5CcRe4i0pkdqGZHexaK2y8XEIoyI0wxbZvfK7birpuFZQlNqZ
          jugUhuO5EbyjoHfGhMO2FthUTAQxDKLLjtp5v9/wQ0xo2nSBSchtYtXM9vIMrMN+amv8/7/NHTUJ
          4C3Mb90lMP7/9VekQ+fxSejPHz0niwc3qTWg439++wk5vPPFYv/eYm+f2orPF/vUQtx+uHj868Uj
          ajzu3YSkfdNIjEFCV7uhPwZ5obO2quJ6u0RARsu6J4JY5brNFbGnsQW3V4RSRpaOqwvQS77RI71u
          HBnzlV7d/euycJhqs/4Kscpx4i6k6qhNtyx2G9ieZ7ccbznAUhMbD4Ctvs4RrxMw89FNDDRNpTOH
          m7XgYbsh8bpNCOsgjoFnDS9jdYSDkNwpzFhmOtrCiNpxA27r+ZCH/GkQ4LkpBgA6Wb4XDK5lcAQS
          nGsyA7RL8Q5ps0CgmHsvZt6pjqCFZbUXZxn00AWlhXYEkRZb00K2iFqszaTkAkzDxJggWsZ5G51A
          9lGYK35EmsQPvWW2qXaUNvEuTGuX6uS0tgllQZuW0lAZ/HHRvOIG/X4IBEg3RNjcYzE9LkQ0TUEB
          4uabap6jRg6gidtjZ26WzKCYVNiB1xzoVlHogU0JKYVMc0AbSOPdWAeflpo92ADmlicUvByv0OUR
          Y2JjrrbXQ2fj1qdKiq5V86lK+pQYUyFTo07gRDqMnDDXO9Q1DZqA5yUMHof55iVvnSFra5a/E7dj
          CvvHhQKrvfMsK41Tam0Ey5b5MjVHELo7E554o9AS4e5wngxSnUQONANS9Vymk1leYTldFj/uNOmV
          1cn6WhzVoSozFbA8FKCGJ6aV2rFROwiEhzs/lsMmH3zRy2iuWBUdAAaRDZ4dRTudmskWOGWBfJXO
          ga2ZI7NOtRgTaoogUESRhjZKuHyP3fwPz8nhvYfk8O7efP/m4jGNYfb35rf/dHjvwYtnB2TxcO/w
          Ho1m/vOXNLShSQ9ffH1AkxZffUYjnFuLR3fSfE1eO+zkwStxJ2PN0r1yziRf8+x8F9qFLlmupykZ
          ouJYr9MOW401PI7g3REBvofquGHBywQ88/nPDh/YtajMyeWW9S2ywhGTqXNlOd6XkGJIk9567ln4
          +DOwa/Y1Zl5z1k1F6uBxoXWJ2lZKZENDAos69GYeyHFCbTHQtlLTgTZHNwAC+ujp/L+fEUBBv3mw
          ePSALH72dHFvb/H4JoAgh7eezR9/yUANBn4AIjq//XR++zswEt/uE0q3ePh8/l9PSdvr9Row/F88
          u0ltRKIcCQmzVQ0WUFPqsaUUR90xIuGwlNhERX6wPLZMJqCdsO5G7W9KLnPdBCKhaiV1joMnbh4+
          dzFRhL537RjTs+Dt7MqcKChrnbaFAVf4UHehX94GRywExSmTUCk8RXPU2ZApApiihzC0fWTmzt9E
          CcmtyrYRjrfSWkna1lrLArMzy2wxyWq6bgw0MH5tXS7ZJ0BA4PPGMIqGfScr6tA6lVxsl18m1Vwr
          Ahtyt3jGKgDU6krkpzavmmjeiqNx06OxqYk5x2RDhQBTXQqf00k+VYRRDLMlt45nQnBMHrCmTnt8
          k7Bd+aLT4BsNQJiw8J19sDVp5IfsGCh1bq4WrG177FQzP2qQDmRU8D7Wmp06p8ozCdmbLeApxJHN
          sswKloF+zZV/pZIW26TOxWxcisMV6UNAHCVxqv8PKRrpkCRkk4/B95CNOpHud1AsVh6RPz8cttgJ
          JTu5440MFB0epegQ5oE6btJPVNFZR8BnquZTTM0lWz4tONs/ZgcZwEr/KMjqDngsa409DuuNPZo1
          zybOiOHhsZe35OPCo5mAXmGntXHXA4hYv7phT/mI7qeGS96qMS3BTVHYLlR4HHujKBtxMBbPBung
          j7DztjiJpmwOJkrfrErFd1lAe1LQXsEGxangYWemaDF1spIhNd5cWWkHO8lS0C/zjFUI4/lElFYI
          PCxslD2TyyQgm+FTWpGPkM1KqZSOPoXHoTGiAqjt0Z8UG6Q/Tt3gVUh/g3jYmh65YgNVs3zdiuiM
          SZLobXESDDpJuAU5gA/TM6Hud5ZfwpwLWm04j7lSM08YimRvCsnr69YJRJUdTmtaJwhVbkhd37D2
          7eQ41sDQyDLcNULjrloa5tDQMAfWHgemFtPVWcOcURRnqu7p2OLNdHJVhIztdgZbdZ8HjSZhLSMt
          LJ8fHLz45m8sHv/tv0Gg/eLZU/L+BcI2HDAoLq2AOqmtOwPcRPuq2mZgkzAXlkrVjW/HTD1gRalS
          dqs4LV76iR/lz9jxV2y+9IZxtcPOt8TL0Feaw9BPW9uWl8rAjhN2acQSv5JH3uRwZFWHe6eWaa/w
          W3dsvBIeHlG9Rmq0tNqx+4ohh7t+2POwsAoe5TKLw3eiabjbriIOccJP3mGERDLJVfjmlDUYjiKZ
          5BIpGl7zXLuuZQuo6V3OXr2FZyN9ztM8fbEvaGrHuPAUXZaArYDnq8vqWp6VnthgsTXTNXvpj9UH
          MTOvgOQycNcx13FXUzJ6u1KSXcBrV0UXO3gZW/GYch2/kQOOZcC3jcPiUY6ZMOvAj3bYB0aluQDF
          j+4h51S0ItjmciAZ4+C/Aerj57ATpf6QIFM1FRZAIAFtJKjNdLWaCfsYG+a0nXBs82wBdsg9en5y
          /pe9wy9/VYRVpsX+zfmdz8ji1pPF/9yN15Dmt+7Obz8p68zmv3h2eOsZObz/ZP6bhy8OPtO4zw/u
          zn//EJalFve/IPPfPFn89uniwRO2V+/B54v7f55/dYfMv32WYMnkUEsFA9JwMEwg62ny4BcUfl+5
          C+hk1TRGVkk5WuaAOMwiOSSxlKPMl4PKHREjrCEYYezfJpfRMtxfdqcV7Owz4gsJfyCvbdgjvhUw
          GYOwy2zEArbxml2dZr3tqLdJv0HCKXDjEwNTprU0JIWSf/Qx6QbqvgR4sfaxC6hhiGRV4pG1NChS
          VvQfGI14jo3RQO98BFQfY+ejHNv2uFwvB43GcMB2N7lFmyrSHKLMJcIU0dkis7b4y4eJQi0rO+SR
          /GZNf+IsmQEAiNtA01DKgB1npX+24HZ+EiwtuRYYWTWDj3l452oLL02Q4miEqGpwjHU/4A7HZFxV
          5JZsy6110tQ5EDZlxKTVEmaqY1krRyXhEWYTKQIHjGXlj3A5LjxHvyDXnct9Sa47D35RLpOJBkcy
          edcddsCFRMYoJNrTkoQJepmoMmqn5EYLN6gIU6JaGVbXI2YaQFZGtp2EGmVTtYbUQfHyAprwiCt3
          c9Pzq3lzk7MrfHNTQ5dnEuMxI0s5IrKOOCf6gzgpico6MfN8IVSswBiClFcDj6B1KZrm1q58GpVH
          i3JoTra2ODXkKNcQMSCMhYhsT1aeCDPOkijHoAoGdoAIW4gG5XHwL3BBMD/kL6oRDBKOLr/Nxmpc
          yvU2HhxW9gAMQqMIzG9nqLVVRpobr/awNSchzK0DuPStUEEX4OMZn6g2oxO/YjqIWQYYzDJQW1lo
          8fyza78sYITLjIyGayDomttm87bkM9SMY9beDYikeNElqEktZe+5bIjtxeXcGS6hYMoI25nLm5YD
          x8H5ZCDJPKpzxyA6znJclMVOnCLQsz3UuAZaEoE7IOIrDu3lf9iXrpVuHrUFpw+OYweACYMpbpR7
          QT+Ae8DRI376lGBcEx6yG1y4spNXSWXa1o7fsSg1JoDdXjhRo5egqsVUyYqPOSDGo5mwRDolmtVV
          aeRq7xs4P9hbno+dcfW3g995ODqbi9/5PNW7xKaifAzt28TNYVBBB4FEzzOCxn+MBbn/FBHw33U8
          iNp0oMrV06jD1aGTRwjpqzVXMi0I8q9g6SGbcjZQ1jzfqbVUXTL011YXu9s79qsGqgnUhUvbuhiW
          4s8waOytfR52bExNfCo//WzlB7CZAdWLn/8yRplPLh49Pfz3L2HfM+DKj57PDx4IUBrQ6MW9vfnt
          mwmEWcoJbr0dRN7FYIDBZKwHqxtraDekpHWg+3SBNGAv/GrNGABa4UdWeNgEfvvJYv8hbed3h1/e
          Xdz/YrH3MNl2Mv/Z0/lfPmMi+HIPjrsfPjqgguPH3alM7iTY3T+AcyWLb/48P/iaUp08/N0d/gn2
          iv/+IeO2/0SA97DO/buDF9/dgVWBw//40+G9P9rSvd4NIv/d8D2vh0lXgCTV06gMQcsgdQ0dBJCX
          /QIHGyhVXbLqJpOZh+kpH7WOoZWSxnThNDqa1RIpG9bML9/YQGrUYFvrrl4fvtn1BgO/55ZJrYLK
          pFDgGrkOqaIl62v4Ameho5E20klDjLRoWzy9P6ndZhKmf8125bJMbOJ/aXZJVJA1pFbdcHZureIw
          11vOwRzSTmWyXEE7vyGTa+mze8JB+WHajSuN0AOHTKDdp5ztbmRMYazYfDMR4tG8hIYLyaONC1Ma
          x2q+4ZZJrepsNJ/W0axKJtVVZ7iDQyBsZcpuN7K03EUEZk/TAINDRWA/EWGfOuqTtestt9PeVoza
          mYzS3fVOZn6ne+5yuRFZxzfWWTLzcnk7cCo5eZ8EYj8bqXfW5RauZ9zykFqSgM+PK34vgY6nF3U+
          o1Hft6NiQ4EcjUuUKn/zJfEyPseHvI+Cvn+Vsg+9QdNHbmphWJPxwzRj9v/r5i+rYJvA1MTP8qiz
          avBLVJVV92E1Ixs/hLgsf8SGZjeqjR8kZsK1j6zp4IxBrHmT2I4++2zWUaRvydaQn4KVjR/yUee/
          Ug7mylvz48O1aQWpg8SW0HjXLteJLvgtdXCwWqvkPS8sbpTWj/mIe72RScpxWpbdGSt+GSTteGy+
          LWrwpF16Ih+1I0aU7MyAgI7YUVvtmG2aqPhN5ohCGQCEkKI9UnOcrRIlsZNVVj3dJ36cB58s1uKM
          0pF5YyeHbO/apSYQ6fQyjlAnjk+Horgefmj6e/Siuv5LGANE2bX7MTKkoZ0Nf83ZMC4UaiTgpvZq
          G6+c/LUxvsnXFqO4yw7TNOqMoa+9qcvldA9Hixc88e97etMS2UV+UeHGif8FUEsDBBQAAAAIALqB
          E10HevJtOQkAAPUqAABKAAAAUEpTS0JPVDQvYXBwL3NyYy9tYWluL2phdmEvY29tL21hY3JvL3Bq
          c2tib3QvQXV0b0FjY2Vzc2liaWxpdHlTZXJ2aWNlLmphdmHVWl9vG8cRf9enWL0Yx5o+00rcppGl
          lpXk2ghlq5aK9M1YHpe8tY631709SkwiwEWdl9hA/BC3DmAVLuo0TwUCNA8ukE8UUt+hO3t/uHe3
          dzw6bpsuYJPcm52dnT+/mdlTgJ1jPCLIYWN7jB3O7OBBeNxnYnNtjY4DxgXC/oAzOrCx45AwpH3q
          UTENCZ9Qh9hdffIwntxstPLXJBQRJ7skdDgNBGV+ad2I48ClTmgfYOGWnrLQviW/e4SbHvUYCwxP
          JpSc5OXJH2FvQnzt7A/wBNuRoJ7d5RxPezQUm+VnO2wcYI4F44aHt3Do7uPA8KSCm5n4gFPGpYC/
          iUgkNbwWRH2POsjxcBiibiSYyRKInAriDySB6eHHa0iOgNMJFgSFAgvJcMI8+emRap7Ul6Q+mNm0
          fkh97CGP+SO0c+u3dz64v3+IttC19zaXEB91D2LSjY1lpDd7t3cSvhvv1hAPPYZFQr17+/Coe2dn
          D2S5fn24dNVh9+befZDp8MPbB2rVO7WrqC/Qfvd39w+P7t39YA9E+3lBPzHd3f4D4gh5DudY0vjk
          JJmxWpsG6sS/0RhTP/0er0p+WbGb2yMi9iVN/MtqtYx751zoxj13KtzxLhFyd8btIxwo399GAgeK
          Am0pHumAXfMctq2F49uO+kr9UU+ayMLoyjbC9iAid8IKaaSb37jtCzIivI0Kwtxi3uAIc3mqbTQg
          IeVkAFOhQaQkvKQwDbY5FJwdk0NpOCLFcwSdkHhqNc59xjyCfYRliIwxQNeej/seGUjjCA7haaKm
          /k2PjlwhiYbYCyuogmgcHLBQKGYGOhUBMujFTY7HUruSqtOrC8UYIbSTJ3EPY+G7dLBZmC3jsx0z
          0WbkTjBTXBqH0Kl5epoIC0OTyoqlaK+ybzvdKf0ybWmHgyFcGtoUVKkfMHsSs5FPi+fIKE7lw1PD
          /FTOTxfzZ2vx/7EZYmhOrFCJo9K7LV1eTuS5fQ1eNZa/vDshnNMBSezMIFCki0xkTkPMT1juMN9X
          8zm+YQQIYSJayJ9uCg4sj1e3d3y4ZGNpE6m5aW4/OkTWgl/MsKXv4EeepzlBOPUdlzOffiQPZAEy
          lqyYIJLtyBDhutwwdIAwU+Qi3UxiDk5NC7oms1NvGsyuNBMS0S2Cg5WGOIl/52y0VAcmrEkYabpM
          9b9u2KOZNptp9MykHk5+H0nNHEgEszo1uon6YyqsAuQrOOs6cMBQGUx+Fr0qmQanAh9qJSGzki8p
          7ZSUaWAFI4+zh1MJy2Pbxz47omOSpQWDiLZUcojWUzlrjIAHg67n5daVdN3A3SsFcVXerJFkyDgq
          GmORf5GL3kc5XiYeJbmCSFiuDXDuGvzr7If5UpLllDPpdCo1DoiHp/vhasEFClsk3oUz6DS5xLzI
          8gW5tUrNDiT1LogjY18ipKyI8rsul6u0bwGbysoEaj1Yz9qyAhKu7O1OrU47006NRmMOpSJBKddn
          J0sjISYvYF2xFGha/CmPKy7OWrHaGjZMKuUF9XZOzmZekeaFCoAgGRaXIGVFVF6OuTDqsfusvKWO
          YOtQKqJLlxIzXsnB2za6tnH9fqfTgX+9N5OwsH8MPVuFYlpnUwQu5WSubDE+kjXeViLn5UUj+RN0
          LROxsPTEhabVWs80RMO9cSCgNLl0yQhYGWVAyLHVipsVdGMrE6B6nawcpdtI1jf0pq8C50PAeGux
          G5Nw36rX3Fs7TGbqn3VqbVuQrkGy1/0ZfCpfY2XyGuImzU4GamCkvCY/pZSosfy47DQK2KBN7xT8
          ohnIqtOUtV2V6+It6XCo0NCs+ysmlDQxS0XPcPpar50yv6o5vOT4Xq8RD+pbaqKNNq6bVhTzb+6n
          nlEVlwKDYm7Ulhtat19F1BsQjvrJZ4wG1YS6kqpbd5+cihKw5NoZkbR0OyzygVR3C1Xx6A2x9DhZ
          5RSTRd5HJ9iTapEuYcoS+l7bW3lM6HOCjwtOWVdubSURwMmYTYglv8s6ylThuWlVByGy7trEH8hc
          5RzDz5pEA3epKEi0Bz9MfhnYsPkRU9vL9ho+io4Q03nUBzoXqFxFUyJq1tEXbmD0AbvHKrYd5gvq
          R4lZrKCNZFWT5oe2qstMIiTuB0icrCxW2TDArVTpGiu9rVSk31Gk8yGcNTmwgY/mDpcvF7AUEVnB
          le33IzGfxJj8fWkzZb6x5dKr3HZc2bZKjN5Iu/8trRXo/pOK+unb0lBVLq9wuQbdYQxXGT5WZNdV
          IRLGalargyAVb1mIVaX1NwsHGCtYGkZFDiyhYj2XTOx2I7JOM7IsJBtRK6espSx7rJo1VCVVwQuj
          UaKB8YOTDYwfs32yZNeIGhJivXkae7QpY8LIsqZrzJluk4x5VhZiVRCL2zLGxYpvpWCYUC69TADG
          EuXUxZzpLjHtgT75BNVhXNmtm3Um6T4ZPus3h9BVLq3vYaQ5pbbrTBspgfdDvR8xytTpmR0QRMo6
          INV9tnJdTG6Rsf8fRFzdo8SdlT1URdEvFm9930/eFW+Wl4YCc6EJTysiNDmk+QSL+7LeorSUh0nl
          atUeYWnOyvIVHE5GBHyU0Awsnh3eeCuY4qHOxZSu9EWVCHv1Kpqffzf75jmaffr64rPXs88fofmz
          R/O/fYfmX389P3+I5n/8w8WfvkLzz17Nv3w4P//24otHs7++QPO/fDp7+dXFsxezx69sE9vdux/e
          QfPHL+Yvn87//DS/y/ffPEQXT57OXz6bPX3+/T9ftuXjb2effwn7XXzxZPb3f6D581fz89fzx+dy
          MQg1e/Jw9q9HVftVKSX/Mr/+6qVhJn87GWJJZkjcuZ4odct6quo8Xe/OFShcKB5zvbZstoseq98p
          vNP8PqHBFe3itV3llbzg08Kq9HKawd9gDGgYYOG4iTXNBku9Qn1aLbOuNZ+4R8LIEzvY8/rYObaq
          gB1G/vWqaeRfuUJ28wi8vy37HxqVpuq2htE8C+mjwRvV5ctkzQCvvqB+aLC2+g2taZRToD5Mb5fM
          XN6e2eDlt+f9X5rtf6N646w58rS3brVopgo2ZlRVc4WuoMTliisfsw4rtcIXOQBayDqSQp9AaYjo
          yGe83ME3O1jDQ9UfKH8Y/SDv6q8k1+L/1UcWRoVwKf9RplWeQgT+l8c5q+UFd8icR4H6c5uztbO1
          fwNQSwMEFAAAAAgAuoETXT1fWr13FAAAXWoAAD8AAABQSlNLQk9UNC9hcHAvc3JjL21haW4vamF2
          YS9jb20vbWFjcm8vcGpza2JvdC9EZWJ1Z1JlY29yZGVyLmphdmHtPP1v20aWv+evmPqHQk5i2lKT
          No2bFI4tx7r66yQ5aVAUAi1RFmuJ5JGULe5tgNtdL9Dd9nA5ILnNLZIgxXYvu8AC19vNYlug98v9
          OZHyP9x7M6Q4JGeGVGK3vUMHiGNz3rz35s37mk9Hbx/qBwZp2wNtoLddW3M+8Q73bX/53Dlz4Niu
          T3Sr49pmR2vblm9YvrbK/q8bnt0/MtzlHLhben9oeGqokZ+pP3B1p2e2PQDo21kiA6Nj6lptALxL
          6rbw56rdMdq5ADWra+cCbZpelksOaN12B7oSYms4EojLMnxtzzUz321PuzE0+x1RRdU6Ml3bGoAA
          M9WOax+ZHcNlNBu+7RrxWH6iH+maaWvrZj+WG/9xzfDarun4nMij6tpOddQ2HN+0rWSdBZU3At+4
          Mex2jVQ7HFutAV8Ate4bKSFRkKFv9jWsFHzetNt6mlNaAerTHrouatCK6+rBjb7dPjStg78fGsMc
          +KY5MPYsEzXcGe73zTZp93XPI2vG/vCgbrRtF6RH/vEcgeK45hFwRjxf9wGwa1p6n5iWT3b2mq3b
          5Bp558rScj7kBkC+9TZAUtDFRTK+f3/855MXf/uajH/5zct/v//iq38ik8dfTz57TNZ3G+Pff0sm
          T76YPDgZ/+GbyTOoevDr8b+cjL94TMpLXccbP/ucTH7x8OX9z8fPfqamDtiAdjmPyRu1Zn2lWUXQ
          1pWlpdbSkqpF37YOSGNla3ez2tqm+LFB9G+TLCLZsLMRAtYytHbSjqw+C5IdzvfWXX1gXCf/gH+Q
          a7RNVCzjWNTieqkyn2LgyO5DF/oG2bftvqFbxB1aFjQA9rt63zOWxdC0r6AffkNHJd72AH5pM4W7
          2XMNvUOObfcQDSBRF3sQ6DX1Rpla6hjIgLkHvjZilVY1fN31jY6YXxxENHu76YJHB5iFchagja40
          MsFELe2lhwS2vVQV+CZCnRh1UnwN55B2dbdt9JMOhDjdTgpXQouY1dGxDa0Ny1QnP/qY6O7B/nKq
          hnLq+N5exCcWiqQUN7rIgc1zyLH4PdPTEAiElCQwraXtoDokE9XdPcd+si4x15FwGqWUevOkKeLw
          e0qHsYQ12oHhrzgOYNbRz4b4SvPLAtKRcphenWlyiafnGv7QnSq5qL0XWO0eRBHzJ6BURzCQTAFK
          8ymBuPaxR6auH0hM680uKYUE5kOC3KA4ruHorrEz9J3htAtcBbWJ0jzXIrZI3x0acYNQMeF7I/B8
          Y6BZumWjG+exymwUCzNM+IrughlrKTMEOEJXrwIPm7btXMxUz+3+XeODGzvNhWi056Yg8xlSWijK
          onK3ncTgoWDfkEs247liLXODlLojqrD7b0D/h/1+2iA4rj+xTatUuby0NJ+0iruxDRDQzHaPlGqg
          ma47dMAjxbphHliQbnSAwt2YJ7Bb0+tNRzv6TKXh9ZLqkZQUFY6NSUVytGjaR0z8mRynei/we4M1
          wzfa4IA0apyY3JEO/kZBZWImP/1pRiqUArnGxCYCoGgjgLRco2GLhRjrKnonyz6W6fQUEFKFyZf/
          Ovnt/athwCeT33374uuvyOTpyeTx8/Efn5OX90/GTz+dPDkh47/8dfLzP0HmcG/y5+eYQ7x88DDM
          HiaPP0/0OmEsb6C1kDffzHSPcbiQNK334sg/S4+T1kkxc/1krrtLY0HWOQ70QyN08XTMmdx5OcXu
          XtB8S/d7MLkZZU0+KkubWXuPSimSQuiF5iG9KWOak2kxn45IpBu6HMY87d7FMCotJ93oGzS50Ziy
          d+fTkmW1jt3vl1KmmWwnC1ZxEgBijsV5NlYFmYZ3DD2nqDCi3TY7fo9nnIL0eJANwzzo+Qndp/xo
          u33dMogjGNZpWwrileY/WvqYax7PSMi+oLWDLVl9giqyBhGv4buQTcna1SOATFPHHBl9dePdGCTd
          HAbHHorSA1QirGfTjvNsUsH3tgv5FiZAJMDYtwz/vceA4NcLF9LqROXvtu8IKGFhBgOhQGoUWGAA
          F0hZbjhYAuAV4BYZL0JQXgQRb/u6JxIfpYpsn4+HKNV6KocRk8MolMNt+DUrh4geIP1QQg9LMXlQ
          7o7zZYJlhHI5DuVyWwqelk3Er6lglsrugrSadvU8r6ciGuCRTHIdJCgKC1MocoFUQL77Wt8cmGC8
          83xymObZVfBM+UbbKJnz5E2yNOp2BVxFmA6KYQLuygWw7fcLo6vkoAPb/SgIrfM2wI8+zkFN17Y0
          mITkaxYWN1+xsBwUA9vvK8FScQbL3XPiv/hkr2/rPjkcCTrOpLJIShRmHvR/OdMukLTb4Nv1uHYd
          Vz/eNC0jK0AYjKwcqCW79tDqlGjw0j4Zdg6MTaPrw7AdjuaLtkAXdBgUBq9jcDslCkxntlZuVreb
          K9nqsnBWggbNkO/bI8OTTQWo9xSF+xv2COabI3JVqDIcZqELmK49SFwNtNT8wMFUW6qSKa6ad3ar
          rfXN2uoHIp+OhRI8XfurXL5czLTeWSoGV6kszWyDxIAp32uJbWNnc+07lFphYRSVbrn8fUjt5ncr
          tcLSAB0qBnjp8itK7Tvr86XT7jIIcfYYl53lQ4ypgybIOyGMNVHh/Dvq3qgsCwSSBkFZFgpkFCqz
          UqjkUaCDLZrw8n8qEgKv7RqG1cDNHFGijalw5mMU7/On74qEO79xVLgVWNzaHLptnFMWUjMs2G7N
          9Jy+HmwZkFe3Z2p8jDNkOjH08jX7e+W0RyfqjFX5vEW5NpJRCdE8FGeNZ6kSRWZzP6pEocanoBJx
          furrzkzpaVN3qkcGJJjQUJmeImJ5diqasESF85a5QgEqGkzu8xcKeIeYD344mnmNoC2aS0Vl1i4F
          s3XpTpEuBTN1ia7wusZAN61t0SIvz21naNAVW9XKelRMpjqriunJlOp18tbl6S63LBfEJfsHJ5Nn
          PyPj//x6/OTh5Df3yOThp5MH/z2+94hMnvxy/PT3woYRF+QalzddWbpIypfgB6Qys2ZoyMlnX06e
          PiIvP783efqAAFOTpyeLk//41eSzoqygPLt9s32oHND3Q5br1TUl3NUQ7vZGrVktnHytmm67L5ji
          R0WZfrVHirpAXveOvCoSzyslRLGr69n9zky+bgMaNHUXnDXpKX0dxXz2zq73/83V9X4Aju57U/h3
          5VXMaG/Wq9XtV9L58DACsJ3c5p0etjE7JNx4T+yDH/fwCE4p3qIl4T6Z6VUHjh+UMhtl2Q1wLNPd
          OGkPuQ223AEtLxWYfkanzLSt2uZmrVFd3dlea8ym2eAourLN5aiAtkAmS48BCMIDFkwNTYs/ThEV
          gbc1LDyjlNhIpJDRrn8TT4Po+zAo/FZ/jJBDmxjcEG84DsVPmOwHvvHRxyQYHgnGDk/vNO07wyP5
          kHXpSR/5aNE1aXX1Rs6smJ2nUme3uGVjOcKdPXomTOsYVAFrCBRuSpZpmpFOkhka3JlJawS332la
          Ek1nxCB+8IQoyswuHKWlOjJiWhr4KN1Nb0iHdXioA4ZNpNiMi0yHpWKmDMpHQWGMwIDWN6wDvyeH
          6bLjXgr8r+TysoYpsovkUSiRWXCnbnnD4FRPpFQ92/aM1Rgmkfpyx5VJdyBqz0FoEOyA3Vt4tjDE
          JQ+1XLOt2laVrpveqq1Vd1ort1ZfzwqVBga90DzUat84EGkSz9gH1Tut1Z3NnXprfae+tdLM0hWZ
          9etQu1FrtvB0bZZSeOz2VKis11e2qhI667uNU6FRC6nUtpvV+q0VwakZ8fYTtXiZnlHlD9WsSuOE
          eyNoBo4i/1ErmlJVmPOBoNg1D4augAbIJNstdIJFv3KdgqC/Xru5V8etqpWbrer26s6aeLQZW8JT
          g/wB3qxd80dMM7lP8vYC6eMPcWTAAyZJaHUelITVVjY3W9i3VXGKk44CdHKjuo0BvYUf4ikO9gJj
          2BTYk5w8oOeqEBGmi0yxEDJOiDItoiO1+lFbcLgywT2enYCU1JcwSekjaWC0MXTwNoLRQaX2sjkr
          z++Mms0XDXII4LhGE7NV3TNKvpQUFtbJ5EnbjEDAKg/F1XczXwX5JB0CIKSUenLoNfrbqu7o+2bf
          9E3Dg+TTUS35RHLm24AI1S4kQXx2gYvymunZoy65SnnWuEiSOYfOi6ir2oyccqkQUW43sWhh2KP8
          3Nm7damy1DAGJh6f012VpoTTt+5rKML/QdmchVzEf+VMr9LT6Jk7LOjcet8Ymft9Izc1jc5nF56y
          hY4RQtlAdGoTA036PpjcSucCKFtbnU5rY2Mw8Lw5eZbIroppe9kINK91GRmkjVTBBS9nGLbEZ4+j
          Y/+tOcGhOtbJ7Pc5beBcmktN3ehtPu1Wtd6o7WxrjbUPMI3CqVzl3bSSpa5YkrZso53b90m1ySx2
          J65jkiP2nzwZSIBnkLHmdJInxBDfPdTozIGFd22t1tjdXLnT2oYkUjySOAqJilOijK69hb5dTHaO
          3p1axFE7C+r16uZKs3ar2tpdaUrWE7grnSCmenW1uVO/09rauVWrNhTHOSnzi6GOngnvtUZrt7q9
          Vtu+KWa8rCQa3RyT6a+rmZZnuEWyzQxrxRx79UOYq2yvYH4Ks5btZmuvXlMv3zFBFUpk0a7jLsoX
          S6jDpHbFzecVbi/uMGHygWTU7BuduUyTzFpE4k+n25FL3nYMK3llTz0KUUfV0ptzj7NchpxmZEf5
          Oz2xZXv0inJLI5FJEfhH35uSYsYI6P3OnIkXvQSqHoBuRy36GI/GwrZkbVJUtK29D6v11s5ec3ev
          2drard5sXZINY/SrcPcRZUE6pqq/CKLuKRfXqiPfcC2dXi711swcEUVF5U6VCBSHoLDMCV3ttLFA
          xd8AWWiQbHm+ZOqH9YND+Omll1IFSkm6+CNHtIDrIo2kZ6aIQIVeVd2HZGPoG7s63u/5gSmnNLNl
          S7PRXN+wOuk7geFyVeSXMvcvESbVjH5WLPNjmWGpP6IiX+6PEX4XC+mKquIn7FS37KJSypzZIAuF
          VARL7g29qKiORsardzf21tdB68Klu7XWznqr0axXV7byg0n82/RXHjEdp3idSzxLEjZIxJZwexSX
          cES6KL5KhiWhicwa83SHIe3a6iEEqyDvE6bPMNEXn9MWKTrlVXIbLZZDbXt9p9UER75yc6W23YKk
          uloX7k2h36UWKljA4s6Cz0A19D1sz6C1urGyfbO6Jlx25J9hkAqLemJN73QoYJGjiOHOHe87FYf0
          ROtTjGZijTlTHT8ykV0YTAlO5pW4jciO7usKIaQ6Faqgnd2NxELPzSC+cE9SeTMN10U88ycGua6+
          wsb3WXp7Dalqju2ZNPukuO1u1zN8yY47hWdX4nLNKcRELsQ8F7KZRAe0Y9f0DXa9eg2Iq8nG+qm2
          ZeyGGgJZzgvDURGsCU4jsK1a3WUC7/b1A4/IBzIqsdkWjhpyP59/Bhavzkt3uF0DuucV9K/KIz10
          J0IUdYRWAvIUO74CuVHisQbl3hLLomjs4WcExVYyxe9UsLxreuYg2hPDQ0FnSiIcqNOjknClEvfD
          cnHFAYvIXSe7Hw/fKbGZz4JAPKfJBa4BTHnACXW7b7/aYIR5O0UVtw4nPamvdOVBBCl8ZgmL8Hkl
          4cp58mWT1ORCsQwsUpXp6hI3TAkg8Ym31Gqvwr/mL/bSzsvXDbG84tohFuHxGoFHlS90S1FrQ6eD
          y/25brzYyhaWo3wQ8akAEZQqe+P/LHz8Ltbk6Zokp+IpXQ3P1klO0XGPaWUmFsfZT73sp248v0/b
          QDc8uKQ6ETLjZp5yAy/RKtxFY/2uAVyJPRl2fJH0EusH018XF0m8UUrGD++Nf32fRDtok9/cm5w8
          wi/bt8oVMvn5nya//aPGt33x9VeTL54TJDV5fEI8QLXgMFzsXKSLdwTGJ7+b/NtzQEUmv3gMTcb/
          /JBHMnl0sogPAj55SCbPPx1/8fh//jb+y/Px428B/FcvvvnD5Nk9RD55+ujFf3318sGj8Wdfxkwk
          uoxsZrusUg7a4rW0I6sFqCDsuR9yTM6TXiz4kLT8IRQKwBqfJ2/BZL/Cv4RCH0Ex6esfiW/DI/xI
          m+W8m9ITvpkielnkWPmqiOjEU1RQdPStiGP6ToTkYLvqfm2pTa5fJ+W3FW9S5D2WwVBcycEgej0n
          Km1100B1ML9UevttfMklZ3cLSxli43noSj5k5TIA7hdCCf1mvb8AUhR0gL7mYV64oHrEo4S6OI9P
          GQ6cUhDIMvJSAHIqz+OSonI6WhrFcMrHVIbDnJvXpdLCW1eodIstn71zqaCAsZTLlYJSptAJSVeu
          KN5iOVIlKlhKJUa7aLfeZd0qBly+cvq9QiUCz6PWIiwJTRoOZfP9V8N3dPRqr7nk3NtIBAkaSc88
          SJx5lOCCBP89Dh4w3Oz/RXLpx0DCo/gxkPwYSH4MJOQMA8npxpEfShihLo4SoEMneMVYvsco2Jic
          vu+AT+gAuimA4h6O+ImXMIBlQ9WonP0WCL6NKgI4wbf4eRW+89O3zfSLSBEpIEb6P21xEUx8WQ5e
          CcErxcDLcbM88ArHTBZcJmDRrVapiNO3WNk93+w3t6g0EwF6waUR+hpx80M0wo5CWEWQxhVDfNZx
          BGaM8TiQ7WGR64owAP4Inxk8P/1N4eQ7lCl0YlIX7xk5e1A5Ozxt7I3iPjGFCbDHOTDC6/JYZvIo
          7KdYu7KvAH635pv97PfM9qFleJ4wse2gblFfpe97pVEFhnvEGxyFCXiYAGGCNIyHeEZlSCIBx/uk
          TK5OF6enIIgmQJBABmK4uEQOPC0A0WJHDKZGYlOLmvZWsClqU1tTQzDLytTEVEZ5VCieUR4lBiWh
          huV1bQbG4gJQyHkYlwKdpdUk1REcD/AF6SAoicSlBLQ+qIgcnHA3MaPwRgWGCLMq0CbBGQ+ovk4W
          OoGIAOrfwjWqe+kqlOc1UHM1eYb/PVBhGfoLqN9Z9AFDH6TRJ38TeZ2MosgdjsCPFI1bdOigY0ui
          B+hHuHHEHlYV1AayZkHUbGOGJ9z1/Ldtw0c+WcO75/4XUEsDBBQAAAAIAMp7E138cZFlUA0AANEz
          AABAAAAAUEpTS0JPVDQvYXBwL3NyYy9tYWluL2phdmEvY29tL21hY3JvL3Bqc2tib3QvQ2FwdHVy
          ZVNlcnZpY2UuamF2Yb0bXY/bxvHdv2IjoAZVy8zJRhLXFzuVdTqfEn1Bkn1xU0NYUSuJOYpUSEp3
          1/qAvBRI64c2QJu0QBH0wUGBvvehaH9NX33+D539ona5S538gRLOSeLOzM7O187MbpbYO8Ezgrxo
          4S6wF0fu8svkZByl+9eu+YtlFKcIh5M48icuXi7dTpT6U9/DqR+F+1cB1Oc4DElwJVwbh8BCbIUb
          kHjte8QY86IwJWHqNtlH4fBgjmMy6cVkSmISeiQxIGcxXs59L3HrURCZPGTDPf+MBIdRvMDmbDDJ
          5BQmcid+sgzwuXvAP4sWZsA/9uN0hQOBZsAvyMTHbnMBxLaN9QmeWGbjEMs4+pJ4VNxum77oZb9f
          G6FoWVHiPlj5wcQ2cATfAzuOGBrOY+DfBtB84Ie2hQGHax8GwEjS1A9npnLXPjl1H8Z47aemVNlg
          O6IraqxtRsQAHsMf+8gxcBWdFgnj1J/MSAoCSVOLiMVoyw8Jjlv4PFqZ0wuYITlLrUzI8Qgn1FuX
          q3Hge8gLcJKgOl6mq5gI70FAgoSTBMnfv76G4FnG/hqnBCUpuKGHpn6IAzRIYxAlqh/VOp1Ga9Q8
          QPdQScSEkcfJlvaL8f0wRZ3usHnYrNeGzW6HU/ioChyqODmTQkvFHFU43TPQOucoKqjiA8hX/UEF
          0owNifVI07MASpDMfjUgzQTQqW4Q+jLIKYrWJDa4luplUlwluQmM+AUjZJroJPrz83S+OCApCDCK
          0UR80YEOyHg16xMviql8YvElN906CkCVAUHjKAoIDhFepVEjxOOATECLabwiOQyq7sSLCQmP9wsG
          jnIoQQT2NV0mgxTH6b516DDGC5Jb5TSIcIq8VQyCSA+XUlI/74JUYwgDHJg7wRr8A8EGBGpNiVMW
          9k6fZLWEgLEZElT4RCBZWCU4lSF2R7pAqYLa3YPGqNdvPq4NG+X9DF2KHSiEoE5dKY4CKGUvADXF
          OOncT1SmPMan2ElVKgmVHuxHZBZHq3Di5HyugkJlh3VKl89fvPrut+jyxbelskZf9QDBkeYjTgYq
          n1Lv08FnD7rDmyLIlCoGCEd127XPqaC6/ebwSQajrEGb3GUrcsxh6Ykac46OCzprRRGo1tFWJ60M
          cAfnSUoWrrCfob8gbT8I/EQzAX+KHLmZuB4OD2J82uVem3DVqLa00Y+AUZm/uMb/Fhsp9ZAoZPzV
          o8UC1uXwbIaOwEeFQUwDPEv4Vyag5kRlgTLModE9kM8qCNCzZ0owRe/xt2WwOhBXiAbDWn84Ggyb
          9c+eqAsHAjFJVgGwMiEgLk6UyhV4apylMXZKGwDwgj1VboJvDnCAU7yvcciyAvdxoz8A43QHB5+N
          mp0hun8P3b6dl+eGhMZED8ceCWgc0nihcMALn95lW5+qAkSChLz9BJpWtYWpIruH9qjsVfpS9joH
          SRotBySYqtbCOVM0BO6cackyuT0jQ4vlAt0zvNGxQ5dZpGNuIfICp904aNbAZbufNuoskAwa/cfN
          ekMPk5lx3aMTUunlJlDkUlEEYqfiQgjzgYm4joNgDOWIGXGo3+emcDPovHjlo/tc/tE3igGopJDQ
          Np1tVGO8MaOiHs/UgLiJ6nwr5btQnyTRKqa7T5kKWRYVBDI0j76DBDCds7ok2c9RONqNwpz4s3kq
          SWimLTn5WFLMi4eGDBpYtd3fXEeWA5jDlMnU7ltAW0iL0iCQnjttnM6hRD1zPrqzV8kmeB/dKis6
          URCPDMTbH2aIRxJRw5yQMIFKARAzHEOJVSBivNxB1IL2wdKnU1uVryStwIKSzrrgAM0Qwj+kIiZH
          UlDFBmeOKNWs23/4oDa6A48JdtvKp56EA6uKM/P9UM/ai1OI4gziTRYlRGwO6OW4+7jZHz6qtUYH
          zUGvVXsyOmzVHo5qj4bdUbvZ73f7JgFFM1S5g1U8xaCKsglJA/4beb46RULSbsj0X1tjn+1KLRoi
          Q8hvYm4fN+/n3JGBcyqI7zsKcfqk8bklwEkETtbF3lcrPyYt0GGSMpK2iMeyDo6opxe5KemTZfM3
          blhGWQ40ncKC2wkzJEjBRdLhlPjAaJHk0w356Dm2y+apMTtMEBaf5nYoH5mw0z4C+G1imqlVWKZ2
          84+ITbsCWiw5/0gRFQLapEO1pNRvRdtbDUBqHhWAP/YD8B/ZJEjEZ7EEt6FTLTo2tiRrkvx79ixJ
          fQSom6zGCz91hGp334rtspF1mOsn/VUYQs7vGOm9fDJY0AQ4ITcEaWMQ26GEs7BjmXi1nIBvQfma
          96sLCBKpN0cOVDTRKdUY8mch1HeG4i54pyWwunPmmZlY2U/IjaPE8OWNqC4quRilaq7YQsBlr9K/
          ylmy4SqhQY7iLliBKmzUoR0GdWqIB5A/zgesN6IX0ZZyRpG52oZgWQD9slZFKSg4a3QdVcs8f/8E
          rdFd+O8mqlqpsXRRUaFCjrUuwuj0ilJTA4eCY5mwzgpFvKk0RTSxSbCPUXVvb88SazdNESCVBVz0
          UwY/hXwjS2eqrYqcVWFmgwJC0F7L6hn4y+eHTCVF3stH3WWUpKxuvntX02RRnazJOY1ms4Dwzghz
          zlzdu4v/0spB9DEA39g0uR0IMgkrAgoC6fbl2pZdNN9m3gLTzj+swQvaOyG0V3j1LkXlffWWUmpH
          a58k74tM7PL7P6DLv319+cOPr7775vJ3/3z5/JuXz1+4lszMzl6r0Xk4PBoNjrr9YfEu5Sbz6LSw
          hrJGUO1XZdN8oiUb2EapbPaNrHW/Pf1RlJ8jsoHYoiZL0CY229hVhdtVV3r5m3+9+ssfX/74H3T5
          /K+XP3z76k9/vvz71+jlP/69q9J2UJZdSRc7OGyuF6bIQeuMQzhxtMa5pRFx3OwcdI9t7Qf1yASN
          ozPRFlRfyyaqRAEollLHPgRJ3g9VwV0QQ/MX3c6w1jKRenjCgs+tChL/TJgH2DvhXVh2huiwvy6O
          Z2MHAjDkrvyfVm7ycyHEIjbln//Oc75k2ySzmVJvULKODPxfEadaNcbafnhMGwTOnm3IX6wWRcNy
          zVXOOPswgLphPfC9k6wuWZvRTj88eE/5mQuy7yTBoM9uSYaaFOc4KfT2CxWS6h1kRI9tTF9eWjw4
          b6Eu/+hh2HUTh/YzPrhTtpaFwk4gTm01FBjfWEq/US/Zx7it7JmDVmPZjNmtRYxLc7nDrOWObiwC
          xmotxga/s4yB6usK+We3ioUsNncuYHkglxex2NuFJFVPPz5qaidBOqQp8824OJp2xKdbb3SGjf7O
          YuCEXlcS1Q+22Bvr6p0vaUugsGt/60Njxk/0o1BtQnf4pNcY1Xq9ljye6gLRVu2JQeXulVR6R91O
          Q2G3GB4FS0vlSiVTjFO8MW/h67hf643qsH2A7oo33rcmQJXyRuRZd4seJxx2648GtQetBnp2ZVJ3
          FT3QXvcRPaUYtZrt5nBQzJnaaRz2a51B6xG1cjPtULQaLOm9mzVvxUrfGHZ76Fn2q9U4HO6rCDQR
          qN7RXlHs6u0P1PNAdkWBnSR/8RTBCkPh9PzVraf7OVBwBwCMYn/mS1D6ygQUB+aUaoxnM3qFgoPL
          gerTnFezqDiMVt48i4rOukLzR2MjTU59lmWyPa8mznCSE9jKrA0LD0P2q1xscWv8MAcyqs5dq6Ko
          JL7Ye0o75nSKPj79vChLZ6BVFfRJESgXG6dLNbQVqiqgzgumFVLl1KYYEnw7oCjrBcTOsmlDTLLL
          ht87mJzpwoFqXQjNzobAOtflJLE0Y1AfmsCwYh2PE2dyVkb3UfUWPVbcvDznL7f1y3Rh8VsbRbDC
          dTa6usHn4rcKgIWtqOcb1Goe9byo+0cfezmmPlrN4PKmC90GRY4PLlQBDrawt7WjZmnNyUdYULHY
          zA4jfcZQ/Zzki6ZccskIK9opyC/FRSGQLaxSeW8KTReSTBQEfk4+u3cYN/PzcwTLeqyJsq0ozAHm
          ejgy8yo8RtgcEOx+PKDnX+amrhYAkLmU6NEP6nZKkH+I74eHpTK6YSCWfhmWLK+zTpSsPND168jW
          naKTQXKO/vv97xGbzToLv4HnTtme6ZR+4u5Np1Anwio3fT4bniPkdJ93Mks3iqcQkJYVgjTVvLBI
          q7lrSTmtbskc86ZmuS+MZKljGbNnaJvLivY8RDaNChojlrvIbrPd6/aHtU69MWp1jzW0fFizoKNw
          IS6SaV0N20T5Syv0CRfiHNUmAe+q5qmKpN8CE3c7U/AKVQ8qAr/BCysYW7Ln16kI5POJoUo5BSuw
          KoryyoVE7m4nop8YsCA7NmjReFDn18KHfhoQJ7MKc14VloYQJjEr1GCBg6DpgXDltdy+CwGehVfX
          90bsLvWInj7b8bvhLKKxgR18mBBjuspceN124/GAJGkc6c23/+PxDcu6ylt3LLVzf1W8LJvNeUlm
          183dzoB600I/KBMn8MZx2dvNl7sxkU2pv3djAqXCu5zXdhFQuazxboUqswZFqXrfd8vhiZ7HxGQB
          xNRUprgb/VYs67dfM/70u6Vfrfx0gKckOH8TWckLx5lnXu3L4v93AHemX/RLoZYTzE2OdnHt4tr/
          AFBLAwQUAAAACADKexNdbmqMimAIAACBGQAAPgAAAFBKU0tCT1Q0L2FwcC9zcmMvbWFpbi9qYXZh
          L2NvbS9tYWNyby9wanNrYm90L01haW5BY3Rpdml0eS5qYXZhrVhbb9tGFn7Pr5jyoaBQlfUlTbcJ
          nF1Zoh01uq1Ipwi2hTCWRvbUFMnOkErcNkAfFCBoDNQBEmyDdQIvEKDoW5oNNgmQp/05Fv0f9gyH
          lCiRtAS0AixanHPOnPOd64yLuwd4j6CuM9AGuMsczf2GH+w63rVLl+jAdZiHsN1jDu1pdWzTPuGw
          MreAXVcrdT06pN5harHr2B6xPa0aPnKXjX3MSK/FSJ8wYncJz6V0B1pLKg0KwTdLUe4x7O7TLtfK
          juWklwekR7HmMucbAko7tlYXL1qT33libeJpO4ym3jtc2/Sp1ctesHsWSa3A5kPaI0wziOdRey9t
          7ZCSO9o2w5mYhou34GubOb6bWr5De3ug66bveY6dt1qjNsGshg8dP+2ViMYg5GATp5GIlk1y1xNa
          QKi4/q5Fu6hrYc5RHVM7jgcENMTucTR58f0lBB+X0SH2COIe9oCxT21sIWp7qK3/vVMutcydto42
          0OrKyuq1GYZsZyE37b4kVyq8YIX0+SxRbA9y+n1OPPETTBMUf2sOCWPgsYje8WAv0kNDQAM5dpkR
          4FelsxHHQ9Kr2mAZbGSAfaQQGS0+3HfB7xOeDOJoz2inOTs3kJqNQAGBS4xD7pGBQdiQdola1yvV
          UqfVbn6hl81qs9Ex9PatalkvXEtsACiAUME7D5GqRKVAKaJ6s6KDpOqtkqknFaR9pIbBr93S2wbs
          oRmVm51qw0TXN9D6Ovrwwwlp/Onuk+6BQax+i7AB5RxMUOPSormTd1qraZidRtOsblXLJaG+UUAf
          bKDZ3NdaerteNcTOne12qWHqlSTY4sPItz6Inu7GVRt8bHgMEu8fX3+/3N73iiIW1xLQ3ZuikMwl
          xBzHA0TFHsn3qrdPeYJdkGkQZU1Goaph4Uk1SS8ANWH3WgZPVBfU6KmVdTC8nUHYwr0eWKle/ksR
          rcGffGYQbgKqe1BM7F5YM9XwW2N7u+rqZ2C5YPu0kHT8JFc86kHMS3vjl/O2hjRalFKq0vrCuLnZ
          NJU8iqQKX96omnoeoUG/I+r6StbychABPFJfwVZEfd+y1Gwzub+7wEigmJpollrof2/QdrNWEc+t
          WrV8U/xzI3ph1KoVXfxT0Td3tqHolZVsUSl3XFkBX6x/Cl/SIxk8ISyrl9OLC0GZCUD5aGGGBxxx
          ywX7JUAJuZYr5NYx26OQV6AaRIpQcCUPadCkKNiSIMtGhXAEsPw5Dy+egruqoeD00dmb98HodxSM
          TsbvRsFPL1Dw/uTs7Utlnqdpl6E1HdQolEabMHWIPr4u2g7z4pYU1gM5n6hxQ9ZKsmSWymUdystm
          tVY1b0MBNc1qY9soFPLsw0W0G+pfc2cjKTLSudBIZ2rkmobOHx+N/31yfnQf7VTR2X+Pzp+cKPPE
          mdbNFkBRoz+Y2NXFdoXhO6KhWfiQSw3ma2bo2zyIUpTxZx67eqlR2tY7TahktdLtzrRUF3NFwHyl
          uZhxAs1HFvqrCvpItKeo7jfwgACwKQFJh4jPvWmdznOVk+eqaftfkPJTwmVKV5paJupnuTR/IF+9
          zHz1Uvm6uhYmbG6+ThUqCu4kTNF0GOkcQRW9zEZK7n1XXVtJ7iemvnAMAhHhPKKBuyHWVEVydQZc
          mdVwKg3GoD1GOJdzFETK6oxo3+3BRNUMySVJppSmHald3sf2HpkkU8IgLY9mPnVmR8X4E83H0bwY
          ay1F9dQYyV3MiiEcbkQAEeo4FsE26jNnsMPFmJfOVMExxJZPQgAlJ/pYQHEtRSsBhgnSUwua66dx
          DgUVxJnOOlQLaQEzkErivMybgWMOAkNUF5NBUkPFMB2/u59EAaxcVozjLiclvwyEpmQ1/6hkh4Xw
          wrIdUkxL9zqU7qePx7+9RsGzt8HDZyh4eBI8f6RkcWTV74tL8ZbD2oT7lqemTgdaNzxUGPAgdhm7
          ns9IVLQLxeTJKrd9hTstaGEcMF8Ah+NO0QiejoLTEQpePAp+/VHJIFuihZV8zyl14UzC6S61AITo
          iIPE2SVvUZSR+QgWvZCLY4QN3i4gLvYX/INwANdtvGtBPvaxxefDWmgbH6wSzVCYXkQR1vHG4TE4
          iXFu8AmpeXBPZk9q950FnUiQTCBPxY9y9uooeA4++HUUPL+Pzv81mpktvrKhx6aZWgZsGjw/Hv/8
          NCQ/fRA8e42ajU+aW1s5LDDHCp4nvwu+4NVrNH78ePxqdPbmLRrffwdJMWHPERBRnR8dBc/eX0V1
          Z0gJ/yQ6MFzIE/zzePyT4DwOTp8Eo9NinHzjl09gOiyi89HL4N0vKPjlgSA4PRbGnL18Kh7nj04g
          RcfHv40fPhg/fKEpk01yIE62+ZoJB8/bOYTpUTxe/QO9nWb2dpru7Vcu7u1ClaLgS0YdiCjLm7aQ
          RjBE/NGBN74tyddPapZIYUYgO+zUkXiGKx21kwuuGTqtXjLLNzqtUhsASw+SOUxftkutTrkJEDfM
          eecubdc0TRO25ZNbbsY1wAKb69jb1wbUVqF2QZV3fCYuYgqilFUod2FirxOP0a54d4f2vP0WvUus
          sNuvgas/v7xS+FMwEZ9UPMlwupIMJ+lYy81EMuzRM/NCOKkk0UvPxKoiUxiN//MaHleRmP+hJ1zf
          QCvor0j5SEHwTinA2yH8KQimlllHLrisi/to1ESFStEVUdnpETl/sXBN/paFHoEVOOseb07cjKik
          mJB/7uYsQSx6UvLq84cfEtxy0dipmZ3mTbEkhKGNuItJLyRkRyrzqEnKKFzcsBKtOXoPA6J+12NY
          VabKKEm7luCpgK5Ktv25N4drVwpy6IFhh8h7qbj3RtskNob4J5I6TTMh+lMmiOWmB4/5M1sPnCEx
          MT8wHXHLFi/LgL136f9QSwMEFAAAAAgAynsTXWo4J4ZtAAAAnAAAACwAAABQSlNLQk9UNC9hcHAv
          c3JjL21haW4vcmVzL3ZhbHVlcy9zdHJpbmdzLnhtbLMpSi3OLy1KTi2241IAApvikqLMvHSFvMTc
          VFulxIKCeBBLyS7AK9jbyT/ERh8ij1VxMtCU4sykzJzMksr4lNTi5KLMgpLM/Dy4boW3LRve7Jyh
          8GZe6+sFSxXetMx5vbPlTdcShKk2+kjuAQBQSwMEFAAAAAgAynsTXal5Ub+tAAAALAEAACsAAABQ
          SlNLQk9UNC9hcHAvc3JjL21haW4vcmVzL3ZhbHVlcy90aGVtZXMueG1sjZDLCsIwEEX3fkWJ+2aj
          G4kBnwu1KugPDOmogSQjk9Ti31tbha7EWZ97LncUY6SKDUY9yJpTMT0dZgE8TsX5hh7z4+a0nR/O
          IrsDY0hTAaFksuWkRWUHFZCQLbh8Z6+3lO9pZpKlMAcWnbiV24T+4/5KLhTSGrx1T6EjhKjkG/qd
          qW0oqe4aCirx8EB20AgSV/iPwJAjnhnTzBF6OF6sRstxP6dku00PlOz95wVQSwMEFAAAAAgAynsT
          XaYcQsTsAAAApQEAAD4AAABQSlNLQk9UNC9hcHAvc3JjL21haW4vcmVzL3htbC9hY2Nlc3NpYmls
          aXR5X3NlcnZpY2VfY29uZmlnLnhtbH2PwWrDMAyG732K4HvjbqcR6rZQtl7HVthxuLbSiCZykJRs
          ffu5JYeFwXQREv+HPq23311bjMCCiZx5KFemAAopIp2dGbRePpntZrH2IYAInrBFvS4FeMQARWZJ
          Kk+RE0ZnGtW+slZCA52XctqXIXXW9xfLIHbamUWRaxqqCBIYe70r7EQ5H7ezi5+/InN2FnsegfR4
          7UGc0dw+kGL6elevsG88nSH+A78AxJMPlxvvTD1NByBgDHOOkmKNwd90jthBGtSZx9U8FDy9AteJ
          uwOIDnyX4gH+pN4gfwzjZLtPpPmLbOBbAVPYzeIHUEsBAhQDFAAAAAgAuoETXfKgLIhsAwAABwYA
          ABIAAAAAAAAAAAAAAKSBAAAAAFBKU0tCT1Q0L1JFQURNRS5tZFBLAQIUAxQAAAAIAMp7E12fB5ft
          XgAAAG0AAAAaAAAAAAAAAAAAAACkgZwDAABQSlNLQk9UNC9ncmFkbGUucHJvcGVydGllc1BLAQIU
          AxQAAAAIAMp7E12wK1S/rgAAAEUBAAAYAAAAAAAAAAAAAACkgTIEAABQSlNLQk9UNC9zZXR0aW5n
          cy5ncmFkbGVQSwECFAMUAAAACADKexNdsqJfX0YAAABJAAAAFQAAAAAAAAAAAAAApIEWBQAAUEpT
          S0JPVDQvYnVpbGQuZ3JhZGxlUEsBAhQDFAAAAAgAi4ATXR9gM/72CQAASgoAABgAAAAAAAAAAAAA
          AKSBjwUAAFBKU0tCT1Q0L2FwcC9wanNrYm90Lmprc1BLAQIUAxQAAAAIALqBE10HlU9EQwEAACsD
          AAAZAAAAAAAAAAAAAACkgbsPAABQSlNLQk9UNC9hcHAvYnVpbGQuZ3JhZGxlUEsBAhQDFAAAAAgA
          ynsTXWnLCxEfAgAAcQYAACkAAAAAAAAAAAAAAKSBNREAAFBKU0tCT1Q0L2FwcC9zcmMvbWFpbi9B
          bmRyb2lkTWFuaWZlc3QueG1sUEsBAhQDFAAAAAgAuoETXdQTvRuEGgAADoIAAEAAAAAAAAAAAAAA
          AKSBmxMAAFBKU0tCT1Q0L2FwcC9zcmMvbWFpbi9qYXZhL2NvbS9tYWNyby9wanNrYm90L1JoeXRo
          bURldGVjdG9yLmphdmFQSwECFAMUAAAACAC6gRNdB3rybTkJAAD1KgAASgAAAAAAAAAAAAAApIF9
          LgAAUEpTS0JPVDQvYXBwL3NyYy9tYWluL2phdmEvY29tL21hY3JvL3Bqc2tib3QvQXV0b0FjY2Vz
          c2liaWxpdHlTZXJ2aWNlLmphdmFQSwECFAMUAAAACAC6gRNdPV9avXcUAABdagAAPwAAAAAAAAAA
          AAAApIEeOAAAUEpTS0JPVDQvYXBwL3NyYy9tYWluL2phdmEvY29tL21hY3JvL3Bqc2tib3QvRGVi
          dWdSZWNvcmRlci5qYXZhUEsBAhQDFAAAAAgAynsTXfxxkWVQDQAA0TMAAEAAAAAAAAAAAAAAAKSB
          8kwAAFBKU0tCT1Q0L2FwcC9zcmMvbWFpbi9qYXZhL2NvbS9tYWNyby9wanNrYm90L0NhcHR1cmVT
          ZXJ2aWNlLmphdmFQSwECFAMUAAAACADKexNdbmqMimAIAACBGQAAPgAAAAAAAAAAAAAApIGgWgAA
          UEpTS0JPVDQvYXBwL3NyYy9tYWluL2phdmEvY29tL21hY3JvL3Bqc2tib3QvTWFpbkFjdGl2aXR5
          LmphdmFQSwECFAMUAAAACADKexNdajgnhm0AAACcAAAALAAAAAAAAAAAAAAApIFcYwAAUEpTS0JP
          VDQvYXBwL3NyYy9tYWluL3Jlcy92YWx1ZXMvc3RyaW5ncy54bWxQSwECFAMUAAAACADKexNdqXlR
          v60AAAAsAQAAKwAAAAAAAAAAAAAApIETZAAAUEpTS0JPVDQvYXBwL3NyYy9tYWluL3Jlcy92YWx1
          ZXMvdGhlbWVzLnhtbFBLAQIUAxQAAAAIAMp7E12mHELE7AAAAKUBAAA+AAAAAAAAAAAAAACkgQll
          AABQSlNLQk9UNC9hcHAvc3JjL21haW4vcmVzL3htbC9hY2Nlc3NpYmlsaXR5X3NlcnZpY2VfY29u
          ZmlnLnhtbFBLBQYAAAAADwAPAEEFAABRZgAAAAA=
          EOF_B64
          tr -d ' \n\r\t' < /tmp/PJSKBOT4.b64 | base64 -d > /tmp/PJSKBOT4.zip
          mkdir -p /tmp/src
          unzip -q /tmp/PJSKBOT4.zip -d /tmp/src

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: '8.9'

      - name: Build APK
        run: gradle -p /tmp/src/PJSKBOT4 assembleDebug

      - name: Prepare APK
        run: cp /tmp/src/PJSKBOT4/app/build/outputs/apk/debug/app-debug.apk /tmp/PJSKBOT4.apk

      - name: Upload APK
        uses: actions/upload-artifact@v7
        with:
          name: PJSKBOT4
          path: /tmp/PJSKBOT4.apk
