name: Build PJSKBOT11

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/PJSKBOT11.yml'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Restore embedded project
        shell: bash
        run: |
          cat > /tmp/PJSKBOT11.b64 <<'EOF_B64'
          UEsDBBQAAAAIANQCFF2fB5ftXgAAAG0AAAAbAAAAUEpTS0JPVDExL2dyYWRsZS5wcm9wZXJ0aWVz
          yy9K10svSkzJSdXLKstNLEovttWNyK0wMjCxyFXQdUnLBEqk5iXnp2TmpduGhrjpWnAl5qUU5Wem
          6JUWpzpCmBG2JUWlqXCJvPy8kKLEvOLMksyy1CDnnMTiYogCAFBLAwQUAAAACADUAhRdsqJfX0YA
          AABJAAAAFgAAAFBKU0tCT1QxMS9idWlsZC5ncmFkbGUryClNz8wrVqjmUgCCzBQF9eT8XL3EvJSi
          /MwUvcSCgpzM5MSSzPw8dYWy1KJiIENB3ULPXM9YXQEkWamQlphTnMpVywUAUEsDBBQAAAAIANQC
          FF2wK1S/rgAAAEUBAAAZAAAAUEpTS0JPVDExL3NldHRpbmdzLmdyYWRsZaWPsQqDMBiE9zyFOOni
          AxQ6tGKhttYQ3SWYn5AS84ckFkrx3aulSOnQpTd+xx13Vo9SmYobLmEAE6IHiWY5sOhVQKfAv9Ei
          iSg1JOkKBn4Dk885x/UHlo4LDfTVTdGF1ZzIRARYMAJMf2fgUY9B4e8BFQrIPISEfcPD7nju6ktH
          WV0WeduxgtZN+u+DZaRDDNThFfqQGT5AtI1iWjanfd3GRJlejwKSeMOtjVPyBFBLAwQUAAAACADU
          AhRd3bTM/HQDAABJBgAAEwAAAFBKU0tCT1QxMS9SRUFETUUubWR1lN9uElEQxu/PU0zCjUalVE1M
          eocrbdRqm9p4DRasREqblsZ4B7IlCGvcaimL7rZbpf8MTbYFtU3wZbzcM/sOzjnsUkC9Wthzduab
          b34zIZh98OTh3Zn58XHGgp8RwB2dv2+Apzp4YYC3oWGl6VXOxXs866BlAG+do23y/S5g2UC75tVM
          wEOVV488TQ8zFgrBQDijgMUCuGeO2+4ydgPwTQs/HVM018lDHO1N92cX1dP/5Y0DP1O9ShctFbDe
          4rstelEGXlb5gUrh4vSt2/4O3qddUjMBkTigaeNhXpxFFQVmJifj4G2aWCWV9RJamjhJptdWErmF
          F1Optdz6agrcU4f/yHP9aPQuw4O3MKBSNfmFStLAdSzyg1e26KZD5XHdwO0OlVF22/Z1NpLgylXw
          jHP8YfL3KjxPZNZSwj/uGF7DkP4VC17RlNFq5GSZV5ujTvYtuewBY5f9CWwyYCarZNILLylSGes6
          KQaqQZQ0okko6Inytv2EWCyLQGiraOUn2Hh4uF1/Z1ODTtwMw51IZGkN3HOHYvGDLrs18DVgSUTg
          1i9yaIPb+2iRVw2RyduhnAWLvzGBf2iy2+FhFKRPbZV843tUCSkr7VHdNbOnmBu69M/qiKO6Liwc
          qVN4Qqn4V20Mfx5hSYOFRCbzLLHwUup3PhMtZFYFa4aM2R8L8sAHV1rV2OLHHUpBsBeICB+UvhJq
          lo9OAHuIXs1H56Zi86BM31ceynmp2jAGQ9DC+DVGY0QIhBlWm9RXgisvpqbngHCefzum4PA0nXrl
          XmhSsE2ctLiuB9lDQLjHZudj9+B36QMoM49mp2P07/pItgiLZpOry+mksMpPtHhJRM+pHhFEMnnf
          oQf9p6T8UGODSgQShQ4/OPm3kfhFo6tjoh2ZxOuBvUGnNFv0OHLbasBosEsu61Gij5XY9HTsXqBY
          JOwRAMQDNjeHhMve9lEWAeZiD2IKWTA6jf4yE+GCwR+2UWwN9q+pf5bO9lTUCFo9mFu/+8UTop/G
          s8N8Qsgv/tEmXg4FSrijChST66uJXHo5C1zLEw1BbdJRZTn7PL3oXxCXc4kVyKWXUsvrOcl4sSAX
          oRyrQfKwvsHfOXSDhjMA+BYVRgSRVQ20upBYWaG1ICPfT46Jkr5tyGByXQbBBja3qUrYByKTEU2x
          ncUkV/Y9v81/AFBLAwQUAAAACADUAhRdH2Az/vYJAABKCgAAGQAAAFBKU0tCT1QxMS9hcHAvcGpz
          a2JvdC5qa3ONlFdUEwgWhtMh1BCqivQOQhDpLSBVR5oFohCaIALSEsoqSAy9twiiQAw4dBHCiNKl
          OCwQBCnSu7TQ0QxVWObsnHH3affhnnvu99/7eD8UkcUEBASjiPAtGFwu2ix6lx3IBHxJhM9CiPDJ
          UzyKIkIr/yuCUiBEaO4pzj6tpzDWvyI2FiDoNESfQh2U+98XUHYUBqXxc2RDyUN4BpESnfZtaxPf
          thnnw6/aFKfbmGuAQNIIEFAExQZj/vcuCA4FoM7D4E7RZkA3MAQoB0E0FtvFFqLvJfQXiyAoNaoP
          IURI3zLLUcS7BZnwTpZuH4Q1+Rn/KCJoXPosqSbNYK+QN4vTeOQFZSTV0x6LLcYp8Gc1ocdAZBsu
          ++3Wkal1ssRXBxK5EN5aXdYRR8sBLyTZXvDzuwwKrp31UsqqpmUFbfWdp6ufCeuXTLnPztNjIGgV
          pL5xu8bpiIshDOT74GHrIyBmzpoxxC8I7dvWj8pcL16tac8U00RLCk+EWnRc/0WOhRo3JwUuAL5t
          Env79FiyMex6Mz1dLnIiKqRF59ww8sPszcKDTvbsP94gm5/4zMe1vH2vDWQLDM5qMSwtT72rnGi5
          bzYDQ6jnRiSsHHQ+oWypfSm3Z0wJEwzSgJKlzNG6ZmaO50aEJ5/Sh2TVaKuUJzKKiGwgfoA13voz
          w91xXFUIr2M7XfTdmhiwM/iW0sgxNNr5IUp7cImXy9b6vHag/hVPurgO4rZFpJrdPFLr93W0p8kT
          VZU1XKDZrytuvYsjcVZ28ZsPeHS9+aTyNMRqw/BMwB/VoKGYC7JjAos6qbb7jJt2o/GoS9Nck5VS
          2/HhmSEQuh4wPd01UeMgXKUYoKeDRTCELGJ3L2bVWyOm7nxBc27BtpdyZ4zacOWiZFbspzzrcBFz
          H3HdIPQoeb+C5FnEPPZGRD5USkJTUTiv1YCkI1Fa8J2JdJykT12XFL8eE/vZuCZJdbpbM9nHSbEe
          e3E2PGy5WsWSp42T9rWKCiMNgzujwJ1xa047JbFocMCuHOwebB9a0daL6Vwg8MvkliglqFAAibK4
          wvcEKh5ztXait23zyFii376yWAVQr/m9s8vIPZK4lbpHaMcKrUslv42mQTpnucF+ItHf7fPE94Fw
          jRdbHw+JnrbL4I1tdEVtwBKbZOodvBi/K98r2nyFlJtr4ZT3u2LtUihtE56pCY9dOWfUrfdQSZ1q
          6WB7J1pTy/dszt1eP3P8eJnv3irAYjkgoEyYnA0F9YSScMoPTDGMuw2WH+1IO1PaEATk936BlYhR
          1Y2v4MTF41T7/P3uKvTgVTDeOb+Y740cfCK0EdDkQOoaYZ4RrzixcBKaArOLavEVvb+eOLjr1xi4
          a1pbzyh62F/YucNBmjAag1mVeLLj2wXTB00bCy6GivjFUK8WZXPqPB9/tCo9a3vkNyo/V/+NoSX1
          EdkQIO14cT23qVdeWvWzKsybn+6s8XWSukZNOYxudy+VDDKddFTnHBed877FnMZglXbSDbCRMMjX
          uDkT33ysW3XDp06OfVtN+LGmv8BnFk3uPhEuts+54/KNzVjCIkLb3xfQhbbmXhnzIZQ7YLDdFSV4
          f5fS9JM/nANrE21XvExaPRj3E5Y3OkGVS4581NLgHSvu+frNFIEBN/yv2X0dEaGBiAGFTxVw8vN5
          XARdDDtBqzKKu9NaFBIpLGEAq1JoSwmTBPhzdLweyOloPXeHTnN3Crt961HBChXScfj+VcQaezd8
          Fe7igyWeHPRCghwfU4C+PLgbN68cuwbHFkuKZw8Ki0Ja5T+W5ZUGHIpR3rJFhD+k6AexqDp+M1wI
          87IY59g9yZ5/IC3HybX1kQhoizmOzx3knvBnMcnmj7u2QxrAR04bbG3apd/H6F+25CrFGRctPByi
          +YvkMO+6Z61uJHAX6cKx0x0xxklWPcHej0ZeDpFpisqGf0rvL13CeZQRQhwAP4AnAAfwArgAfAF4
          lOjPmFeZB4K8cf+Bm4iyuoa6sqrqJTUVlKoyigj5ucQEe0mEIE8RBwgIOG1M/2Hz/yVqxgXnjaKz
          knG/8RsGpYlZaxboOSP+H1FPCs1PvzSU97Ct21oyVElOJxDBqZippn2Z9PE+YH6sRZfjJaGV4XTn
          jIrqiEaPVHTXVm2iutzxzCz2Y9y0TUe2vxNHQ1QickZoyQD9MuPZ0sHqWK9MavfYpbu+YxSHRz4Z
          3KBPaRYH3yZt9OVb5N9jJKNleTWdqNsX0nF4g29pym75e8xdAmorZ6QzzP9ZqDI3SFxUI8c7PJZq
          D0ntLmg21h5cwxO+TIQNe7cU87vWkZX0okzWKHffQc5nEFxeYaKmauaiQjI9+ORp6scQhRsJ3s23
          H39OJkLetD426OTfDxhQKbvm52h29ODFQqWSPRqTpmG3oaBGp4Jjq33bTtC0bULunr9NY0KGaU29
          LGOlwTlMab67aToX1Dd1FQx0zVQSG7W0axFebkhyXd1RFFDoGBmOOjIfdccOX8EVPTC6pH6Zir0Y
          VM5k3JjL3pZtt2fjhf6HEuLJgCH8jspoSqz9cwcp8S1pjKKaKdRFh0CIJe/MOdMlA0UOpB/Sy/5o
          OCPY8sKoHDthDPYj2bXN/bAGioMjJy9XB888IxHbHq7SHSjYFSqF5flsym3Ogt9+BF8ZY6qsJ5Dd
          HHfXzHbhVkEtLWOEaQ/YFkpHpu1JutWR7ojTdi9iarpuDQdvd9Xf495cjMmQnFQ9Sjiaio057CAB
          epYLTV7xNlSL+uQB8zIwmu2j5bYLs6tagT283choZkPovdaT/YBP8XAuRfStvd+CRNtSssL5kOyz
          b4x+cP8SGP4LwJRlIQcpADd49nQxkyQDJZhHFuTCyAuFeXhfW8Dsy742gUrh5XeprAGh8nTaUEhL
          +3XZH2HfvyRxDCSDZCVrlpt5Xy/MWin0jHp5XcGlHFLHQ7S6pi7V8dkVeGvpO8w4nEH2dgsXYKMH
          OivlmheucYLvV4WpTUrfaiijJvluYnr2HnFZpAZ0vWbX7h5rCuHO9zTOUw4L7fl04LevuFf0Y+Na
          iTdnskfZjQJ2BgcArI/M4xDkk01aaf1dLbPm+mb1h6pGHZyLzRe9+HXFcyzvlEEk/snokqwQj3v2
          tY5dJ7xd0h2PWK3P9zgCu8p7Peh6JxBAnjQ8x2O4ZtAv76vtr8vOr16PuTKMcSSgVfwK6kzPJ5az
          PFvj3zS/I8zYwpsSlmNXtZFCmBZ5aIqxbjR4EwQTLMuzd7Gps2PaiCu3PJuhhwRphQTQvQrvOUqE
          i9snC1pYejbsiuxW1R4Kj6D6S4rzLWhf/dRdKmJMzvRJZcWirqGUUex/vy0ICAVARFBSjOinh140
          QwvlvYJrdZryGPOBbc69ffN3yJx+FYoIhEcv5elI4HQH8bX//TlSx/NbchaA4T+V8C9QSwMEFAAA
          AAgA1AIUXVGsTF5EAQAALQMAABoAAABQSlNLQk9UMTEvYXBwL2J1aWxkLmdyYWRsZaVSsU7DMBDd
          8xVWlsISNUWUGVVFKkOLKOqKLvElusaxLdspilD+HacxVUgHkLjBw/Pzu3u+p0VTkrTsM2K+iLNZ
          ruoEJDeKeAJaC8rBkZKzqIuigAe2hBqthhyHRzXkRiX6aKtMudmZ4WFNAve8Ynf30RniWEAj3ErJ
          gsog1Neo1Yaz+EowvjBrkr3gYnlBHJgSXejyDZ7QWC+2UhxZmk7hrZ+dxWmazAfhbpjOUilJlsN0
          djRemGKEnOlOGXzyDlnhj5s4sJJjZePba+YLWPuhjLcXiIv5Yhn/4FXYPgoCe6FcXf8i0o3tZA0J
          /tZqHFvhmDXl1MjY9+QXvjcwadGXQYFgcSLmF0RFu5aQCeSsAGHxv82Cn5Cnne5jMvZkVWNyXPlr
          n6CMBLmWPcMJDsO2k8P6db/Zbd/Th0lo/vyk8/n/AlBLAwQUAAAACADUAhRdacsLER8CAABxBgAA
          KgAAAFBKU0tCT1QxMS9hcHAvc3JjL21haW4vQW5kcm9pZE1hbmlmZXN0LnhtbK1Vy3KbMBTd+ysY
          7Y3aXccDTjEmLaltPIY0kxWjiIujBiRGEmn895VtsE39iKcNO3TPPTr3KefmrSysV5CKCe6iz/Yn
          ZAGnImN86aJa5/0v6GbYc0rCWQ5KWwbO1YDwTAqWuehZ62qAsaLPUBJlN+c2FSUm1QuWoHBzhoa9
          nmU+p1ag+hXIkqn1pVZjH3BSgotahj3Ajh/jJJim3iRYJOlDOBtHD8jCw39ku40WwbdFdD8bp3Gw
          +Bn6wYeSpdNgHHrpfBHdBX4SRrP/YJ9HcZLOoiS8DX1vzRVvyLZspKoKRok2wM3B+msZSVGI3yNC
          X+rKRTkpFKAjTEGeoHDR/C7+MYqSY7s2FTWyviq9KgAn6z+7BTcatjqoZq9Mr3YnhyTb0OwpYdxr
          cOgkEN4qITWYjtKyhtMYRSUAjyQDrjdxu0gBV0JODEJRUgEadhwdxrXB9nNWaJBd20772UJsne0t
          xp564b6UHRJTA1gKubpM06LsiXc/878HiyMyB5+R6+A2x4d5VyBfGYVLafdJpWsJ8Rb5XuL/6pND
          UC4kLKWoedZwJavKXFBCxshcil+wydG+Oa8V6NVaeJSCafcnVpgAL0rdT8bJaRmZzZB6vh/EcTgK
          J2HyuBvwqyL/yN4hh0E1ibBPRvpuF3StJWjSz4gmR4KuF4LO+pp1LWpJ12Nv9jzuOKeNd0oFz9my
          I9zBjbFdTvhgO5nXA7fPx7D3B1BLAwQUAAAACADUAhRdphxCxOwAAAClAQAAPwAAAFBKU0tCT1Qx
          MS9hcHAvc3JjL21haW4vcmVzL3htbC9hY2Nlc3NpYmlsaXR5X3NlcnZpY2VfY29uZmlnLnhtbH2P
          wWrDMAyG732K4HvjbqcR6rZQtl7HVthxuLbSiCZykJRsffu5JYeFwXQREv+HPq23311bjMCCiZx5
          KFemAAopIp2dGbRePpntZrH2IYAInrBFvS4FeMQARWZJKk+RE0ZnGtW+slZCA52XctqXIXXW9xfL
          IHbamUWRaxqqCBIYe70r7EQ5H7ezi5+/InN2FnsegfR47UGc0dw+kGL6elevsG88nSH+A78AxJMP
          lxvvTD1NByBgDHOOkmKNwd90jthBGtSZx9U8FDy9AteJuwOIDnyX4gH+pN4gfwzjZLtPpPmLbOBb
          AVPYzeIHUEsDBBQAAAAIANQCFF2peVG/rQAAACwBAAAsAAAAUEpTS0JPVDExL2FwcC9zcmMvbWFp
          bi9yZXMvdmFsdWVzL3RoZW1lcy54bWyNkMsKwjAQRfd+RYn7ZqMbiQGfC7Uq6A8M6aiBJCOT1OLf
          W1uFrsRZn3sudxRjpIoNRj3ImlMxPR1mATxOxfmGHvPj5rSdH84iuwNjSFMBoWSy5aRFZQcVkJAt
          uHxnr7eU72lmkqUwBxaduJXbhP7j/kouFNIavHVPoSOEqOQb+p2pbSip7hoKKvHwQHbQCBJX+I/A
          kCOeGdPMEXo4XqxGy3E/p2S7TQ+U7P3nBVBLAwQUAAAACADUAhRdajgnhm0AAACcAAAALQAAAFBK
          U0tCT1QxMS9hcHAvc3JjL21haW4vcmVzL3ZhbHVlcy9zdHJpbmdzLnhtbLMpSi3OLy1KTi2241IA
          ApvikqLMvHSFvMTcVFulxIKCeBBLyS7AK9jbyT/ERh8ij1VxMtCU4sykzJzMksr4lNTi5KLMgpLM
          /Dy4boW3LRve7Jyh8GZe6+sFSxXetMx5vbPlTdcShKk2+kjuAQBQSwMEFAAAAAgA1AIUXaSZniO+
          DQAA5jUAAEEAAABQSlNLQk9UMTEvYXBwL3NyYy9tYWluL2phdmEvY29tL21hY3JvL3Bqc2tib3Qv
          Q2FwdHVyZVNlcnZpY2UuamF2Yb0bXY/bxvHdv2IjoAFVn5nTGUlcX+xU1ul8SvQFSfbFTQ1hRa0k
          xhTJkJTO1/qAvBRI64c2QJu0QBH0IUGBvvehaH9NX33+D539ona5S538gRK2JXFnZmfna2dm1zH2
          nuA5QV60dJfYSyI3/iJ9Momyw2vX/GUcJRnC4TSJ/KmL49jtRpk/8z2c+VF4eBVAY4HDkARXwnVw
          CCwkVrghSda+R4wxLwozEmZui32UDg8XOCHTfkJmJCGhR1IDcp7geOF7qduIgsjkIR/u+09JcBwl
          S2zOBpNMz2Aid+qncYDP3SP+WbYwA/6hn2QrHAg0A35Jpj52W0sgtm1sQPDUMhuHiJPoC+JRcbsd
          +qKf/35lhLJlRal7b+UHU9vACXwP7DhiaLRIgH8bQOueH9oWBhyufRgAI8kyP5ybyl375My9n+C1
          n5lSZYOdiK6oubYZEQN4CP/YR06Bq+isTBhn/nROMhBIlllELEbbfkhw0sbn0cqcXsCMyNPMyoQc
          j3BKvTVeTQLfQ16A0xQ1cJytEiK8BwEJEk5TJH//+hqCJ078Nc4ISjNwQw/N/BAHaJglIErUOKl3
          u832uHWE7qCKiAljj5OtHJbj+2GGur1R67jVqI9avS6n8GENOFRxCiaFYsUcVTjdM9C64CgqqOID
          yFf9QQXSjA2J9UjTswBKkNx+NSDNBNCZbhD6MsgZitYkMbiW6mVSXKWFCYz4BSNkluokBovzbLE8
          IhkIMErQVHzRgY7IZDUfEC9KqHwS8aUw3ToKQJUBQZMoCggOEV5lUTPEk4BMQYtZsiIFDKru1EsI
          CU8PSwZOCihBBPY1i9NhhpPs0Dp0nOAlKaxyFkQ4Q94qAUFkx7GU1M97INUEwgAH5k6wBv9AsAGB
          WjPiVIW90yddxRAwNkOCCp8IJAurBKcyxO5IF6jsoU7vqDnuD1oP66Nm9TBHl2IHCiGoU1eKowBK
          2QtATTFOtvBTlSmP8Sl2UpVKSqUH+xGZJ9EqnDoFn9tDobLDOpXL5z+8/Pa36PKHbypVjb7qAYIj
          zUecHFQ+lf4nw0/v9UY3RJCp7BkgHNXt1D+jguoNWqNHOYyyBm1yl63IMYelJ2rMOTou6KwdRaBa
          R1udtDLAHZ6nGVm6wn5G/pJ0/CDwU80E/Bly5Gbiejg8SvBZj3ttylWj2tJGPwJGZf7iGv+33Eip
          h0Qh468RLZewLodnM3QEPvYYxCzA85R/ZQJqTVUWKMMcGt0B+ayCAD17pgRT9A5/WwWrA3GFaDiq
          D0bj4ajV+PSRunAgkJB0FQArUwLi4kSpXIGn5tMswU5lAwBesK/KTfDNAY5whg81DllW4D5sDoZg
          nO7w6NNxqztCd++gmzeL8tyQ0Jjo48QjAY1DGi8UDnjh07ts61NVgEiQkjefQNOqtjBVZHfQPpW9
          Sl/KXucgzaJ4SIKZai2cM0VD4M65liyT2zMytIyX6I7hjY4dusoiHXMLkRc4neZRqw4u2/uk2WCB
          ZNgcPGw1mnqYzI3rDp2QSq8wgSKXPUUgdiouhDAfmEgaOAgmUI6YEYf6fWEKN4cuilc+us8VH32j
          GIJKSglt09lGNcYbMyrq8UwNiJuozrdSvgsNSBqtErr7VKmQZVFBIEPz6DtIALMFq0vSwwKFk90o
          LIg/X2SShGbakpOPJMWieGjIoIFV2/3NdeQ5gDlMmczsvgW0hbQoDQLpudPB2QJK1KfOh7f29/IJ
          3kMHVUUnCuKJgXjzgxzxRCJqmFMSplApAGKOYyixBkSMlzuIWtA+in06tVX5StIKLCjprAsO0Aoh
          /EMqYnIkBVVucOaIUs26g/v36uNb8JhgN6186kk4sKo4M98P9ay9PIUozyBeZ1FCxOaAXo67D1uD
          0YN6e3zUGvbb9Ufj43b9/rj+YNQbd1qDQW9gElA0Q5U7XCUzDKqompA04L+W56tTpCTrhUz/9TX2
          2a7UpiEyhPwm4fZx427BHRk4p4L4vqMQp0+WnFsCnETgZF3sfbnyE9IGHaYZI2mLeCzr4Ih6elGY
          kj55Nn/9umWU5UCzGSy4kzJDghRcJB1OhQ+Ml2kx3ZCPnmO7bJ46s8MUYfFpbofykQk77SOA36am
          mVqFZWq3+IjYtCugxZKLjxRRKaBNOlRLSv1Wtr3VAaTuUQH4Ez8A/5FNglR8lktwGzrVomNjS7Im
          yb9jz5LUR4C66Wqy9DNHqHb3rdguG1mHuX46WIUh5PyOkd7LJ4cFTYATckOQNgaxHUo4CzuWiVfx
          FHwLyteiX11AkMi8BXKgoonOqMaQPw+hvjMUd8E7LYHVnXPPzMXKfkJuHKWGL29EdbFXiFGq5sot
          BFz2Kv2rnKUbrlIa5CjukhWowkYd2mFQp4Z4APnjYsh6I3oRbSlnFJmrbQiWBdAva1WUgoKzRu+i
          WpXn7x+jNboNf2+gmpUaSxcVFSrkWOsijM6uKDU1cCg44pR1VijiDaUpoolNgn2Eavv7+5ZYu2mK
          AKk84KKfMvgZ5Bt5OlNr78lZFWY2KCAE7bWsnoG/Yn7IVFLmvXzUjaM0Y3Xz7duaJsvqZE3OWTSf
          B4R3RphzFureXfyXVg6ijwH4xqbJ7UCQSVkRUBJIty/Xtuyy+Tbzlph28WENXtDeE0J7hVfvUlTe
          V28plU609kn6nsjELr/7A7r821eX3//48tuvL3/3zxfPv37x/AfXkpnZ2Ws3u/dHJ+PhSW8wKt+l
          3HQRnZXWUNYIqv3a2zSfaMkGtlGpmn0ja91vT38U5ReIbCC2qMkStInNNnZV4XbVVV785l8v//LH
          Fz/+B10+/+vl99+8/NOfL//+FXrxj3/vqrQdlGVX0sUODlvohSly0DrjEE4crXFuaUSctrpHvVNb
          +0E9MkGT6KloC6qvZRNVogAUS6kTH4Ik74eq4C6IofWLXndUb5tIfTxlwedgD4k/Jsw97D3hXVh2
          huiwf12czCcOBGDIXfkfrdzk50KIRWzKP/9d5Dxm2ySzmUp/WLGODP1fEadWM8Y6fnhKGwTOvm3I
          X66WZcNyzTXOOPswgHphI/C9J3ldsjajnX548I7ysxBk30qCQZ/dkgw1KS5wUurtFyok1TvIiB7b
          mL4cWzy4aKEu/+hj2HVTh/Yz3r9VtZaFwk4gTm01FBjfWMqg2ajYx7it7JuDVmPZjNmtRYxLc7nF
          rOWWbiwCxmotxga/s4yB6qsK+WcH5UIWmzsXsDyQK4pY7O1Ckqqnn560tJMgHdKU+WZcHE074tNt
          NLuj5mBnMXBCryqJgw/eLxcF6+qdx7QlUNq1P/jAmPFj/ShUm9AdPeo3x/V+vy2Pp3pAtF1/ZFC5
          fSWV/kmv21TYLYdHQWypXKlkynHKN+YtfJ0O6v1xA7YP0F35xvvGBKhSXos8627R44TjXuPBsH6v
          3UTPrkzqrqIH2us9oKcU43ar0xoNyzlTO42jQb07bD+gVm6mHYpWg5jeu1nzVqz0jVGvj57lv9rN
          49GhikATgdot7RXFrt18Xz0PZFcU2Eny548RrDAUTs9fHTw+LICCOwBglPhzX4LSVyagODCnVBM8
          n9MrFBxcDtQeF7yaRcVRtPIWeVR01ns0fzQ20vTMZ1km2/Pq4gwnfQJbmbVh4WHIfpWLLW6dH+ZA
          RtW9bVUUlcTn+49px5xOMcBnn5Vl6Qy0poI+KgPlYuN0qYa2QtUE1HnJtEKqnNoMQ4JvBxRlvYDY
          WTYdiEl22fB7B9OnunCgWhdCs7MhsM51OUkszRjUhyYwrFjHk9SZPq2iu6h2QI8VNy/P+ctt/TJd
          WPzWRhmscJ2Nrq7zufitAmBhK+r5BrVWRD0v6/7Rx16OqY9WM7i86UK3QZHjgwvtAQdb2NvaUbO0
          5uQjLKhcbGaHkT4TqH6eFIumQnLJCCvaKckvxUUhkC2sUnlvCk0XkkwUBH5BPrt3GDfz83MEy3qs
          ibKtKCwAFno4MvMqPUbYHBDsfjxQWk5gz7PkBDt3sMXVOKBC8zq9tclI25tDAp7eo6s3Gqh3fFy5
          oleRY1gNjVPpogq6XjIOI5SGPIekWqcLjDO6Y5RhvdewoDWiZRyQ7Xif2fDoUWUQbMUbWPAGhB4k
          bkU7VdBOKc40mg8IWIJerxWz+7w8Msiq9SAkshV6Esjle1v+OD5GFRtHeQ9S1pzo3XeRrS9J6UJZ
          9t/vfs/JWqlx+3JnLFlyKj9x92ezOEVg3psGr5UL4SB3eQu7cr18CgFpDlSW6S9Dm0UJW1SLBUW+
          lv5Pflet4Opbyomix1gukSNZ/1rG7Gn75garPTmVncSSbpnlgrrb6vR7g1G922iO271TDa2411nQ
          UbgUtwu1VpdtouJNJvqES3G4bpOAd1VHXUXSrwaKqJaBklU9qAj8WjesYGIJSa9SJsrnY0OVcgpW
          de8pyquWErm9nYh+jMR23olBi0aFBv+/AiM/C4iTW4U5rwpLAwmTmBVquMRB0PJAuPKu9sCFXZ/t
          ua7vjdkF+zG9kmDH74XziIYNdhpmQkzoKgt77rZrsEckzZJI78j+H8/0WCpe3ZrGqMc5V4XSqnli
          I8nsmvHZGVCv3+inp+JahnGG+mbzFa7R5FPq792EQP34Nue13Q5VbvC8XaHKVFJRqn4YsOVETU9u
          E7IEYmp+W35E8UYs61eic/70C8dfrvxsiGckOH8dWclb6LlnXu3L4j/BgDvTL/pNYcux9iZxv7h2
          ce1/UEsDBBQAAAAIANQCFF06DfhL0QwAAJdCAABLAAAAUEpTS0JPVDExL2FwcC9zcmMvbWFpbi9q
          YXZhL2NvbS9tYWNyby9wanNrYm90L0F1dG9BY2Nlc3NpYmlsaXR5U2VydmljZS5qYXZh7Rxdb9zG
          8V2/Yq2HgFefadlp2jSy1KiyHLvRV6VLW/TF4N2tdIx4JEvyZF0SAW7itE5cIAYSNWorBy6ab7So
          6vrBBZI/pKP+Q2eWXHK5XO7xXCd10Q5gHW85Ozs7Mzs7M7tn3+rsWNuUdLy+2bc6gWf6r4Y7bS+a
          nZqy+74XRMRyu4Fnd02r06FhaLdtx46GIQ127Q41F8TGzaRxtlbPl2gYDQJ6mYadwPYj23NL/bYD
          y+/ZndBct6Je6a0Xmlfh2aGB6tWy5/mKN7s2vVHkpziFpV3qRupeP4U/i567ZW8PAivhl+O9au1a
          5iCyHXMhCKzhsh3mNPJ3i17ft6CrFyheXrXC3orlK95UUFMjrwe2F8A8fjKgA1DElD9oO3aHdBwr
          DMnCIPJUCiN0L6JuFxBUL1+fIgApIduNaLBlQXML9JfqcNFynDYYUoqKsAtiI567QcOBExmbUWC7
          2yRg3xqzDGt/KqEb2LtWREkYgUw70M+BT4dW82q7gOqilan6b9mu5RDHg9EWr76y+vL1lU0yR569
          ODsGubWwnqBeeHYc6pXla4sp3QvPa5C3HM+KUuzL1zZbC6uLS9jnuee2NL1AwGRl4efXN1sbay8v
          4SA/qMP71bWNa79YW2VsZUpAyKRwjqzAKoJFvmckk21mM2mksjx/PkE/Ob4JIuuH8b2Ho7/dHP3p
          iMT3D+K3fgUfR/G7H8cPDkfvfkDgLYnvHJ0c3yLxwe34w7sk/vpodPx31v77m/HBV+T04Gh052OT
          ExfeH92P73x8Hsl+dnN093D0xUOkd/rHW2T05eej9++T+KO3R/c/QdzRZ++cfnQbRzx58FZ8DzCO
          v4BeIu1q2VxbvQ6zfOlq63rr2srS2iut66uJ4mauz8ywf8uSISWd19qv0k4ENMCq54hLb6QtRmNW
          gZ36IdK3bJc/J73Sb0bijsxtGq0ATvLNaDSUYxfW8KWN3jDq9S/TCEb3ArNl+cxHzZPI8hmGpHAc
          tUhh3sg9j9lhj7Aal0E8hkXOzRPL7A7oaljBDfiZS9dg1W/ToEkkZq56TrdlBTCredKloR3QLjaF
          CpZS/wbM1BgG/IW3QzdBmxTY60T2Lk2aJqPc9jyHWi6xwJf0mctecq22Q7ugnChA/6jCtt0rjr3d
          iwBpy3LCCix/0PfXvTBixBR4zPrA60ZXAqsP0gWskqllzo4hd+3Qt6JOD72en9DFHuM7oHYdOlEP
          dKCOM0GPDYrWX6PDDcTuetvg+WmknDVD40LetIGTTDoiGjpCPvpL1KXJnouIOs+fbHSC/Qh7Uu5g
          7e6s1FqORsyEiNACI2GL3DXx83vq5mHKLILAlZFw0Zxk3CYfiT8MG8LkEKKeHZo26kicYPYmIQNv
          5XlkGHvwck/RPoT2Yd6+X9jAk8Ag1ULltg0+whD5DSjM2xV280qS2boMIfpymRXqKJEz4HkHjqOi
          yEwPOLksLTUVPXk51qGXrUQdwQypFkW+UrUUOVIdinwl6whyHB29nxUWuopa0RWoaHHVRrAKYGMz
          CpbHrV3ROCw2qkLRTvrAEEXm7C1iZLYyl9iKvJAQhxPg9tTISJpZXDu9sLhI1q5cmW4UF00qAGFb
          EOaOEAVDaUhMcYifRg34xZBo+mbf26Utz4D1P2wIbgUh8dUD7iML7zhk4Z/yLYfnZ5abWoRSGoRB
          DSivZfepN4BFruwtM6zwez8a2E4XAqd2Bf8omOpuhjxC27S63cSXqmdcQa/kfvXy8vXSmtG/5irT
          YzE7Uou10FoSQbq8PIxh872UTVk9q7bZRnEaDTVDgsiSFcCXmyGvIBFeXNulQWB31VNASN1BmjTm
          XlQrFYSy/sA1yU2VVHRMI5Q89tmzkoRlUDsO/SgIZdcytguH6cW1lfXlpdbSZfIimSZna3dk/iDw
          Bm7X2GtM0G+6+ZijDNWuQQTJ58mwX/l2v1ovE5tftuU+LebHGXo6zQ/rGsvL/+vmp2xVe1GhSqB1
          36hNb0elPzk2VRrGJMYwoQFg3LO0Xs/lTKLn8bodr0+FDova2ScUtlONVHn0+w1IdXpj6cdLiyA4
          OWJUsFkcOw0pvR0hnoQBgF1itHqBdwMLG4TKrIydU935TGAh00sbG2sbL2gtg2LUuIjJutHAx00b
          t9hVq08VAaQkK7VkSsG2gFrcAvzAi5JiRurx0xxVnV6GAyzcqZDywfJ8guXLs5qxC1sN7BIQbQ4N
          XX6CBBviCElym/M3dDugf9d+DSZkYMGyVBZIC4VmB6LBQM4rxLqdGqNQgFOjqGtmkrK4JLNZq1JC
          JhnIFxfkmp3Bo1mafC/oaKwMVCXAlJBiQZxRjFFPmvUkWlOqesnKGOVSWoGpUikNXYGIsa/SWUB/
          OQB1rQ/6vjGjUdig3bcjQyoPs9LnQgcHC9l84VM29bQ5z8ST5TyRgTOVlTSsIIVQrMluDsOI9k3X
          cj1MYEtZpMCiCZoPdS4yswxIPBccp9BP78LUFlPJSI/V2DWcbHkBkZWR1+pJj7xACrSqNrACXz4k
          9z0Ti5a9GpuXYqY6W8pqyWBMIl5S2KCONVwJJ1vxKLC8SJ8bg4hTKOLnJwIS30K8ZvqAfRnZAYcE
          bvvcvDTqeL5K4yqW9X6JS9E17DfzWs5MM5OORqIJhVIpnAnX9W6MXQkJuuSA5YJ33YMiZnFy5+zc
          XHveFab1sRx7vsBnPavgDlOlGfE9d6hn0KOSZ56pDGYSEZ4reeJ55fEjDqskVTwhPbhN4sPPi0eu
          p+/dPXl0fHpwePKP+yT+9J34zhGJ37qdHpaS0Z8/P/3g1uiTr0j85sPRp8fZ+WhplmM3FRFLv7Eg
          1NzLEMbvQxyK5WMVVmUkj6Ba76yTzhHTLDgobScThgn1ggB9MLFfHlLcvbhdZvYnvpwnFy4+l51x
          Px6H0vjJtjMnHbqKZJRl6Z4X2K9VVqUT3tWJQublLiw3pVsODfIdckE+wudwo4fHkcaZTLp2uNT3
          I4yzK1ZxhulTugMZCTsQJ5fmMuar+4VmCO4GSF8S721UxAchxgZGPpoHYUJDL/UnNpnMTL4/o7UL
          ibsaQaK4FtAei+4g41cRkPGoRoGNhJjFFZuYEAWSr5cNjm2IeMljRrKLepszm01Z2lUxUnpMvrXF
          PKRa9udUu6uKGGe93lnNhTFHNSlX54WVQs5pe3DQrDyYzMXl2qWX8qRs12ANTXIR7G/iKkgeGjIq
          yoM3ZRSnO3FKP+dqnDHlEqq6r+LSvajkJQvFgig9gV/0Bm4k3GhAYKG7eH8BlgCE63LUU1w0u5YD
          YgEbVYU74ljzc0Un1Q6otSOtEl3eMJcuyYDiYaQBz5AQqFKVHk9PcM2e6ZnU7UIw0dnBr5pdc+wp
          KEJ2EorD7zVRQqZsCAmeY7uI10Osnlk6Na0wC8UFjIrNCwFHT0Rsdjw3st1BqhbDbxIIz/kFvCZL
          MFQspOYnnFfK6SICmhXLwRKhN5mIxCslvD3EuaYTVtARzKFUAUjiqZL+nhL1gecp3qasJ8zH1hy/
          HtlMguSxdcl60v22pCbhfZOC+t6TklBVcFFhcjXKHIm7yvxjxXY/qYtEmExrOhfE1lu2xKrijMdb
          DggTaBrhydyLyNjWhygcxtyT4JAtyVrY1fcmONQ/QtKlmrU2GoR/e7NBeJr1k212tbBxQ9Srp7ZF
          q3ZMhGzX7Cn3zF6dHVNxt2BSJ5bkiV4QTXgVG0Hl5XhVDAmDl2MVZlVRnCdlb7xBdD6ubNb1UiU+
          TuafxRI4prlj43sEvqdo02Ce2UXWSjg2Qaq6w4YsZSkZS4cbheyo0GnMHTucq7nFgqIf5r8JeSH9
          JclsuWsYWUFUZB745HOSR6t/HxD5AOPFj5LjQeVkfCor0dx1iVRUO4vYqdIZYgXz3lej48Pzo1vv
          x/duktHbj07ffcRKlwf4K5K7o89+S0a3b40+eaQsTgKBpAs5fe+v7McfX/6GxP98BI/x7x6O3rsF
          dA5Hbx7G9w5J/OHxyYPj0d0jPgr+huTXd0+Ob47ufZ3i4XDxm3+J//CF+HORsQLQV2Rq7qffyv3C
          1Kj+k7cMK3yhFMIVMl5IeWVjFDP7Z+tn9fmd/v4wLylPdiSQF8OLR0Diy7wGPqaSI7IB2GfPlgve
          yomUbwQ/xu3N1DCfqjucte7IPdZNTF2H+vuXCGioBQWemVMcWNShhFB1AiGD5u4ihwkOWKq7QRiE
          x9IYEtXoW++MSNVj/HkRh+oLdQiq82I1lSdnttndzydrtuINTl2H/5stm89/kekpW7/Ne5+FgSe5
          2ijj1Le9CdT6pE+a6x0fl9WiCy+EjK18o9Ledr2gXHqqJ6yn+I6XLJTvihdMppK/7CNzoZKrLP+3
          CUa5iVD8C6LZ19LCg5QgGPjsJ4L7U/tT/wJQSwMEFAAAAAgA1AIUXTjLWZ+YHwAAdZQAAEEAAABQ
          SlNLQk9UMTEvYXBwL3NyYy9tYWluL2phdmEvY29tL21hY3JvL3Bqc2tib3QvUmh5dGhtRGV0ZWN0
          b3IuamF2Ye09/XMcxZW/+68Y8gO1wqv17kqyZSx0ZWOwHAy4bCegSlGpWe3sasxqRzU7K+8m4coG
          kTjYHOawwRDJJ+pMIDlxJ4yPs1PmH9KO/ofr9/pjevprRwJydVWZSvBq+vXr7tevX7+v7ln1l970
          24G3FK1UVvylOKqsXu692YiSE4cOhSurUZx4frcZR2GzshI0Q79ydoWAZ4WX/TW/0g2jyqlhEpzq
          t1pBfCJX1k/CTuVkHPvDc2EvMZQ9H62s+rGfRKaKC35v+WJgqmbBhsCHVvuNTrjkLXX8Xs+7sDxM
          lldOB0mwRBrxfnvIIw+D6CV+Qv5phV2/44XdxLu0eP6FX7/y6oWXT57znvNqJ8YDv3ju7PMvEdh6
          AdiFV8+dJqBTBUDPUNBpMhobLB3eJX/1hbWAVKMDk4AzjGHzhLmw1Yn8xBs4S4eW0kYUdQK/S6DC
          pTctMJ2o2/aa/eCVHhsHPLzHJdq1Mu8F/zEs53GXJTQT0jDhSZbDXiVsEkrJYxQlA1IwMLwfkvdD
          w3tsj5QpYxLl2AdSzobEy946RP87ZqoWok7zkh+3g/+7yQq6zRfp2ARc1qsCE8Lr/8TzwJshxVmP
          90nt00Gj3z4VDWy0ZoOslb0h+f+gTv6tW6gHdEmGq4FENY69lKFhxBK/ACV7R35xHEbKDWpAoJqJ
          QlAyNJUM6lCnbqoDJUNTCXSAlNGxHISeZ7utyE3Qy/1mOzgXtBInnyLUhbC9XABs0QICW8Acn4d5
          wqKDoOcC5XJn3kv8VSdktiTmvWXyu6dOPJChlCMvPAoByi4AHLsTYlEvNY3YApUfrAVIG6cAM3Kp
          GBlhIcM05+FwgBxQmek85CKHWjRA4BgJgDK7ohxGBxydm1FRioMixWwSeVlBjn8x9leCk0tJGHV7
          Nqb/4ZxlBM4WWxN+Sfwnd6pkmmpLQ2UVp3GKD0ROUY54YXukfTaTOw7X/CQw0fti0F7JazIgNAdc
          Op/Ive5G8YrfKXMVAbpU9tr43yRK/I5EMoa3xLHhv0wkD/cpjx1SN7+XvZW1v0bUZ89vNkvWPQA6
          fPhwHmnY8kpUXj8nq6UTbOQqeNDpBXod1E4nKJGK1QAddQLJWQz+DMK3FfiiU36qEzWU+V4Ju68T
          Up7tJkE7iCsvn3z91788ee4XL+Snf8Uf5KDOvmKECruLhXAtjsdF+psUAIujK70Dc6rgFL4UNIWX
          UedlP1mukN8l+LvsAcdO5GeLEYgC+oMS/I2AdRWQ0kjGuAiAQx3hooLQCMfpREryBUAZlacobbzD
          AE5/58upQo7FBp0cSEkL4Ve+rC3K2loZkp0WshngJdKqpVvx0qBEpsCLg6Qfdz0kt3cYiTvhPeNV
          KzOtE4zZszqtOOomi3I9oJUOdyVsJssK2OveJM6xDr0cwCaqYqXgBuR+b5UYvDI4b+5INoe1Vlng
          nTihy6xGL4obJVykUTFOjOD364V4MaogGYtwI2JdLMSQiFUF5TwpYPEFAOOPCZ1RgTuiSn4xw5Mx
          bORm2MjFsJGDYSMXw0YOhuW7S0mdKZTZiGHuOa86wflB2lQkEUQHgQzXYls94Rhq5kx4SusZcKvF
          zeYi0G2AbhtRaz0n3Zgn3a5MHW3luw47lb5lthh4va6A41aow7dt8Gc09Ca6ZfMgzYZjw3slSoJL
          sU/IlN/1ZLOZ0qivvhiqL1bjYC2M+r1FtWBNAkXfCXC57LDAl7z6K8p+1QuC7gmNq7I3wjkTxkFT
          fw0cczHx40QuxAZ7S8tBs98Jmqfz7hPa6SZ66ILmayCmbIUnUaqdKEjs56NOFF/odyVaZ+a6rMQZ
          DHxeVzPwBwc35u3Ko8UwVzcjohIEcW5DIo0dJijtm5G2yZBOTEL3CrMsmhIHY9mBxpkDhScIExlY
          E/j1ImFDlTVXwl4v7LbRBurprJf3FRUwODhDEn5dWdW4pK/0SnVk5qszRumPdVf2yUT3DTxQyLnI
          BiOZlEKiEPsP/gEU3eCKJ5zuc/MltsEZaovJnfd8YlSuBQvMxiuOIk+G+WyZ498WXDlkqCUHgwSG
          crYpOd6VcugbLa/CY8DSAs54rUz/XSDq6VJM2Og1/mNBGQTOWG9AiodEGegnr+N/FxXEui/KUJL5
          QgyFkv8jX7rmd8Pe8uv2InNf2kQj8zu/BJNzstbKxwhyXovVOFoKer28rwpjOF4I/807hlCsodPg
          IqObs3hBL45arV6QvEwdSTL304kB/zA0WyE4XqOC6UQeZEEGWWCqaQbD5hNdFFI/VYAFBWBBWrU9
          cEaz7hzx6lPT1ZZUfcgLF0hhrTorFwKDgGHD+pCpLhRbDnBRAC6ogHJnhANstjbbIjK8J+3csrtt
          6ngViwdKMfey1Y7PaACMt6C0dsxSCk3XjvKWM1kLihHnMVAaW6okkziwXqnOqH2Xti6Uht3oCsq2
          i8NeEqxUun43uhSuBEISwINsWTnf8buBtyqzAb7qlSZ+VX0jayELOHqNPqiTqwBK38gcw2zyi0kc
          NgMOdoG/UCFXw0HQycOez17luouyDEyjea9B/ouSG7WUhcBvwvteiXSsnDVelrHLmI4c8fZur6fr
          j9LHD9PNu97PRusfpZtXvb07G97o3Ud77z362ei9297eB1+nmw+90V//4KWPH5Gfo4+2KMyD66Mv
          b3qj6+ujLx6O/kJAbm2MbtyvyA2MdjYR5bs3Rx/eGv15+8jo7Yej76566b0v0hub3ujOzdH2o/ST
          W1Kjuzuk+JPt0b9te+nnO7s719KNJ6PPN7zdB1fT7zZIG+TX9+lnO3IzuAMFMSAard/dfbRD/uel
          W+sU893R23dhgKPtJ6QLrBlAuXfnL+njfJ85TVcCsozPLw974ZLfgQ2CyDf0jRDyAohMyGyPyftE
          HVsQPP3VJhGtYh9liMuUactCppURl8YCXFGcZyuyT8Tuc7m1Ag9lDZj7peTnHG4/DHLzVrp1J13f
          IjN5G0iWbqwDKdN3/ohz/+3D3W+3vEsnz6eb6+TlZrr+DaF3+iWZwjvvEe5R+WFvfSd9TKpvPtz7
          l0/JLBwZ7WzsPvzQ2/vsq91vn8DUkxrpjQ1pktLNR4RVRrfuph8/JIyxk/6BtHTv3dHWF+QdMGj6
          p1sAs/kw/eS62p6gDQCC5Xbk4rmzp1/AYUA/vrudbl0jXAKDSd/eTj/7C2HEHBI6S0Jf6ZUESjZT
          Zk5QHeH0t0PDgacVxV4p03uXvWdl7UiVhRLaCjjvALEUVdV4AetUwqYelaElAyJMURkxlpfYnnHY
          O16nYneCwhsCRhQfV4tzxRMTRmm9BIp0f7XkoGgWgGqyX0ERcqIXqUEoSZetQsMMlSChCLEah9VA
          R5N5yFhmIUcDvU6OMms96lspQkRmacEgcuEaDbE5Nifxk14oKGOOQfLHEYXMgVjikDkYC0XgyabN
          DqMyBkrR4uASNSa0StmbCaPRh25MTb7n0Kj7eL5nmfZiV3bLOr78/qNpwxeDnN3W7wVNtoJYxpOy
          Q2HHKr0oTkpZvlRlCX8Se/h0RFT/AFfYs89S7/NEJQ7WgpggBs/uof0sRbHbeHvvXAU1Y+d9UB3o
          RoB7zp310b276V+/90bXNkElgRc3ro82n3hkxwBFYeual97/ML2xzVWGb9fTt3dUic4aox0efUFq
          f7SD6gu25I1+/6/Q+pc39649IRrC1+k7BOvmk3TnfS+9ez298z3bdogWsvfxF9iPe9fVrQfHTN1n
          hMIlKhmI7KRLXbhNDPBgpoPi+QtSCaIAZW84obgnM2deI+iBGt7td4z+Tih+PkKQF+GFHInKg8P0
          ZGgTMkfUqFcnCXmQaOnAOoQRuokfEgGTTEx48EfY7QcK5qwzTcKyQAuqk096SYW6ByEyUPs1savh
          /wpJeHNYFw0C73e/o5jmvdo02Adj212FGUgqQ0J94YevEv0nqazhFgbY9FZZn4fce+8TvXpIer2q
          xp0k4L4M3Mch9tW5EyMakhEcn+E7aTYKI3CfAFcr1dl6kQEv0RlvwohJzWe86boww4zoscKc4BbT
          nMMjcRPU0LvKgYDeeulbh/J/5eUa6QatSrnZ1AfO7ERcCVYtGWYD4GhSWObcUQOAAs7gFRNlhjQx
          USac4A6YNUDALVYLDF0D0FdYFmMaGwsIPvTMj6UVM3cv1yksUDmPOIJfUX0mRnjqJMcKPAqo16Bi
          BZUtqKxAvEWj/ea5z9GcTlAReklkHiebhHywagm1ll2DEJJNajEv3HQ9wtqj2L+CXg4UOnSwgIsK
          K+MqpjVATrDlPvSeftraWQo9581UqlwG/VbHy3FnzEWEcM0mIODJGB9bMAsJ6zRrWKwQKiRsqEeJ
          YXJ4bA06coCfmjVsN9g/MyUy55OzEQEGbYCId/cp609V1QgsfeGCy02+Ph1j1dU+hTlWbRl4aqwI
          LCS6gGmswpfJI/S1XAKRJN6WhZAqKKXctMgDI12c8yJEHuUr07wYRV+xXjDoIt0Q6RTGfii8gUqZ
          JFmNO2zFkHalL8QVf9gIMJwKHgWsqDmmispuiotFZ4iFYsYm3Fz5ARqGyraQOFiJ1oKzrVLiTc4r
          zbJclHbwsskpBs9YNTRXi1nWFOG8V59CRdSIGNbMvCecJcwDLvuoHSajRiqL3p/8PaxFzN+oYLid
          pyjIFh2SOInDdjuIL0WrIpuW0LR2vGr07QNt5qQ6VrRrVGdfo/sZj1Fo9P4nhNFePyspXQriIPGp
          FSL6SjdWDUdmKlRqTEsvk25NKCOi+Oa8yfo0mib073mkgGF0PGJMOJfYz89HXULdFTDCdT2Jbrfz
          z3l10zYuaFPXKU1s2/Rvn6cP7novnr+ILtW3/5OYyl764D/A4T/aup7eWx99d3VvfUfy76bf307v
          3EMP+tt3iQU+enuDmNX30y3hi/3yprf739vp55pBDX7+9eujbWJC0wgCc+oKLy96acFQ/nxn95uH
          pI10nSDf2kg/faTGDDiFom6APqwLQW+pH9gJRARZzUygIRBPTPPRul0nQraUYKddoPmthDQxRblz
          UASctCKMMTc82yMI/lplmjBgEWDQzWZbCoc+pfLa0097T+Wpa12GeH7mJA0clBRjFrhs68Pd/3mS
          rn/D/PHkn1vpAzLNX14FPz1EBO58v7sD/9wb3Xi8++ArCBik71zLIaE81gx7q36ytHyG7A39OPD2
          7j5Kv9tgGNH7c+9DYC2KG2MP//UIozmI0cCS539+8aVTr16a+edjUP1wvb7S83a/3QIHE+/gVWDC
          3W92Ksq4eWfOBX4TxYWsKPLMoI4/xDK65CfVSoeF5JWIlqVoGDia7ki6NjDeKqmes1slWDuO+t1m
          iff5mWyjq1QNzk2Fg8Le6f5qJ1wiu5TIuQBuKNORlL2paY7u3ISWekI3EBDnsere4FzH/5b3eLIh
          CY+8OLlnWAKmcIY9kLGfIIaiKWEenw6FJBBvcz5PoqAEK40gNhFN0nOIIMslqOmpOCYa2rUHobT9
          eLqDRTWQUu7+f+/kRFqAIozbFJELv3/fa1MxhL5l6vT99iERMPJ++eW1dGsdPM8omcAbfR2Ktq4p
          He0BhS4tx0EP6GVUSEUXj7bKIMLJYCQl26BwzOtYDepoppzoiRSOtScHIFl0gL+RPTrLmY+NJkjJ
          Zt4yOtYIv8uvDNtJVrgGpbL/d7nCkvR0C3O5kmXqmUpz+XqAViKiFFBFAbOcW4oSS49dblpkWNew
          syB9DAFjy8LTlpcSRqbRGmrvjMkp2F8EWSSqgkV2JqbOQ1cw4fTAFEqwojwfdt8cgxFAzFjzFWBc
          AndMhgUENVmubHseyL74uCJSWCeBD21O+Vg3jl0+NNLInCdynMZCUgK6vOtIiKZyYlkG4HMUF/IT
          GYZErw0YOyaXjqqNiU6ha1xikl1jY8xiHJpjoNyvQUnzlD188FN4emVBZNp7NKQHdQUPHL6lbPgq
          mxfokcWhTOWxtTYWo0vK6V6kPQe4aaOLEbcERyODAi5Mw+DtPk26LS11IG/aTk9oeDJLZShCxtzR
          JilFUkZj56eqg9dqxVjFvSVmUIatUQawOvGUmrDXW9jV5XWD50dYPBbxTVsmVvDMjKbvZOMYwIEm
          xsDivBdWLXtwGscsoaj2MoZzGKB9MuHJ8msPe8x1UKACZydWw1jB0PVCohMlL5OcNomfTRrXyua9
          ozOZ3WdkmQELv0EDYnmauFK6eEM3E+Ghyo+msPHHHD5XhsvyK7rgNxrvF94Pd1o5E1MleIM03m9x
          G6src55wsYmoDkIYneXEtBHEpanpkPEC2bbCFQiJsqMb23t37mLW7Mb63h1izfz5j5CGSf0jWUpn
          unnTpWvS3pkOAj6VTbJpWLJWTpEUG55e72yrtOxNzruYzMDiplknEzadcXhm49stAjIrL2Awq7s0
          RCvnkr96cLPgx/TlF9OfLTqwLT2FgvNI2Zw3RR2nA2uOSpbh5BCkeW298C588B3YtvsqO6+66zp9
          efDY/Hm53lZh05GchROyd049IGv1xmW+uNqs7IuzzAN3stO0+eZFInHoZV7PeS2f7P8/NDuMO6wc
          1oPm9SL7T/Wcq4aw5iC0Pen1geMgZl41OscNtZQGJ/lZOXSbO3cy7LBOK/NWhQSOA//NA+zGaiPW
          GSzoH4VHToIyM3osq84/Xga4yfQ0Q+adqPBMqKtNd6YaXKnGM4tSoq16UCbXQv5kjy58s/MSWpF0
          fkKTvHjbC8ZHtaHLQkBy08/wmF6OCIjnVJQk0YoVFVFkrQuBnS6b9GqFYgXHxBw7zQ/s1cUkcA6v
          lhvelGVwg/2hqbO9RkVDiABbnAPP8TyemgFR5l7Ln7Qa63pDekDODJnxEx6GFdmkwV/E8EBiqTKG
          xdLh6FcQYyyPKDWXSlriL94HQ0/muR0YVfMcS8N27qX8CN/4ZCp4SplFM8mrgmQgfxaqP1V12TTO
          PRjXJTuL6F4C7OSllf1/StJwRSRHm2IIfgBtxF0+Qdvog+WXC52JoiYe6NWL2/6q4j2HRzA6mHfA
          jifIL8LoOBHwm7D5wMTmHC3dFqzj7+FpNZDSL4XjpgMeTVqbHov0Nj2SNB8PPMZ2h0cPa/HH5odG
          Aj2Fl6aYlREAwnm1uzv5w6afCC5+H9mgDHdsmvLY4bHkPhI07B4JczUoB30Er6cwg0jMZkEi+E3r
          VHYLGIzH4eVlaIz+KXjwiDFphth2Y6hGh8s7bUHHUTL4SVqxBuY73YhcjcCD5iKfmUIiwXBayDGK
          YoC4KzkhLXMKj4VjWAeMskd+HDJIfqy8QbvgfmNQtSU+stkPomfFptXAMypIbrbZcV+YJKYWFHB4
          qJoJUb/H6SWoXJBuw/UFU3X1QD4r9gdQfPSodmBfVIfLDbQD96I2lB6d1XLRCpz7Qi8kXnlFDLq6
          y9fQkHwNOB6LLy2Dm8eBWa0oilTccDZHh2nFKgAR7cIYtCJ1d86rQQzDCo7H5HfgUDukOX38BzhR
          vfvoofeLsx4mGqALztXAvFc/ajWCc+OrScn+KmAhHyphN5ph7DyBSqCMTjKJbx3n63MNSlXC7mo/
          0e0r8IlASaUX/gYuIaMnFFhPsMSh2HfCnmn9YLXcSUjmMVla9rvtQN4NmpFCSwZi8aUQ0gTxs2Z9
          KkQBR/6Zw36xAZEXhw+bJgyXlQ/yBoDxIm1jEJGjvwyXWxDrvXaC/FSauGxuQjTTkJu5bGoG5wJ8
          lGtB3PFXF8ccksgiL/TwszgZ6bYZhNnj07PW7My1rUOZ8AqolVAMeaE90xUg1rG6THPT44tlW6wV
          /mTLvVA1N5SbrGSiE1i9r9IZv+AnYTSGwoI5jmST4uCl5SgOfwOHTDtn/FWHQoc89DqkI9BrIB06
          Vw4lnlXDCyUnPYrDeV6Jil3WlL/vpnzeVGN8U8WxWjUiK1VBRT+J/bEdA5QhT+UODJq3GC4c4WB4
          EjY6eJhnDCuwXjzHGrFsuvwpCXD5UxkOv6/a1ClQ9qSIRpH2Tv2A9k7m27NQLkvVT7euj3buent3
          IJt59ME60QB20vtX2UH29M56+u9PeA40u0Nn7wbev2O4xEZtYn0DkIw+/ir9+GG69QgOrGOuI0vv
          /+DT9MYGS/JnmfpE4xj9eZsnPf7pq/T2trd3bXv3wU1v9N06FN2yN8n5oeeviC3+lB+PYQiFe8bQ
          2ih88EbNY3VnQACe/BoChWHaekAaHrQX8oNxLXy/wm6wbTisJtxNWajzsgMuUyfs4QZ4MORA1YuD
          2kjil3dlOewEXom1nU9qRr2qE/bMKh5NRLYate5bL4TLSnexZxaqTHmqm5guQcgyDC8uRXHgSlvk
          Ny5DMjFeo3mY3lctLmnYrzUDl7KDlKfX/+qhaHio0/wZD2J/9QOr45LCZVldQvtgF9CwoZm1LKEA
          sVtu+AXfeXXVkGC5NMABw30VKrg40POmbzs4y0dAlu9kMR1s1q0USc5clvI9MCs61n0AkxuL9WV6
          pkgST/5EKalj7o/BknwKKDcmpN6jPG4bypjZrpb5FNDe1Yx5LLSNuWxN2e5o4AsOK5gPzoJOUcDZ
          Me5WCOlGCFiVqipDr68xXDUgNYFHYgGExxFNJmuWr2G+Ty3X6k8ZR6w5Iz+GqI+0EsQ5ifqsGtmz
          XvpGj1+VQA/YfHKE7Px7n74/gVfmEHXl5lUvfe9++rfbzhvf2K06e5/cH320AacRjVfKwbHDj+6D
          enL3Puogd6+ln3xNr5h7lEOJdKg74z2uUKeJIEdd9KBf7/ihdGfRsWlVGGktFRiZJYqlNkmjTocL
          tPnjBF73GQauG8LAmQsmnyE1xsOJt4fDoQ3FhcwjXIbXemQr+2RG3qjC631ZbqLyGi+p1962xdu8
          3sAjZnAHNsbLBnVXsIyA/+oNbzkUdwbCi5k3bLE4DDrXeMi57oo2847+IwzHngOH4WB2fgVQb5iu
          uLCcyKB0vRA2GlEXE9ftpHWStAApC5HQQTqdZNr5Tv4gKYS9a6FH/i9t+2PXgSgeDfapHFcgOsQ7
          j8BxCp+utPlL8asO0M3wDerBt42FtsZAzcYU62p4gBwvwA7H+m1dpJJszs51XNRZgqhCiHGpxcRU
          W5NWlk7Cw8SmoQlzTgDv/D6+HAXP/r8eZa9l/4KUvY75K1JIEynijPSet8gBW7A5CzRPuaL4SOhJ
          T7RRP8ZzaO3+BdgSRfKf+GDEWAGIbYyXk9Cj8VDNiCgoftGYNTzse1SF4el3qwqD4/etCkPDlI8F
          tjvHTbcSwWNLnjAoJ/JjUFJynbWmRRQzoTIGNjnGinLgPrjOwWl27irGUUW4qADnjOcWK4fs5ype
          dIShiYjp9kUszKxKrh0FKuzqBiIGQi1R0JyiS2901QbnuOLVhyuWfHAGGa0Ik96OiQlaGy41XhxP
          WOrHsLd2MdhYNeZYZju+J8Zs3PgF0m6GUguTAum6IluZNE9/245CgY9wEsGIuUYIzU/LGt14OJZi
          ghoxjkvPBUuKNl2GntQd8UE+EF2LK3joj0f7CSLToSs6tAJ+HDOeMckC1Kqz2yCyn+WgXha9cGBw
          PetLjXKgRhG4xi/76IOe4QlHDqXW1XtWQOmDS6QgSF8HUdyodMKVED6SZ7y9Qd4SlA+yxRi1o8zu
          Pe1VBy3pZgW0UjMASAkwAzU6Oah6BpXveI86xKg1E5e9dplUtXXa8BG1t8z44NhgMXTKR9Ys+M7A
          rSiF8J0p0r1XcCsqhlD/bpu6DKrGRSBCaW6j8R9rgSfbGAj8d10PrDdtvLnruFHhapPNI4byaePV
          blBMGoL6U6bymB5YMqKm9Y7NOHlJ4V+dXfRpb+uvGkZOICqc63RKXM5+w6LRT2/4phsBxMYn6pPf
          Wn1wNqOjOn3nj5mX+YhyC90TCLNLX5qhd8ibrqCD7wB1E/9c2DW5yXAGa7MzxmlwlLVh+mSCNOCY
          43RdWQBS4/tm+OxWtdG7j/c+vc0v3JPHzpIIkASfrsNNRnubO4Rw4l79mzl0n8Clf1764OvRzjcE
          6sjeZzfpL5agANi27jPnPf0+z+7jmxAV2Ptge+/OVzp1ryyHSfBqfN7vmKjLnSRVIw2By4DCR82l
          /oB+nhYoPTtryuIb+iY2ZYt21j6lx40NUlaoGVezCJHiska9fMbYAJUKc4hIlycytYhUhAEUWuO4
          hf5oK5x1Bsdbr9npVK9aBN+cdVnEZPhI/ykjGRu8uO7eJ3Nb/U8zbjNLUt45aqEJjPuYddyNMZsB
          NltMpht0gx9h4IzyxsHFjsFhz2ftNKmb10y2QVpXCl2O01bDwexMwBiPPm5DkHbZQDB9wwOHMnQE
          Eo48/NUWv7QjAoXV35ZA1BqLyK34tsfWtyq6NuXVQOvs+m6NZn4hvQEyOPOXbhmyMhrOO6sLE9dX
          rsJytsQc0Qclv5/zM7ubOjNmUD90ojJBYbg+INcq/55s7mV22YHhfRKuBJcI+tjvLgWG6+zQa6N8
          9LaH/31W/WqrKZ1KbKFYRxz+h1y/quVqXHiUak3t0L/SbfNtK0hcPfNOdnMowJJeZsqN0w+y74f6
          Gm0V+gkHrfKRYHFY3nF7Cf8GW3YDiashcduKRjQ6tZPznkz4OXHFSq1eLXqpCvuAj3wmmn1UybBJ
          Wa4UwQ9osK+Ouu4QKZ78XyTxX+SWsJatFQzuO9N9JNJdJC5S0Q9HGRhKMeUZFfWVWuAgOmsJj6Fr
          /bQfj7aeEtdQx5ajGuNwm45Z65q0jU3AZuiMuWcmd8dMzJrrmG+W+QGzKO5IZcLAwOzSJWJjqCFd
          oPOMdWCUKERIwIexai1z5/iXzGm6rE5GdirExGlEGTO+9gc2ldO+HDVc8AiDmlQpe2uG7/O9deh/
          AVBLAwQUAAAACADUAhRdPV9avXcUAABdagAAQAAAAFBKU0tCT1QxMS9hcHAvc3JjL21haW4vamF2
          YS9jb20vbWFjcm8vcGpza2JvdC9EZWJ1Z1JlY29yZGVyLmphdmHtPP1v20aWv+evmPqHQk5i2lKT
          No2bFI4tx7r66yQ5aVAUAi1RFmuJ5JGULe5tgNtdL9Dd9nA5ILnNLZIgxXYvu8AC19vNYlug98v9
          OZHyP9x7M6Q4JGeGVGK3vUMHiGNz3rz35s37mk9Hbx/qBwZp2wNtoLddW3M+8Q73bX/53Dlz4Niu
          T3Sr49pmR2vblm9YvrbK/q8bnt0/MtzlHLhben9oeGqokZ+pP3B1p2e2PQDo21kiA6Nj6lptALxL
          6rbw56rdMdq5ADWra+cCbZpelksOaN12B7oSYms4EojLMnxtzzUz321PuzE0+x1RRdU6Ml3bGoAA
          M9WOax+ZHcNlNBu+7RrxWH6iH+maaWvrZj+WG/9xzfDarun4nMij6tpOddQ2HN+0rWSdBZU3At+4
          Mex2jVQ7HFutAV8Ate4bKSFRkKFv9jWsFHzetNt6mlNaAerTHrouatCK6+rBjb7dPjStg78fGsMc
          +KY5MPYsEzXcGe73zTZp93XPI2vG/vCgbrRtF6RH/vEcgeK45hFwRjxf9wGwa1p6n5iWT3b2mq3b
          5Bp558rScj7kBkC+9TZAUtDFRTK+f3/855MXf/uajH/5zct/v//iq38ik8dfTz57TNZ3G+Pff0sm
          T76YPDgZ/+GbyTOoevDr8b+cjL94TMpLXccbP/ucTH7x8OX9z8fPfqamDtiAdjmPyRu1Zn2lWUXQ
          1pWlpdbSkqpF37YOSGNla3ez2tqm+LFB9G+TLCLZsLMRAtYytHbSjqw+C5IdzvfWXX1gXCf/gH+Q
          a7RNVCzjWNTieqkyn2LgyO5DF/oG2bftvqFbxB1aFjQA9rt63zOWxdC0r6AffkNHJd72AH5pM4W7
          2XMNvUOObfcQDSBRF3sQ6DX1Rpla6hjIgLkHvjZilVY1fN31jY6YXxxENHu76YJHB5iFchagja40
          MsFELe2lhwS2vVQV+CZCnRh1UnwN55B2dbdt9JMOhDjdTgpXQouY1dGxDa0Ny1QnP/qY6O7B/nKq
          hnLq+N5exCcWiqQUN7rIgc1zyLH4PdPTEAiElCQwraXtoDokE9XdPcd+si4x15FwGqWUevOkKeLw
          e0qHsYQ12oHhrzgOYNbRz4b4SvPLAtKRcphenWlyiafnGv7QnSq5qL0XWO0eRBHzJ6BURzCQTAFK
          8ymBuPaxR6auH0hM680uKYUE5kOC3KA4ruHorrEz9J3htAtcBbWJ0jzXIrZI3x0acYNQMeF7I/B8
          Y6BZumWjG+exymwUCzNM+IrughlrKTMEOEJXrwIPm7btXMxUz+3+XeODGzvNhWi056Yg8xlSWijK
          onK3ncTgoWDfkEs247liLXODlLojqrD7b0D/h/1+2iA4rj+xTatUuby0NJ+0iruxDRDQzHaPlGqg
          ma47dMAjxbphHliQbnSAwt2YJ7Bb0+tNRzv6TKXh9ZLqkZQUFY6NSUVytGjaR0z8mRynei/we4M1
          wzfa4IA0apyY3JEO/kZBZWImP/1pRiqUArnGxCYCoGgjgLRco2GLhRjrKnonyz6W6fQUEFKFyZf/
          Ovnt/athwCeT33374uuvyOTpyeTx8/Efn5OX90/GTz+dPDkh47/8dfLzP0HmcG/y5+eYQ7x88DDM
          HiaPP0/0OmEsb6C1kDffzHSPcbiQNK334sg/S4+T1kkxc/1krrtLY0HWOQ70QyN08XTMmdx5OcXu
          XtB8S/d7MLkZZU0+KkubWXuPSimSQuiF5iG9KWOak2kxn45IpBu6HMY87d7FMCotJ93oGzS50Ziy
          d+fTkmW1jt3vl1KmmWwnC1ZxEgBijsV5NlYFmYZ3DD2nqDCi3TY7fo9nnIL0eJANwzzo+Qndp/xo
          u33dMogjGNZpWwrileY/WvqYax7PSMi+oLWDLVl9giqyBhGv4buQTcna1SOATFPHHBl9dePdGCTd
          HAbHHorSA1QirGfTjvNsUsH3tgv5FiZAJMDYtwz/vceA4NcLF9LqROXvtu8IKGFhBgOhQGoUWGAA
          F0hZbjhYAuAV4BYZL0JQXgQRb/u6JxIfpYpsn4+HKNV6KocRk8MolMNt+DUrh4geIP1QQg9LMXlQ
          7o7zZYJlhHI5DuVyWwqelk3Er6lglsrugrSadvU8r6ciGuCRTHIdJCgKC1MocoFUQL77Wt8cmGC8
          83xymObZVfBM+UbbKJnz5E2yNOp2BVxFmA6KYQLuygWw7fcLo6vkoAPb/SgIrfM2wI8+zkFN17Y0
          mITkaxYWN1+xsBwUA9vvK8FScQbL3XPiv/hkr2/rPjkcCTrOpLJIShRmHvR/OdMukLTb4Nv1uHYd
          Vz/eNC0jK0AYjKwcqCW79tDqlGjw0j4Zdg6MTaPrw7AdjuaLtkAXdBgUBq9jcDslCkxntlZuVreb
          K9nqsnBWggbNkO/bI8OTTQWo9xSF+xv2COabI3JVqDIcZqELmK49SFwNtNT8wMFUW6qSKa6ad3ar
          rfXN2uoHIp+OhRI8XfurXL5czLTeWSoGV6kszWyDxIAp32uJbWNnc+07lFphYRSVbrn8fUjt5ncr
          tcLSAB0qBnjp8itK7Tvr86XT7jIIcfYYl53lQ4ypgybIOyGMNVHh/Dvq3qgsCwSSBkFZFgpkFCqz
          UqjkUaCDLZrw8n8qEgKv7RqG1cDNHFGijalw5mMU7/On74qEO79xVLgVWNzaHLptnFMWUjMs2G7N
          9Jy+HmwZkFe3Z2p8jDNkOjH08jX7e+W0RyfqjFX5vEW5NpJRCdE8FGeNZ6kSRWZzP6pEocanoBJx
          furrzkzpaVN3qkcGJJjQUJmeImJ5diqasESF85a5QgEqGkzu8xcKeIeYD344mnmNoC2aS0Vl1i4F
          s3XpTpEuBTN1ia7wusZAN61t0SIvz21naNAVW9XKelRMpjqriunJlOp18tbl6S63LBfEJfsHJ5Nn
          PyPj//x6/OTh5Df3yOThp5MH/z2+94hMnvxy/PT3woYRF+QalzddWbpIypfgB6Qys2ZoyMlnX06e
          PiIvP783efqAAFOTpyeLk//41eSzoqygPLt9s32oHND3Q5br1TUl3NUQ7vZGrVktnHytmm67L5ji
          R0WZfrVHirpAXveOvCoSzyslRLGr69n9zky+bgMaNHUXnDXpKX0dxXz2zq73/83V9X4Aju57U/h3
          5VXMaG/Wq9XtV9L58DACsJ3c5p0etjE7JNx4T+yDH/fwCE4p3qIl4T6Z6VUHjh+UMhtl2Q1wLNPd
          OGkPuQ223AEtLxWYfkanzLSt2uZmrVFd3dlea8ym2eAourLN5aiAtkAmS48BCMIDFkwNTYs/ThEV
          gbc1LDyjlNhIpJDRrn8TT4Po+zAo/FZ/jJBDmxjcEG84DsVPmOwHvvHRxyQYHgnGDk/vNO07wyP5
          kHXpSR/5aNE1aXX1Rs6smJ2nUme3uGVjOcKdPXomTOsYVAFrCBRuSpZpmpFOkhka3JlJawS332la
          Ek1nxCB+8IQoyswuHKWlOjJiWhr4KN1Nb0iHdXioA4ZNpNiMi0yHpWKmDMpHQWGMwIDWN6wDvyeH
          6bLjXgr8r+TysoYpsovkUSiRWXCnbnnD4FRPpFQ92/aM1Rgmkfpyx5VJdyBqz0FoEOyA3Vt4tjDE
          JQ+1XLOt2laVrpveqq1Vd1ort1ZfzwqVBga90DzUat84EGkSz9gH1Tut1Z3NnXprfae+tdLM0hWZ
          9etQu1FrtvB0bZZSeOz2VKis11e2qhI667uNU6FRC6nUtpvV+q0VwakZ8fYTtXiZnlHlD9WsSuOE
          eyNoBo4i/1ErmlJVmPOBoNg1D4augAbIJNstdIJFv3KdgqC/Xru5V8etqpWbrer26s6aeLQZW8JT
          g/wB3qxd80dMM7lP8vYC6eMPcWTAAyZJaHUelITVVjY3W9i3VXGKk44CdHKjuo0BvYUf4ikO9gJj
          2BTYk5w8oOeqEBGmi0yxEDJOiDItoiO1+lFbcLgywT2enYCU1JcwSekjaWC0MXTwNoLRQaX2sjkr
          z++Mms0XDXII4LhGE7NV3TNKvpQUFtbJ5EnbjEDAKg/F1XczXwX5JB0CIKSUenLoNfrbqu7o+2bf
          9E3Dg+TTUS35RHLm24AI1S4kQXx2gYvymunZoy65SnnWuEiSOYfOi6ir2oyccqkQUW43sWhh2KP8
          3Nm7damy1DAGJh6f012VpoTTt+5rKML/QdmchVzEf+VMr9LT6Jk7LOjcet8Ymft9Izc1jc5nF56y
          hY4RQtlAdGoTA036PpjcSucCKFtbnU5rY2Mw8Lw5eZbIroppe9kINK91GRmkjVTBBS9nGLbEZ4+j
          Y/+tOcGhOtbJ7Pc5beBcmktN3ehtPu1Wtd6o7WxrjbUPMI3CqVzl3bSSpa5YkrZso53b90m1ySx2
          J65jkiP2nzwZSIBnkLHmdJInxBDfPdTozIGFd22t1tjdXLnT2oYkUjySOAqJilOijK69hb5dTHaO
          3p1axFE7C+r16uZKs3ar2tpdaUrWE7grnSCmenW1uVO/09rauVWrNhTHOSnzi6GOngnvtUZrt7q9
          Vtu+KWa8rCQa3RyT6a+rmZZnuEWyzQxrxRx79UOYq2yvYH4Ks5btZmuvXlMv3zFBFUpk0a7jLsoX
          S6jDpHbFzecVbi/uMGHygWTU7BuduUyTzFpE4k+n25FL3nYMK3llTz0KUUfV0ptzj7NchpxmZEf5
          Oz2xZXv0inJLI5FJEfhH35uSYsYI6P3OnIkXvQSqHoBuRy36GI/GwrZkbVJUtK29D6v11s5ec3ev
          2drard5sXZINY/SrcPcRZUE6pqq/CKLuKRfXqiPfcC2dXi711swcEUVF5U6VCBSHoLDMCV3ttLFA
          xd8AWWiQbHm+ZOqH9YND+Omll1IFSkm6+CNHtIDrIo2kZ6aIQIVeVd2HZGPoG7s63u/5gSmnNLNl
          S7PRXN+wOuk7geFyVeSXMvcvESbVjH5WLPNjmWGpP6IiX+6PEX4XC+mKquIn7FS37KJSypzZIAuF
          VARL7g29qKiORsardzf21tdB68Klu7XWznqr0axXV7byg0n82/RXHjEdp3idSzxLEjZIxJZwexSX
          cES6KL5KhiWhicwa83SHIe3a6iEEqyDvE6bPMNEXn9MWKTrlVXIbLZZDbXt9p9UER75yc6W23YKk
          uloX7k2h36UWKljA4s6Cz0A19D1sz6C1urGyfbO6Jlx25J9hkAqLemJN73QoYJGjiOHOHe87FYf0
          ROtTjGZijTlTHT8ykV0YTAlO5pW4jciO7usKIaQ6Faqgnd2NxELPzSC+cE9SeTMN10U88ycGua6+
          wsb3WXp7Dalqju2ZNPukuO1u1zN8yY47hWdX4nLNKcRELsQ8F7KZRAe0Y9f0DXa9eg2Iq8nG+qm2
          ZeyGGgJZzgvDURGsCU4jsK1a3WUC7/b1A4/IBzIqsdkWjhpyP59/Bhavzkt3uF0DuucV9K/KIz10
          J0IUdYRWAvIUO74CuVHisQbl3hLLomjs4WcExVYyxe9UsLxreuYg2hPDQ0FnSiIcqNOjknClEvfD
          cnHFAYvIXSe7Hw/fKbGZz4JAPKfJBa4BTHnACXW7b7/aYIR5O0UVtw4nPamvdOVBBCl8ZgmL8Hkl
          4cp58mWT1ORCsQwsUpXp6hI3TAkg8Ym31Gqvwr/mL/bSzsvXDbG84tohFuHxGoFHlS90S1FrQ6eD
          y/25brzYyhaWo3wQ8akAEZQqe+P/LHz8Ltbk6Zokp+IpXQ3P1klO0XGPaWUmFsfZT73sp248v0/b
          QDc8uKQ6ETLjZp5yAy/RKtxFY/2uAVyJPRl2fJH0EusH018XF0m8UUrGD++Nf32fRDtok9/cm5w8
          wi/bt8oVMvn5nya//aPGt33x9VeTL54TJDV5fEI8QLXgMFzsXKSLdwTGJ7+b/NtzQEUmv3gMTcb/
          /JBHMnl0sogPAj55SCbPPx1/8fh//jb+y/Px428B/FcvvvnD5Nk9RD55+ujFf3318sGj8Wdfxkwk
          uoxsZrusUg7a4rW0I6sFqCDsuR9yTM6TXiz4kLT8IRQKwBqfJ2/BZL/Cv4RCH0Ex6esfiW/DI/xI
          m+W8m9ITvpkielnkWPmqiOjEU1RQdPStiGP6ToTkYLvqfm2pTa5fJ+W3FW9S5D2WwVBcycEgej0n
          Km1100B1ML9UevttfMklZ3cLSxli43noSj5k5TIA7hdCCf1mvb8AUhR0gL7mYV64oHrEo4S6OI9P
          GQ6cUhDIMvJSAHIqz+OSonI6WhrFcMrHVIbDnJvXpdLCW1eodIstn71zqaCAsZTLlYJSptAJSVeu
          KN5iOVIlKlhKJUa7aLfeZd0qBly+cvq9QiUCz6PWIiwJTRoOZfP9V8N3dPRqr7nk3NtIBAkaSc88
          SJx5lOCCBP89Dh4w3Oz/RXLpx0DCo/gxkPwYSH4MJOQMA8npxpEfShihLo4SoEMneMVYvsco2Jic
          vu+AT+gAuimA4h6O+ImXMIBlQ9WonP0WCL6NKgI4wbf4eRW+89O3zfSLSBEpIEb6P21xEUx8WQ5e
          CcErxcDLcbM88ArHTBZcJmDRrVapiNO3WNk93+w3t6g0EwF6waUR+hpx80M0wo5CWEWQxhVDfNZx
          BGaM8TiQ7WGR64owAP4Inxk8P/1N4eQ7lCl0YlIX7xk5e1A5Ozxt7I3iPjGFCbDHOTDC6/JYZvIo
          7KdYu7KvAH635pv97PfM9qFleJ4wse2gblFfpe97pVEFhnvEGxyFCXiYAGGCNIyHeEZlSCIBx/uk
          TK5OF6enIIgmQJBABmK4uEQOPC0A0WJHDKZGYlOLmvZWsClqU1tTQzDLytTEVEZ5VCieUR4lBiWh
          huV1bQbG4gJQyHkYlwKdpdUk1REcD/AF6SAoicSlBLQ+qIgcnHA3MaPwRgWGCLMq0CbBGQ+ovk4W
          OoGIAOrfwjWqe+kqlOc1UHM1eYb/PVBhGfoLqN9Z9AFDH6TRJ38TeZ2MosgdjsCPFI1bdOigY0ui
          B+hHuHHEHlYV1AayZkHUbGOGJ9z1/Ldtw0c+WcO75/4XUEsDBBQAAAAIANQCFF0sWiQ1MAwAANEr
          AAA/AAAAUEpTS0JPVDExL2FwcC9zcmMvbWFpbi9qYXZhL2NvbS9tYWNyby9wanNrYm90L01haW5B
          Y3Rpdml0eS5qYXZhzVptbxNXFv7Or7idD9VYuBMnUGhB6a7jmODixF57gK0ARRP7Opliz8zOjE2y
          LRK0BiGI1LBKRGATNrsLalm1Ugq0gJRP+3My4/+w58yLPW/XdsqutFcixnPPOffc8/Kcc+dak2rX
          pWVKampLaEk1XRW0L43rS6p59tgxuaWpukkkpa6rcl2YlxS5QQ2YiUxImiZka6bckc212GRNVUyq
          mELB+WBOV1ckndbLOm1QnSo1ajAptZZQdpUGheCvHqNc1iVtRa4ZQk5tqvHpFq3LkqDp6pcUlFYV
          YR4flPvfWWIVagoXdTn2XDWEmbbcrCdPKPUmTZo5L+FMfBWYKqqqljADGnfkOtWFKjVNWVmOm6gj
          0xvCnC4lOsKZvAR/5nS1rcWmb8j1ZdjgTNs0VYU1W5QVKulFaU1tx13p0VQpvT4jxdX3pkW6aqIW
          EF9ae6kp10itKRkGmZdkxQ8iAjRUqRuk/+CrYwSGpssdyaTEMCUTGBuyIjWJrJikkv/DYi5bFi9W
          8mSaTGYyk2dDDMkeJlrc50GuWEzCDG0YYSJ/P0RtNAxq4lcGgam2ayuipIMVhlJAilVhg+3IQrjP
          PkFObcPXaZIJ07gW8UKLtMCk/v+nHTp/KLCYN8O70SaAVugC9xufSoF/kPL3pQ7VdQg7bx3VBIPR
          OumAS4mq5HQK6/JumBND6tB6QQH3gLVwDzTleQ6H0cZ1+jwJxN6a3koRZ00TPtmNKQK6V9cMk7aq
          VO/INcrP52cL2cVypfR5PicWSguL1XzlUiGXT50NLACuBKHIG/Uzz3kgyKXJfGk2D5IKl7JiPqig
          3CC8k/bCpXylCmsI1dkLi4UFkXw2TU6cIB9+GLI4jtoKrV2v0majTPWWbBiwBd4HVUHrPxPKpaq4
          uFASC+cKuSyqX02RD6ZJGPWEcr4yX6jiyotzleyCmJ8NGhuHTv/UBtGD1QweHV81dUCPK9e+Gm/t
          m2lMqKmA6W4OrBAEBKKrKsYkrhF8zpsrshFgRzIBUqWky4DnEnqSD9KjQUVYvZjA44Eb730KuTxs
          vJJAWJbqddglf/KTNJmCf+5nAuEMWHUZEFGpO9WCd/4K+vISP3kado5sH6eCjh9kq2xCzLv79R9G
          9+rQCB4u8Fz58+qFmZLIsSiCKlw+XxDzLMKq/GfKn8gkTY9nIjCPqy+ypUmj3Wzyyds02ksjNgkU
          gy2K2TL59xsyVyrO4ue5YiF3Af9z3ntQLRZm8/if2fzMxTlA7hyXLCrmjlMZ8MWJj+GP65EEHscs
          kyfjkyONEgpA96Ms6VLLIEZTg/27BgrIbWoodx7gXIa8AtUgUlDBDMvSoEka2YJGdqstkTwDu1+j
          5pUGxp0UiL338PDNgd39mdjdHetd177/jNgHO4dv97koT0nJQX29XpQBGhUA9Q756DOsnbrp11UH
          D9zOjPe7CiHrQmY2l8sDvMwUigXxCwBQUSwszFVTKdb+pDRZcvQvauFI8japDt2kOtjklEB6m+vW
          33d663fIxQI5/HW9t7XDRYkTdxcGQMToD/r7qknKrC7dwILWlNYMV4MoZjq+ZZkoRumPqO3mswvZ
          ufxiCZCsmP1icQDVaaYI6CwFTdINCsXHBfozHDmO5cnD/QWpRcGwMQFBh+C4OcBplqtUlqsGPcyI
          lB8QjgNdcWo3UU8zad4jX83EfDVj+To55SQsM18HCqWRO2gmr8X1dPZM5T1MtpS79io/lQmuhy2d
          0waBCKcfwS4MYo3nXK7FlsGFNRxIgzZoWaeG4fZRECmTIdFtrQ4dVckhd0kSpZQUT+3ciqQs034y
          BTYksGiiqRNuFf3hNflev+hr7Yqq874llyQ97ZhD8wggQlW1SSWFNHS1ddHANi+eqcjRkZpt6hjQ
          5SQfoSnOxmhdA0MHafIpQWvH7ewISuFptrnGp+ICQiZ1iVmZFzJHxARVRBdRh6QGxBCxoQ9aAXY5
          rhhVG08KGwacrSQV/8BRZVSDM6AcILj9dMP67jHpdfftd9ukd2cdilTv/ltib9+2H/10VYHqdfjq
          F9J78jf73vYZkuGGCxzaFcXJXWz5hE00Elwi9OwW8SR0I59i7Q81JBH2MQpV+Fx3/PjZhNmwjRPr
          yFENjwUmvHRIbDAicGA5jRxR8VyiQPgkJWeEdLjqrvrf3u59u3OGiNnKXF4kOad3BE3tB3tXFVB2
          COeRNuZtLvg1nC7jlBnHH0UtcrLGET0AhRjZ25+XzBWhJStsCn/AwhVqqG0dz6opLBqzsqFBUzNP
          4WxXw2c35Lq5UpZXadMBROidR0o9fSrDpEmx2SdPx9mCyeDZKbn6xk5k/XPJIObTfRlxiBoE4jgw
          NUYs9mPQWr8FPXVy2HGDzLJednv3D+zdLrHuda3nr60Xr0lGOG2/vkesv0BnHkxIri9otGZBpCmK
          cMD/YjSPC3wnhhMe8XgYFpBUK7z23gQipw4NbfP7VINicSJ0pkkGMI4lYgxszbZNNVuDTDHkJbkJ
          W/ZeEhHD+4wn8DA2zDY+CRn74v4XiAiHMVI6d24UCsbPhof7t4i99bP9aIPYj/YPX+5bG9v29/js
          vr27ziVl7ojzEHP5o58lR4EyDp2abV2JgnXY+op55RrRVB8E8PvUNXYNRSxRa86LJ+htazqlCg/c
          0a03mqpkklVGfADDlcw1hjciq11GMIZ+eYJMNRIXWRuyyOSYi5yn8vKKmbzKkQKvH3SnMxkodC4Q
          EvvZQ3b0cda/XvQe7hD7H+v4wSJzKpzTSPGrKZao9Bjca+HQiXpuYoLY3/xoP3kBcIIJEIPrRxuQ
          IMS+u4HAbT/u2nvd3lNA7Ee3iPXgGSRGVJz1qmt9B6QPduy9DUwmEAtm8oDKen4AFK+tb94CtxDi
          DbyDF8Cb5iyFMg0HH/BTDKlwsNGKESLDmBKxCoeDV8OQCseR0QpHpH5i2Djg5YIPsW7fP3x3Kw47
          OBKSH0cSAOC4mQBUglMcJI2t4yq7kVljT8G5st000WNRf45u1lxP/yZjBkffsNjbevocJ9zwihAX
          cuQ+OTrioM2eifbYaYSU4EUCs+3wa/yId4pOZRracDgUg2bjpEB6jzexSbN339oPdp2MfvqQS+IY
          9wUjM/tkI6cqinNfxie+aBz7YIeD6/cA1g8H9t6t0V0TwlLv7i+Hrw56W9t29639ZFNIrPjRR//v
          BT+k3zlVrzjpkKxo7CJRqDn3j27dz0karEa9XTBOOYHb5WjZ6SvIfOuPqo6MYlUbEcSqFni74tQr
          RFZo5LgEsvdqikGRUeUkKMitJP23AA6wIX/Laa/yirTUhOhvSE0j+rYMtfXvawORhFtPE88v/sLO
          TwRS49lb1Vjm7l9pyUpDHXFgRJIhp0Q/BZMTz97dJiGkxSZkEiDnNfYM9vaP1u4BPLLub2Ir3nu8
          BWA0SFHGmfPwzVuvOSGHL9ftpxAB33ftp3dI76/d0IUJg79chS37CgP53j3Qh5QWJpjnCq6SzyHP
          loMw9svXxNrchA7K0eTOOwDS4ewOYC2ghABS3bH2nvvdgL23BQZhcU/kJv44UUH2J5v2y58mIO6t
          f65P2G9+sO+uTxz+vG/9esuz71WFIcRTs7e+bu8enCHzakemxoR3DTuUB5o88A9wbqCW3b20XzGs
          /S3wctp3ur19DwmgKwRrHu4/xg/ogaGuWBsvrAf3sCNMPPgHI2zoaT9IGL/g9Gff48ZETrwxkeM3
          JqeG35igKmnkCyYdiMi5v9xyaJDB4/dA3f/tCls/V7MAgrkl4qjv2fq/fQrRCfNZMXd+sZytgMHi
          +M9gulzJlhdzJTDxghh17tj7GqBUYG9s8qaW8OOKEXvuv1M8+ivDKXD1pyczCTXxN9gERyye3HA6
          FQwn17FNLdGSzs1H6BbGuf8JWi9+08hzbgrjAQ0+3J4XSuJn0yRDfke44xyBZxwcR0kHG2rSMriw
          I0f8BMrvQ7wmBFXyfniTU+vUvdVy+3X3u1vnCOxCSvp1VERcSFRQjMMf+T1SgBhLcvBXcV9/HeB2
          J6sXi+Ji6QJOobDBcdDvwPqyPZX7b7jIePU60Jl4z7W2mV81dYnnBspwwX2NwTMLunLJ+2f+Hmvq
          VMptGqFZpO5Vjt96eMsEFob4py51nKZP9F9poMZrnky9HVq6pXaoKBnXRRUvpvxpN2BvHvsPUEsB
          AhQDFAAAAAgA1AIUXZ8Hl+1eAAAAbQAAABsAAAAAAAAAAAAAAKSBAAAAAFBKU0tCT1QxMS9ncmFk
          bGUucHJvcGVydGllc1BLAQIUAxQAAAAIANQCFF2yol9fRgAAAEkAAAAWAAAAAAAAAAAAAACkgZcA
          AABQSlNLQk9UMTEvYnVpbGQuZ3JhZGxlUEsBAhQDFAAAAAgA1AIUXbArVL+uAAAARQEAABkAAAAA
          AAAAAAAAAKSBEQEAAFBKU0tCT1QxMS9zZXR0aW5ncy5ncmFkbGVQSwECFAMUAAAACADUAhRd3bTM
          /HQDAABJBgAAEwAAAAAAAAAAAAAApIH2AQAAUEpTS0JPVDExL1JFQURNRS5tZFBLAQIUAxQAAAAI
          ANQCFF0fYDP+9gkAAEoKAAAZAAAAAAAAAAAAAACkgZsFAABQSlNLQk9UMTEvYXBwL3Bqc2tib3Qu
          amtzUEsBAhQDFAAAAAgA1AIUXVGsTF5EAQAALQMAABoAAAAAAAAAAAAAAKSByA8AAFBKU0tCT1Qx
          MS9hcHAvYnVpbGQuZ3JhZGxlUEsBAhQDFAAAAAgA1AIUXWnLCxEfAgAAcQYAACoAAAAAAAAAAAAA
          AKSBRBEAAFBKU0tCT1QxMS9hcHAvc3JjL21haW4vQW5kcm9pZE1hbmlmZXN0LnhtbFBLAQIUAxQA
          AAAIANQCFF2mHELE7AAAAKUBAAA/AAAAAAAAAAAAAACkgasTAABQSlNLQk9UMTEvYXBwL3NyYy9t
          YWluL3Jlcy94bWwvYWNjZXNzaWJpbGl0eV9zZXJ2aWNlX2NvbmZpZy54bWxQSwECFAMUAAAACADU
          AhRdqXlRv60AAAAsAQAALAAAAAAAAAAAAAAApIH0FAAAUEpTS0JPVDExL2FwcC9zcmMvbWFpbi9y
          ZXMvdmFsdWVzL3RoZW1lcy54bWxQSwECFAMUAAAACADUAhRdajgnhm0AAACcAAAALQAAAAAAAAAA
          AAAApIHrFQAAUEpTS0JPVDExL2FwcC9zcmMvbWFpbi9yZXMvdmFsdWVzL3N0cmluZ3MueG1sUEsB
          AhQDFAAAAAgA1AIUXaSZniO+DQAA5jUAAEEAAAAAAAAAAAAAAKSBoxYAAFBKU0tCT1QxMS9hcHAv
          c3JjL21haW4vamF2YS9jb20vbWFjcm8vcGpza2JvdC9DYXB0dXJlU2VydmljZS5qYXZhUEsBAhQD
          FAAAAAgA1AIUXToN+EvRDAAAl0IAAEsAAAAAAAAAAAAAAKSBwCQAAFBKU0tCT1QxMS9hcHAvc3Jj
          L21haW4vamF2YS9jb20vbWFjcm8vcGpza2JvdC9BdXRvQWNjZXNzaWJpbGl0eVNlcnZpY2UuamF2
          YVBLAQIUAxQAAAAIANQCFF04y1mfmB8AAHWUAABBAAAAAAAAAAAAAACkgfoxAABQSlNLQk9UMTEv
          YXBwL3NyYy9tYWluL2phdmEvY29tL21hY3JvL3Bqc2tib3QvUmh5dGhtRGV0ZWN0b3IuamF2YVBL
          AQIUAxQAAAAIANQCFF09X1q9dxQAAF1qAABAAAAAAAAAAAAAAACkgfFRAABQSlNLQk9UMTEvYXBw
          L3NyYy9tYWluL2phdmEvY29tL21hY3JvL3Bqc2tib3QvRGVidWdSZWNvcmRlci5qYXZhUEsBAhQD
          FAAAAAgA1AIUXSxaJDUwDAAA0SsAAD8AAAAAAAAAAAAAAKSBxmYAAFBKU0tCT1QxMS9hcHAvc3Jj
          L21haW4vamF2YS9jb20vbWFjcm8vcGpza2JvdC9NYWluQWN0aXZpdHkuamF2YVBLBQYAAAAADwAP
          AFAFAABTcwAAAAA=
          EOF_B64
          tr -d ' \n\r\t' < /tmp/PJSKBOT11.b64 | base64 -d > /tmp/PJSKBOT11.zip
          mkdir -p /tmp/src
          unzip -q /tmp/PJSKBOT11.zip -d /tmp/src

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: '8.9'

      - name: Build APK
        run: gradle -p /tmp/src/PJSKBOT11 assembleDebug

      - name: Prepare APK
        run: cp /tmp/src/PJSKBOT11/app/build/outputs/apk/debug/app-debug.apk /tmp/PJSKBOT11.apk

      - name: Upload APK
        uses: actions/upload-artifact@v7
        with:
          name: PJSKBOT11
          path: /tmp/PJSKBOT11.apk
